-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ViT_Block_MLP_tiled_oc is
port (
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    m_axi_gmem0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RFIFONUM : IN STD_LOGIC_VECTOR (12 downto 0);
    m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_w_up : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_AWVALID : OUT STD_LOGIC;
    m_axi_gmem1_AWREADY : IN STD_LOGIC;
    m_axi_gmem1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WVALID : OUT STD_LOGIC;
    m_axi_gmem1_WREADY : IN STD_LOGIC;
    m_axi_gmem1_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem1_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WLAST : OUT STD_LOGIC;
    m_axi_gmem1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARVALID : OUT STD_LOGIC;
    m_axi_gmem1_ARREADY : IN STD_LOGIC;
    m_axi_gmem1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RVALID : IN STD_LOGIC;
    m_axi_gmem1_RREADY : OUT STD_LOGIC;
    m_axi_gmem1_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem1_RLAST : IN STD_LOGIC;
    m_axi_gmem1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RFIFONUM : IN STD_LOGIC_VECTOR (12 downto 0);
    m_axi_gmem1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BVALID : IN STD_LOGIC;
    m_axi_gmem1_BREADY : OUT STD_LOGIC;
    m_axi_gmem1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_w_down : IN STD_LOGIC_VECTOR (63 downto 0);
    norm_out_113_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    norm_out_113_empty_n : IN STD_LOGIC;
    norm_out_113_read : OUT STD_LOGIC;
    mlp_out14_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    mlp_out14_full_n : IN STD_LOGIC;
    mlp_out14_write : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    in_w_up_ap_vld : IN STD_LOGIC;
    in_w_down_ap_vld : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of ViT_Block_MLP_tiled_oc is 
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal internal_ap_ready : STD_LOGIC;
    signal FC1_tiled_oc_2_U0_ap_start : STD_LOGIC;
    signal FC1_tiled_oc_2_U0_start_out : STD_LOGIC;
    signal FC1_tiled_oc_2_U0_start_write : STD_LOGIC;
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_AWVALID : STD_LOGIC;
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_WVALID : STD_LOGIC;
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_WDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_WSTRB : STD_LOGIC_VECTOR (0 downto 0);
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_WLAST : STD_LOGIC;
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_ARVALID : STD_LOGIC;
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_RREADY : STD_LOGIC;
    signal FC1_tiled_oc_2_U0_m_axi_gmem0_BREADY : STD_LOGIC;
    signal FC1_tiled_oc_2_U0_norm_out_113_read : STD_LOGIC;
    signal FC1_tiled_oc_2_U0_fc11_din : STD_LOGIC_VECTOR (7 downto 0);
    signal FC1_tiled_oc_2_U0_fc11_write : STD_LOGIC;
    signal FC1_tiled_oc_2_U0_ap_done : STD_LOGIC;
    signal FC1_tiled_oc_2_U0_ap_ready : STD_LOGIC;
    signal FC1_tiled_oc_2_U0_ap_idle : STD_LOGIC;
    signal FC1_tiled_oc_2_U0_ap_continue : STD_LOGIC;
    signal Relu_tiled_oc_U0_ap_start : STD_LOGIC;
    signal Relu_tiled_oc_U0_ap_done : STD_LOGIC;
    signal Relu_tiled_oc_U0_ap_continue : STD_LOGIC;
    signal Relu_tiled_oc_U0_ap_idle : STD_LOGIC;
    signal Relu_tiled_oc_U0_ap_ready : STD_LOGIC;
    signal Relu_tiled_oc_U0_fc11_read : STD_LOGIC;
    signal Relu_tiled_oc_U0_relu2_din : STD_LOGIC_VECTOR (7 downto 0);
    signal Relu_tiled_oc_U0_relu2_write : STD_LOGIC;
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_AWVALID : STD_LOGIC;
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_WVALID : STD_LOGIC;
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_WDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_WSTRB : STD_LOGIC_VECTOR (0 downto 0);
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_WLAST : STD_LOGIC;
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_ARVALID : STD_LOGIC;
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_RREADY : STD_LOGIC;
    signal FC2_tiled_oc_2_U0_m_axi_gmem1_BREADY : STD_LOGIC;
    signal FC2_tiled_oc_2_U0_relu2_read : STD_LOGIC;
    signal FC2_tiled_oc_2_U0_mlp_out14_din : STD_LOGIC_VECTOR (7 downto 0);
    signal FC2_tiled_oc_2_U0_mlp_out14_write : STD_LOGIC;
    signal FC2_tiled_oc_2_U0_ap_start : STD_LOGIC;
    signal FC2_tiled_oc_2_U0_ap_done : STD_LOGIC;
    signal FC2_tiled_oc_2_U0_ap_ready : STD_LOGIC;
    signal FC2_tiled_oc_2_U0_ap_idle : STD_LOGIC;
    signal FC2_tiled_oc_2_U0_ap_continue : STD_LOGIC;
    signal fc1_full_n : STD_LOGIC;
    signal fc1_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal fc1_num_data_valid : STD_LOGIC_VECTOR (6 downto 0);
    signal fc1_fifo_cap : STD_LOGIC_VECTOR (6 downto 0);
    signal fc1_empty_n : STD_LOGIC;
    signal relu_full_n : STD_LOGIC;
    signal relu_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal relu_num_data_valid : STD_LOGIC_VECTOR (6 downto 0);
    signal relu_fifo_cap : STD_LOGIC_VECTOR (6 downto 0);
    signal relu_empty_n : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_FC1_tiled_oc_2_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_FC1_tiled_oc_2_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_FC2_tiled_oc_2_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_FC2_tiled_oc_2_U0_ap_ready : STD_LOGIC;
    signal start_for_Relu_tiled_oc_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Relu_tiled_oc_U0_full_n : STD_LOGIC;
    signal start_for_Relu_tiled_oc_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Relu_tiled_oc_U0_empty_n : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ViT_Block_FC1_tiled_oc_2 IS
    port (
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        m_axi_gmem0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem0_AWREADY : IN STD_LOGIC;
        m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_WVALID : OUT STD_LOGIC;
        m_axi_gmem0_WREADY : IN STD_LOGIC;
        m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_WLAST : OUT STD_LOGIC;
        m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem0_ARREADY : IN STD_LOGIC;
        m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_RVALID : IN STD_LOGIC;
        m_axi_gmem0_RREADY : OUT STD_LOGIC;
        m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem0_RLAST : IN STD_LOGIC;
        m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_RFIFONUM : IN STD_LOGIC_VECTOR (12 downto 0);
        m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_BVALID : IN STD_LOGIC;
        m_axi_gmem0_BREADY : OUT STD_LOGIC;
        m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        in_w : IN STD_LOGIC_VECTOR (63 downto 0);
        norm_out_113_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        norm_out_113_empty_n : IN STD_LOGIC;
        norm_out_113_read : OUT STD_LOGIC;
        fc11_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        fc11_full_n : IN STD_LOGIC;
        fc11_write : OUT STD_LOGIC;
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        in_w_ap_vld : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component ViT_Block_Relu_tiled_oc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        fc11_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        fc11_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        fc11_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        fc11_empty_n : IN STD_LOGIC;
        fc11_read : OUT STD_LOGIC;
        relu2_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        relu2_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        relu2_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        relu2_full_n : IN STD_LOGIC;
        relu2_write : OUT STD_LOGIC );
    end component;


    component ViT_Block_FC2_tiled_oc_2 IS
    port (
        m_axi_gmem1_AWVALID : OUT STD_LOGIC;
        m_axi_gmem1_AWREADY : IN STD_LOGIC;
        m_axi_gmem1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_WVALID : OUT STD_LOGIC;
        m_axi_gmem1_WREADY : IN STD_LOGIC;
        m_axi_gmem1_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem1_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_WLAST : OUT STD_LOGIC;
        m_axi_gmem1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_ARVALID : OUT STD_LOGIC;
        m_axi_gmem1_ARREADY : IN STD_LOGIC;
        m_axi_gmem1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_RVALID : IN STD_LOGIC;
        m_axi_gmem1_RREADY : OUT STD_LOGIC;
        m_axi_gmem1_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem1_RLAST : IN STD_LOGIC;
        m_axi_gmem1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_RFIFONUM : IN STD_LOGIC_VECTOR (12 downto 0);
        m_axi_gmem1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_BVALID : IN STD_LOGIC;
        m_axi_gmem1_BREADY : OUT STD_LOGIC;
        m_axi_gmem1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        in_w : IN STD_LOGIC_VECTOR (63 downto 0);
        relu2_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        relu2_empty_n : IN STD_LOGIC;
        relu2_read : OUT STD_LOGIC;
        mlp_out14_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        mlp_out14_full_n : IN STD_LOGIC;
        mlp_out14_write : OUT STD_LOGIC;
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        in_w_ap_vld : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component ViT_Block_fifo_w8_d64_S_x9 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (6 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (6 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component ViT_Block_start_for_Relu_tiled_oc_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    FC1_tiled_oc_2_U0 : component ViT_Block_FC1_tiled_oc_2
    port map (
        ap_start => FC1_tiled_oc_2_U0_ap_start,
        start_full_n => start_for_Relu_tiled_oc_U0_full_n,
        start_out => FC1_tiled_oc_2_U0_start_out,
        start_write => FC1_tiled_oc_2_U0_start_write,
        m_axi_gmem0_AWVALID => FC1_tiled_oc_2_U0_m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY => ap_const_logic_0,
        m_axi_gmem0_AWADDR => FC1_tiled_oc_2_U0_m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID => FC1_tiled_oc_2_U0_m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN => FC1_tiled_oc_2_U0_m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE => FC1_tiled_oc_2_U0_m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST => FC1_tiled_oc_2_U0_m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK => FC1_tiled_oc_2_U0_m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE => FC1_tiled_oc_2_U0_m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT => FC1_tiled_oc_2_U0_m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS => FC1_tiled_oc_2_U0_m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION => FC1_tiled_oc_2_U0_m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER => FC1_tiled_oc_2_U0_m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID => FC1_tiled_oc_2_U0_m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY => ap_const_logic_0,
        m_axi_gmem0_WDATA => FC1_tiled_oc_2_U0_m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB => FC1_tiled_oc_2_U0_m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST => FC1_tiled_oc_2_U0_m_axi_gmem0_WLAST,
        m_axi_gmem0_WID => FC1_tiled_oc_2_U0_m_axi_gmem0_WID,
        m_axi_gmem0_WUSER => FC1_tiled_oc_2_U0_m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID => FC1_tiled_oc_2_U0_m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY => m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR => FC1_tiled_oc_2_U0_m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID => FC1_tiled_oc_2_U0_m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN => FC1_tiled_oc_2_U0_m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE => FC1_tiled_oc_2_U0_m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST => FC1_tiled_oc_2_U0_m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK => FC1_tiled_oc_2_U0_m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE => FC1_tiled_oc_2_U0_m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT => FC1_tiled_oc_2_U0_m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS => FC1_tiled_oc_2_U0_m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION => FC1_tiled_oc_2_U0_m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER => FC1_tiled_oc_2_U0_m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID => m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY => FC1_tiled_oc_2_U0_m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA => m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST => m_axi_gmem0_RLAST,
        m_axi_gmem0_RID => m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM => m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER => m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP => m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID => ap_const_logic_0,
        m_axi_gmem0_BREADY => FC1_tiled_oc_2_U0_m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP => ap_const_lv2_0,
        m_axi_gmem0_BID => ap_const_lv1_0,
        m_axi_gmem0_BUSER => ap_const_lv1_0,
        in_w => in_w_up,
        norm_out_113_dout => norm_out_113_dout,
        norm_out_113_empty_n => norm_out_113_empty_n,
        norm_out_113_read => FC1_tiled_oc_2_U0_norm_out_113_read,
        fc11_din => FC1_tiled_oc_2_U0_fc11_din,
        fc11_full_n => fc1_full_n,
        fc11_write => FC1_tiled_oc_2_U0_fc11_write,
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        in_w_ap_vld => in_w_up_ap_vld,
        ap_done => FC1_tiled_oc_2_U0_ap_done,
        ap_ready => FC1_tiled_oc_2_U0_ap_ready,
        ap_idle => FC1_tiled_oc_2_U0_ap_idle,
        ap_continue => FC1_tiled_oc_2_U0_ap_continue);

    Relu_tiled_oc_U0 : component ViT_Block_Relu_tiled_oc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => Relu_tiled_oc_U0_ap_start,
        ap_done => Relu_tiled_oc_U0_ap_done,
        ap_continue => Relu_tiled_oc_U0_ap_continue,
        ap_idle => Relu_tiled_oc_U0_ap_idle,
        ap_ready => Relu_tiled_oc_U0_ap_ready,
        fc11_dout => fc1_dout,
        fc11_num_data_valid => fc1_num_data_valid,
        fc11_fifo_cap => fc1_fifo_cap,
        fc11_empty_n => fc1_empty_n,
        fc11_read => Relu_tiled_oc_U0_fc11_read,
        relu2_din => Relu_tiled_oc_U0_relu2_din,
        relu2_num_data_valid => relu_num_data_valid,
        relu2_fifo_cap => relu_fifo_cap,
        relu2_full_n => relu_full_n,
        relu2_write => Relu_tiled_oc_U0_relu2_write);

    FC2_tiled_oc_2_U0 : component ViT_Block_FC2_tiled_oc_2
    port map (
        m_axi_gmem1_AWVALID => FC2_tiled_oc_2_U0_m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY => ap_const_logic_0,
        m_axi_gmem1_AWADDR => FC2_tiled_oc_2_U0_m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID => FC2_tiled_oc_2_U0_m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN => FC2_tiled_oc_2_U0_m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE => FC2_tiled_oc_2_U0_m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST => FC2_tiled_oc_2_U0_m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK => FC2_tiled_oc_2_U0_m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE => FC2_tiled_oc_2_U0_m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT => FC2_tiled_oc_2_U0_m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS => FC2_tiled_oc_2_U0_m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION => FC2_tiled_oc_2_U0_m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER => FC2_tiled_oc_2_U0_m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID => FC2_tiled_oc_2_U0_m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY => ap_const_logic_0,
        m_axi_gmem1_WDATA => FC2_tiled_oc_2_U0_m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB => FC2_tiled_oc_2_U0_m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST => FC2_tiled_oc_2_U0_m_axi_gmem1_WLAST,
        m_axi_gmem1_WID => FC2_tiled_oc_2_U0_m_axi_gmem1_WID,
        m_axi_gmem1_WUSER => FC2_tiled_oc_2_U0_m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID => FC2_tiled_oc_2_U0_m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY => m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR => FC2_tiled_oc_2_U0_m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID => FC2_tiled_oc_2_U0_m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN => FC2_tiled_oc_2_U0_m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE => FC2_tiled_oc_2_U0_m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST => FC2_tiled_oc_2_U0_m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK => FC2_tiled_oc_2_U0_m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE => FC2_tiled_oc_2_U0_m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT => FC2_tiled_oc_2_U0_m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS => FC2_tiled_oc_2_U0_m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION => FC2_tiled_oc_2_U0_m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER => FC2_tiled_oc_2_U0_m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID => m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY => FC2_tiled_oc_2_U0_m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA => m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST => m_axi_gmem1_RLAST,
        m_axi_gmem1_RID => m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM => m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER => m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP => m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID => ap_const_logic_0,
        m_axi_gmem1_BREADY => FC2_tiled_oc_2_U0_m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP => ap_const_lv2_0,
        m_axi_gmem1_BID => ap_const_lv1_0,
        m_axi_gmem1_BUSER => ap_const_lv1_0,
        in_w => in_w_down,
        relu2_dout => relu_dout,
        relu2_empty_n => relu_empty_n,
        relu2_read => FC2_tiled_oc_2_U0_relu2_read,
        mlp_out14_din => FC2_tiled_oc_2_U0_mlp_out14_din,
        mlp_out14_full_n => mlp_out14_full_n,
        mlp_out14_write => FC2_tiled_oc_2_U0_mlp_out14_write,
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        in_w_ap_vld => in_w_down_ap_vld,
        ap_start => FC2_tiled_oc_2_U0_ap_start,
        ap_done => FC2_tiled_oc_2_U0_ap_done,
        ap_ready => FC2_tiled_oc_2_U0_ap_ready,
        ap_idle => FC2_tiled_oc_2_U0_ap_idle,
        ap_continue => FC2_tiled_oc_2_U0_ap_continue);

    fc1_U : component ViT_Block_fifo_w8_d64_S_x9
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => FC1_tiled_oc_2_U0_fc11_din,
        if_full_n => fc1_full_n,
        if_write => FC1_tiled_oc_2_U0_fc11_write,
        if_dout => fc1_dout,
        if_num_data_valid => fc1_num_data_valid,
        if_fifo_cap => fc1_fifo_cap,
        if_empty_n => fc1_empty_n,
        if_read => Relu_tiled_oc_U0_fc11_read);

    relu_U : component ViT_Block_fifo_w8_d64_S_x9
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Relu_tiled_oc_U0_relu2_din,
        if_full_n => relu_full_n,
        if_write => Relu_tiled_oc_U0_relu2_write,
        if_dout => relu_dout,
        if_num_data_valid => relu_num_data_valid,
        if_fifo_cap => relu_fifo_cap,
        if_empty_n => relu_empty_n,
        if_read => FC2_tiled_oc_2_U0_relu2_read);

    start_for_Relu_tiled_oc_U0_U : component ViT_Block_start_for_Relu_tiled_oc_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_Relu_tiled_oc_U0_din,
        if_full_n => start_for_Relu_tiled_oc_U0_full_n,
        if_write => FC1_tiled_oc_2_U0_start_write,
        if_dout => start_for_Relu_tiled_oc_U0_dout,
        if_empty_n => start_for_Relu_tiled_oc_U0_empty_n,
        if_read => Relu_tiled_oc_U0_ap_ready);





    ap_sync_reg_FC1_tiled_oc_2_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_FC1_tiled_oc_2_U0_ap_ready <= ap_const_logic_0;
            else
                if (((real_start and ap_sync_ready) = ap_const_logic_1)) then 
                    ap_sync_reg_FC1_tiled_oc_2_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_FC1_tiled_oc_2_U0_ap_ready <= ap_sync_FC1_tiled_oc_2_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_FC2_tiled_oc_2_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_FC2_tiled_oc_2_U0_ap_ready <= ap_const_logic_0;
            else
                if (((real_start and ap_sync_ready) = ap_const_logic_1)) then 
                    ap_sync_reg_FC2_tiled_oc_2_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_FC2_tiled_oc_2_U0_ap_ready <= ap_sync_FC2_tiled_oc_2_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    FC1_tiled_oc_2_U0_ap_continue <= ap_const_logic_1;
    FC1_tiled_oc_2_U0_ap_start <= (real_start and (ap_sync_reg_FC1_tiled_oc_2_U0_ap_ready xor ap_const_logic_1));
    FC2_tiled_oc_2_U0_ap_continue <= ap_continue;
    FC2_tiled_oc_2_U0_ap_start <= (real_start and (ap_sync_reg_FC2_tiled_oc_2_U0_ap_ready xor ap_const_logic_1));
    Relu_tiled_oc_U0_ap_continue <= ap_const_logic_1;
    Relu_tiled_oc_U0_ap_start <= start_for_Relu_tiled_oc_U0_empty_n;
    ap_done <= FC2_tiled_oc_2_U0_ap_done;
    ap_idle <= (Relu_tiled_oc_U0_ap_idle and FC2_tiled_oc_2_U0_ap_idle and FC1_tiled_oc_2_U0_ap_idle);
    ap_ready <= ap_sync_ready;
    ap_sync_FC1_tiled_oc_2_U0_ap_ready <= (ap_sync_reg_FC1_tiled_oc_2_U0_ap_ready or FC1_tiled_oc_2_U0_ap_ready);
    ap_sync_FC2_tiled_oc_2_U0_ap_ready <= (ap_sync_reg_FC2_tiled_oc_2_U0_ap_ready or FC2_tiled_oc_2_U0_ap_ready);
    ap_sync_ready <= (ap_sync_FC2_tiled_oc_2_U0_ap_ready and ap_sync_FC1_tiled_oc_2_U0_ap_ready);
    internal_ap_ready <= ap_sync_ready;
    m_axi_gmem0_ARADDR <= FC1_tiled_oc_2_U0_m_axi_gmem0_ARADDR;
    m_axi_gmem0_ARBURST <= FC1_tiled_oc_2_U0_m_axi_gmem0_ARBURST;
    m_axi_gmem0_ARCACHE <= FC1_tiled_oc_2_U0_m_axi_gmem0_ARCACHE;
    m_axi_gmem0_ARID <= FC1_tiled_oc_2_U0_m_axi_gmem0_ARID;
    m_axi_gmem0_ARLEN <= FC1_tiled_oc_2_U0_m_axi_gmem0_ARLEN;
    m_axi_gmem0_ARLOCK <= FC1_tiled_oc_2_U0_m_axi_gmem0_ARLOCK;
    m_axi_gmem0_ARPROT <= FC1_tiled_oc_2_U0_m_axi_gmem0_ARPROT;
    m_axi_gmem0_ARQOS <= FC1_tiled_oc_2_U0_m_axi_gmem0_ARQOS;
    m_axi_gmem0_ARREGION <= FC1_tiled_oc_2_U0_m_axi_gmem0_ARREGION;
    m_axi_gmem0_ARSIZE <= FC1_tiled_oc_2_U0_m_axi_gmem0_ARSIZE;
    m_axi_gmem0_ARUSER <= FC1_tiled_oc_2_U0_m_axi_gmem0_ARUSER;
    m_axi_gmem0_ARVALID <= FC1_tiled_oc_2_U0_m_axi_gmem0_ARVALID;
    m_axi_gmem0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem0_AWID <= ap_const_lv1_0;
    m_axi_gmem0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem0_AWVALID <= ap_const_logic_0;
    m_axi_gmem0_BREADY <= ap_const_logic_0;
    m_axi_gmem0_RREADY <= FC1_tiled_oc_2_U0_m_axi_gmem0_RREADY;
    m_axi_gmem0_WDATA <= ap_const_lv8_0;
    m_axi_gmem0_WID <= ap_const_lv1_0;
    m_axi_gmem0_WLAST <= ap_const_logic_0;
    m_axi_gmem0_WSTRB <= ap_const_lv1_0;
    m_axi_gmem0_WUSER <= ap_const_lv1_0;
    m_axi_gmem0_WVALID <= ap_const_logic_0;
    m_axi_gmem1_ARADDR <= FC2_tiled_oc_2_U0_m_axi_gmem1_ARADDR;
    m_axi_gmem1_ARBURST <= FC2_tiled_oc_2_U0_m_axi_gmem1_ARBURST;
    m_axi_gmem1_ARCACHE <= FC2_tiled_oc_2_U0_m_axi_gmem1_ARCACHE;
    m_axi_gmem1_ARID <= FC2_tiled_oc_2_U0_m_axi_gmem1_ARID;
    m_axi_gmem1_ARLEN <= FC2_tiled_oc_2_U0_m_axi_gmem1_ARLEN;
    m_axi_gmem1_ARLOCK <= FC2_tiled_oc_2_U0_m_axi_gmem1_ARLOCK;
    m_axi_gmem1_ARPROT <= FC2_tiled_oc_2_U0_m_axi_gmem1_ARPROT;
    m_axi_gmem1_ARQOS <= FC2_tiled_oc_2_U0_m_axi_gmem1_ARQOS;
    m_axi_gmem1_ARREGION <= FC2_tiled_oc_2_U0_m_axi_gmem1_ARREGION;
    m_axi_gmem1_ARSIZE <= FC2_tiled_oc_2_U0_m_axi_gmem1_ARSIZE;
    m_axi_gmem1_ARUSER <= FC2_tiled_oc_2_U0_m_axi_gmem1_ARUSER;
    m_axi_gmem1_ARVALID <= FC2_tiled_oc_2_U0_m_axi_gmem1_ARVALID;
    m_axi_gmem1_AWADDR <= ap_const_lv64_0;
    m_axi_gmem1_AWBURST <= ap_const_lv2_0;
    m_axi_gmem1_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem1_AWID <= ap_const_lv1_0;
    m_axi_gmem1_AWLEN <= ap_const_lv32_0;
    m_axi_gmem1_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem1_AWPROT <= ap_const_lv3_0;
    m_axi_gmem1_AWQOS <= ap_const_lv4_0;
    m_axi_gmem1_AWREGION <= ap_const_lv4_0;
    m_axi_gmem1_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem1_AWUSER <= ap_const_lv1_0;
    m_axi_gmem1_AWVALID <= ap_const_logic_0;
    m_axi_gmem1_BREADY <= ap_const_logic_0;
    m_axi_gmem1_RREADY <= FC2_tiled_oc_2_U0_m_axi_gmem1_RREADY;
    m_axi_gmem1_WDATA <= ap_const_lv8_0;
    m_axi_gmem1_WID <= ap_const_lv1_0;
    m_axi_gmem1_WLAST <= ap_const_logic_0;
    m_axi_gmem1_WSTRB <= ap_const_lv1_0;
    m_axi_gmem1_WUSER <= ap_const_lv1_0;
    m_axi_gmem1_WVALID <= ap_const_logic_0;
    mlp_out14_din <= FC2_tiled_oc_2_U0_mlp_out14_din;
    mlp_out14_write <= FC2_tiled_oc_2_U0_mlp_out14_write;
    norm_out_113_read <= FC1_tiled_oc_2_U0_norm_out_113_read;

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_for_Relu_tiled_oc_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
