// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ViT_Block_MM1_tiled (
        ap_start,
        start_full_n,
        start_out,
        start_write,
        A_sx_0_dout,
        A_sx_0_empty_n,
        A_sx_0_read,
        V_1_0_dout,
        V_1_0_empty_n,
        V_1_0_read,
        head_out_0_din,
        head_out_0_full_n,
        head_out_0_write,
        ap_clk,
        ap_rst,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input   ap_start;
input   start_full_n;
output   start_out;
output   start_write;
input  [7:0] A_sx_0_dout;
input   A_sx_0_empty_n;
output   A_sx_0_read;
input  [7:0] V_1_0_dout;
input   V_1_0_empty_n;
output   V_1_0_read;
output  [7:0] head_out_0_din;
input   head_out_0_full_n;
output   head_out_0_write;
input   ap_clk;
input   ap_rst;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

reg start_write;

reg    real_start;
reg    start_once_reg;
wire    internal_ap_ready;
wire    MatMul_KV_tiled_17_17_8_1_1_1_1_1_339_16_0_ap_int_8_ap_int_32_U0_ap_start;
wire    MatMul_KV_tiled_17_17_8_1_1_1_1_1_339_16_0_ap_int_8_ap_int_32_U0_ap_done;
wire    MatMul_KV_tiled_17_17_8_1_1_1_1_1_339_16_0_ap_int_8_ap_int_32_U0_ap_continue;
wire    MatMul_KV_tiled_17_17_8_1_1_1_1_1_339_16_0_ap_int_8_ap_int_32_U0_ap_idle;
wire    MatMul_KV_tiled_17_17_8_1_1_1_1_1_339_16_0_ap_int_8_ap_int_32_U0_ap_ready;
wire    MatMul_KV_tiled_17_17_8_1_1_1_1_1_339_16_0_ap_int_8_ap_int_32_U0_A_sx_0_read;
wire    MatMul_KV_tiled_17_17_8_1_1_1_1_1_339_16_0_ap_int_8_ap_int_32_U0_V_1_0_read;
wire   [7:0] MatMul_KV_tiled_17_17_8_1_1_1_1_1_339_16_0_ap_int_8_ap_int_32_U0_head_out_0_din;
wire    MatMul_KV_tiled_17_17_8_1_1_1_1_1_339_16_0_ap_int_8_ap_int_32_U0_head_out_0_write;
wire    ap_sync_ready;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
end

ViT_Block_MatMul_KV_tiled_17_17_8_1_1_1_1_1_339_16_0_ap_int_8_ap_int_32_s MatMul_KV_tiled_17_17_8_1_1_1_1_1_339_16_0_ap_int_8_ap_int_32_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(MatMul_KV_tiled_17_17_8_1_1_1_1_1_339_16_0_ap_int_8_ap_int_32_U0_ap_start),
    .ap_done(MatMul_KV_tiled_17_17_8_1_1_1_1_1_339_16_0_ap_int_8_ap_int_32_U0_ap_done),
    .ap_continue(MatMul_KV_tiled_17_17_8_1_1_1_1_1_339_16_0_ap_int_8_ap_int_32_U0_ap_continue),
    .ap_idle(MatMul_KV_tiled_17_17_8_1_1_1_1_1_339_16_0_ap_int_8_ap_int_32_U0_ap_idle),
    .ap_ready(MatMul_KV_tiled_17_17_8_1_1_1_1_1_339_16_0_ap_int_8_ap_int_32_U0_ap_ready),
    .A_sx_0_dout(A_sx_0_dout),
    .A_sx_0_num_data_valid(2'd0),
    .A_sx_0_fifo_cap(2'd0),
    .A_sx_0_empty_n(A_sx_0_empty_n),
    .A_sx_0_read(MatMul_KV_tiled_17_17_8_1_1_1_1_1_339_16_0_ap_int_8_ap_int_32_U0_A_sx_0_read),
    .V_1_0_dout(V_1_0_dout),
    .V_1_0_num_data_valid(2'd0),
    .V_1_0_fifo_cap(2'd0),
    .V_1_0_empty_n(V_1_0_empty_n),
    .V_1_0_read(MatMul_KV_tiled_17_17_8_1_1_1_1_1_339_16_0_ap_int_8_ap_int_32_U0_V_1_0_read),
    .head_out_0_din(MatMul_KV_tiled_17_17_8_1_1_1_1_1_339_16_0_ap_int_8_ap_int_32_U0_head_out_0_din),
    .head_out_0_num_data_valid(2'd0),
    .head_out_0_fifo_cap(2'd0),
    .head_out_0_full_n(head_out_0_full_n),
    .head_out_0_write(MatMul_KV_tiled_17_17_8_1_1_1_1_1_339_16_0_ap_int_8_ap_int_32_U0_head_out_0_write)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

assign A_sx_0_read = MatMul_KV_tiled_17_17_8_1_1_1_1_1_339_16_0_ap_int_8_ap_int_32_U0_A_sx_0_read;

assign MatMul_KV_tiled_17_17_8_1_1_1_1_1_339_16_0_ap_int_8_ap_int_32_U0_ap_continue = ap_continue;

assign MatMul_KV_tiled_17_17_8_1_1_1_1_1_339_16_0_ap_int_8_ap_int_32_U0_ap_start = real_start;

assign V_1_0_read = MatMul_KV_tiled_17_17_8_1_1_1_1_1_339_16_0_ap_int_8_ap_int_32_U0_V_1_0_read;

assign ap_done = MatMul_KV_tiled_17_17_8_1_1_1_1_1_339_16_0_ap_int_8_ap_int_32_U0_ap_done;

assign ap_idle = MatMul_KV_tiled_17_17_8_1_1_1_1_1_339_16_0_ap_int_8_ap_int_32_U0_ap_idle;

assign ap_ready = MatMul_KV_tiled_17_17_8_1_1_1_1_1_339_16_0_ap_int_8_ap_int_32_U0_ap_ready;

assign ap_sync_ready = MatMul_KV_tiled_17_17_8_1_1_1_1_1_339_16_0_ap_int_8_ap_int_32_U0_ap_ready;

assign head_out_0_din = MatMul_KV_tiled_17_17_8_1_1_1_1_1_339_16_0_ap_int_8_ap_int_32_U0_head_out_0_din;

assign head_out_0_write = MatMul_KV_tiled_17_17_8_1_1_1_1_1_339_16_0_ap_int_8_ap_int_32_U0_head_out_0_write;

assign internal_ap_ready = ap_sync_ready;

assign start_out = real_start;

endmodule //ViT_Block_MM1_tiled
