// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ViT_Block_Linear_Layer_Pipeline_VITIS_LOOP_1588_17_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        v_lin3_din,
        v_lin3_num_data_valid,
        v_lin3_fifo_cap,
        v_lin3_full_n,
        v_lin3_write,
        C_tile_V_address0,
        C_tile_V_ce0,
        C_tile_V_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] v_lin3_din;
input  [1:0] v_lin3_num_data_valid;
input  [1:0] v_lin3_fifo_cap;
input   v_lin3_full_n;
output   v_lin3_write;
output  [3:0] C_tile_V_address0;
output   C_tile_V_ce0;
input  [31:0] C_tile_V_q0;

reg ap_idle;
reg v_lin3_write;
reg C_tile_V_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln1588_fu_108_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    v_lin3_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] tmp_reg_268;
wire   [39:0] trunc_ln1417_fu_148_p1;
reg   [39:0] trunc_ln1417_reg_273;
wire   [63:0] n_10_cast_fu_120_p1;
reg   [4:0] n_fu_76;
wire   [4:0] add_ln1588_fu_114_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_n_5;
reg    ap_block_pp0_stage0_01001;
wire   [9:0] prod_fu_134_p1;
wire   [41:0] prod_fu_134_p2;
wire   [39:0] ret_V_fu_152_p2;
wire   [23:0] trunc_ln_fu_157_p4;
wire   [39:0] ret_V_13_fu_171_p2;
wire   [23:0] trunc_ln9_fu_176_p4;
wire   [24:0] zext_ln1420_fu_186_p1;
wire   [24:0] rq_V_fu_190_p2;
wire   [24:0] zext_ln1409_fu_167_p1;
wire   [24:0] rq_V_12_fu_196_p3;
wire   [17:0] tmp_13_fu_203_p4;
wire   [0:0] icmp_ln1035_fu_213_p2;
wire   [0:0] icmp_ln1027_fu_219_p2;
wire   [0:0] or_ln1444_fu_237_p2;
wire   [7:0] select_ln1444_fu_229_p3;
wire   [7:0] trunc_ln1444_fu_225_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

ViT_Block_mul_32s_10ns_42_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 42 ))
mul_32s_10ns_42_1_1_U133(
    .din0(C_tile_V_q0),
    .din1(prod_fu_134_p1),
    .dout(prod_fu_134_p2)
);

ViT_Block_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln1588_fu_108_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            n_fu_76 <= add_ln1588_fu_114_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            n_fu_76 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        tmp_reg_268 <= prod_fu_134_p2[32'd41];
        trunc_ln1417_reg_273 <= trunc_ln1417_fu_148_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        C_tile_V_ce0 = 1'b1;
    end else begin
        C_tile_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1588_fu_108_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_n_5 = 5'd0;
    end else begin
        ap_sig_allocacmp_n_5 = n_fu_76;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v_lin3_blk_n = v_lin3_full_n;
    end else begin
        v_lin3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v_lin3_write = 1'b1;
    end else begin
        v_lin3_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C_tile_V_address0 = n_10_cast_fu_120_p1;

assign add_ln1588_fu_114_p2 = (ap_sig_allocacmp_n_5 + 5'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((v_lin3_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((v_lin3_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((v_lin3_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (v_lin3_full_n == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln1027_fu_219_p2 = (($signed(rq_V_12_fu_196_p3) < $signed(25'd33554304)) ? 1'b1 : 1'b0);

assign icmp_ln1035_fu_213_p2 = (($signed(tmp_13_fu_203_p4) > $signed(18'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1588_fu_108_p2 = ((ap_sig_allocacmp_n_5 == 5'd16) ? 1'b1 : 1'b0);

assign n_10_cast_fu_120_p1 = ap_sig_allocacmp_n_5;

assign or_ln1444_fu_237_p2 = (icmp_ln1035_fu_213_p2 | icmp_ln1027_fu_219_p2);

assign prod_fu_134_p1 = 42'd409;

assign ret_V_13_fu_171_p2 = (40'd32768 - trunc_ln1417_reg_273);

assign ret_V_fu_152_p2 = (trunc_ln1417_reg_273 + 40'd32768);

assign rq_V_12_fu_196_p3 = ((tmp_reg_268[0:0] == 1'b1) ? rq_V_fu_190_p2 : zext_ln1409_fu_167_p1);

assign rq_V_fu_190_p2 = (25'd0 - zext_ln1420_fu_186_p1);

assign select_ln1444_fu_229_p3 = ((icmp_ln1035_fu_213_p2[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign tmp_13_fu_203_p4 = {{rq_V_12_fu_196_p3[24:7]}};

assign trunc_ln1417_fu_148_p1 = prod_fu_134_p2[39:0];

assign trunc_ln1444_fu_225_p1 = rq_V_12_fu_196_p3[7:0];

assign trunc_ln9_fu_176_p4 = {{ret_V_13_fu_171_p2[39:16]}};

assign trunc_ln_fu_157_p4 = {{ret_V_fu_152_p2[39:16]}};

assign v_lin3_din = ((or_ln1444_fu_237_p2[0:0] == 1'b1) ? select_ln1444_fu_229_p3 : trunc_ln1444_fu_225_p1);

assign zext_ln1409_fu_167_p1 = trunc_ln_fu_157_p4;

assign zext_ln1420_fu_186_p1 = trunc_ln9_fu_176_p4;

endmodule //ViT_Block_Linear_Layer_Pipeline_VITIS_LOOP_1588_17_3
