// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="ViT_Block_ViT_Block,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu250-figd2104-2L-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=148,HLS_SYN_DSP=0,HLS_SYN_FF=119534,HLS_SYN_LUT=127146,HLS_VERSION=2022_2}" *)

module ViT_Block (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        m_axi_K_AWVALID,
        m_axi_K_AWREADY,
        m_axi_K_AWADDR,
        m_axi_K_AWID,
        m_axi_K_AWLEN,
        m_axi_K_AWSIZE,
        m_axi_K_AWBURST,
        m_axi_K_AWLOCK,
        m_axi_K_AWCACHE,
        m_axi_K_AWPROT,
        m_axi_K_AWQOS,
        m_axi_K_AWREGION,
        m_axi_K_AWUSER,
        m_axi_K_WVALID,
        m_axi_K_WREADY,
        m_axi_K_WDATA,
        m_axi_K_WSTRB,
        m_axi_K_WLAST,
        m_axi_K_WID,
        m_axi_K_WUSER,
        m_axi_K_ARVALID,
        m_axi_K_ARREADY,
        m_axi_K_ARADDR,
        m_axi_K_ARID,
        m_axi_K_ARLEN,
        m_axi_K_ARSIZE,
        m_axi_K_ARBURST,
        m_axi_K_ARLOCK,
        m_axi_K_ARCACHE,
        m_axi_K_ARPROT,
        m_axi_K_ARQOS,
        m_axi_K_ARREGION,
        m_axi_K_ARUSER,
        m_axi_K_RVALID,
        m_axi_K_RREADY,
        m_axi_K_RDATA,
        m_axi_K_RLAST,
        m_axi_K_RID,
        m_axi_K_RUSER,
        m_axi_K_RRESP,
        m_axi_K_BVALID,
        m_axi_K_BREADY,
        m_axi_K_BRESP,
        m_axi_K_BID,
        m_axi_K_BUSER,
        m_axi_OUT_M_AWVALID,
        m_axi_OUT_M_AWREADY,
        m_axi_OUT_M_AWADDR,
        m_axi_OUT_M_AWID,
        m_axi_OUT_M_AWLEN,
        m_axi_OUT_M_AWSIZE,
        m_axi_OUT_M_AWBURST,
        m_axi_OUT_M_AWLOCK,
        m_axi_OUT_M_AWCACHE,
        m_axi_OUT_M_AWPROT,
        m_axi_OUT_M_AWQOS,
        m_axi_OUT_M_AWREGION,
        m_axi_OUT_M_AWUSER,
        m_axi_OUT_M_WVALID,
        m_axi_OUT_M_WREADY,
        m_axi_OUT_M_WDATA,
        m_axi_OUT_M_WSTRB,
        m_axi_OUT_M_WLAST,
        m_axi_OUT_M_WID,
        m_axi_OUT_M_WUSER,
        m_axi_OUT_M_ARVALID,
        m_axi_OUT_M_ARREADY,
        m_axi_OUT_M_ARADDR,
        m_axi_OUT_M_ARID,
        m_axi_OUT_M_ARLEN,
        m_axi_OUT_M_ARSIZE,
        m_axi_OUT_M_ARBURST,
        m_axi_OUT_M_ARLOCK,
        m_axi_OUT_M_ARCACHE,
        m_axi_OUT_M_ARPROT,
        m_axi_OUT_M_ARQOS,
        m_axi_OUT_M_ARREGION,
        m_axi_OUT_M_ARUSER,
        m_axi_OUT_M_RVALID,
        m_axi_OUT_M_RREADY,
        m_axi_OUT_M_RDATA,
        m_axi_OUT_M_RLAST,
        m_axi_OUT_M_RID,
        m_axi_OUT_M_RUSER,
        m_axi_OUT_M_RRESP,
        m_axi_OUT_M_BVALID,
        m_axi_OUT_M_BREADY,
        m_axi_OUT_M_BRESP,
        m_axi_OUT_M_BID,
        m_axi_OUT_M_BUSER,
        m_axi_Q_AWVALID,
        m_axi_Q_AWREADY,
        m_axi_Q_AWADDR,
        m_axi_Q_AWID,
        m_axi_Q_AWLEN,
        m_axi_Q_AWSIZE,
        m_axi_Q_AWBURST,
        m_axi_Q_AWLOCK,
        m_axi_Q_AWCACHE,
        m_axi_Q_AWPROT,
        m_axi_Q_AWQOS,
        m_axi_Q_AWREGION,
        m_axi_Q_AWUSER,
        m_axi_Q_WVALID,
        m_axi_Q_WREADY,
        m_axi_Q_WDATA,
        m_axi_Q_WSTRB,
        m_axi_Q_WLAST,
        m_axi_Q_WID,
        m_axi_Q_WUSER,
        m_axi_Q_ARVALID,
        m_axi_Q_ARREADY,
        m_axi_Q_ARADDR,
        m_axi_Q_ARID,
        m_axi_Q_ARLEN,
        m_axi_Q_ARSIZE,
        m_axi_Q_ARBURST,
        m_axi_Q_ARLOCK,
        m_axi_Q_ARCACHE,
        m_axi_Q_ARPROT,
        m_axi_Q_ARQOS,
        m_axi_Q_ARREGION,
        m_axi_Q_ARUSER,
        m_axi_Q_RVALID,
        m_axi_Q_RREADY,
        m_axi_Q_RDATA,
        m_axi_Q_RLAST,
        m_axi_Q_RID,
        m_axi_Q_RUSER,
        m_axi_Q_RRESP,
        m_axi_Q_BVALID,
        m_axi_Q_BREADY,
        m_axi_Q_BRESP,
        m_axi_Q_BID,
        m_axi_Q_BUSER,
        m_axi_V_AWVALID,
        m_axi_V_AWREADY,
        m_axi_V_AWADDR,
        m_axi_V_AWID,
        m_axi_V_AWLEN,
        m_axi_V_AWSIZE,
        m_axi_V_AWBURST,
        m_axi_V_AWLOCK,
        m_axi_V_AWCACHE,
        m_axi_V_AWPROT,
        m_axi_V_AWQOS,
        m_axi_V_AWREGION,
        m_axi_V_AWUSER,
        m_axi_V_WVALID,
        m_axi_V_WREADY,
        m_axi_V_WDATA,
        m_axi_V_WSTRB,
        m_axi_V_WLAST,
        m_axi_V_WID,
        m_axi_V_WUSER,
        m_axi_V_ARVALID,
        m_axi_V_ARREADY,
        m_axi_V_ARADDR,
        m_axi_V_ARID,
        m_axi_V_ARLEN,
        m_axi_V_ARSIZE,
        m_axi_V_ARBURST,
        m_axi_V_ARLOCK,
        m_axi_V_ARCACHE,
        m_axi_V_ARPROT,
        m_axi_V_ARQOS,
        m_axi_V_ARREGION,
        m_axi_V_ARUSER,
        m_axi_V_RVALID,
        m_axi_V_RREADY,
        m_axi_V_RDATA,
        m_axi_V_RLAST,
        m_axi_V_RID,
        m_axi_V_RUSER,
        m_axi_V_RRESP,
        m_axi_V_BVALID,
        m_axi_V_BREADY,
        m_axi_V_BRESP,
        m_axi_V_BID,
        m_axi_V_BUSER,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        in_r_TDATA,
        in_r_TKEEP,
        in_r_TSTRB,
        in_r_TLAST,
        out_r_TDATA,
        out_r_TKEEP,
        out_r_TSTRB,
        out_r_TLAST,
        in_r_TVALID,
        in_r_TREADY,
        out_r_TVALID,
        out_r_TREADY
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_K_ID_WIDTH = 1;
parameter    C_M_AXI_K_ADDR_WIDTH = 64;
parameter    C_M_AXI_K_DATA_WIDTH = 32;
parameter    C_M_AXI_K_AWUSER_WIDTH = 1;
parameter    C_M_AXI_K_ARUSER_WIDTH = 1;
parameter    C_M_AXI_K_WUSER_WIDTH = 1;
parameter    C_M_AXI_K_RUSER_WIDTH = 1;
parameter    C_M_AXI_K_BUSER_WIDTH = 1;
parameter    C_M_AXI_K_USER_VALUE = 0;
parameter    C_M_AXI_K_PROT_VALUE = 0;
parameter    C_M_AXI_K_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_OUT_M_ID_WIDTH = 1;
parameter    C_M_AXI_OUT_M_ADDR_WIDTH = 64;
parameter    C_M_AXI_OUT_M_DATA_WIDTH = 32;
parameter    C_M_AXI_OUT_M_AWUSER_WIDTH = 1;
parameter    C_M_AXI_OUT_M_ARUSER_WIDTH = 1;
parameter    C_M_AXI_OUT_M_WUSER_WIDTH = 1;
parameter    C_M_AXI_OUT_M_RUSER_WIDTH = 1;
parameter    C_M_AXI_OUT_M_BUSER_WIDTH = 1;
parameter    C_M_AXI_OUT_M_USER_VALUE = 0;
parameter    C_M_AXI_OUT_M_PROT_VALUE = 0;
parameter    C_M_AXI_OUT_M_CACHE_VALUE = 3;
parameter    C_M_AXI_Q_ID_WIDTH = 1;
parameter    C_M_AXI_Q_ADDR_WIDTH = 64;
parameter    C_M_AXI_Q_DATA_WIDTH = 32;
parameter    C_M_AXI_Q_AWUSER_WIDTH = 1;
parameter    C_M_AXI_Q_ARUSER_WIDTH = 1;
parameter    C_M_AXI_Q_WUSER_WIDTH = 1;
parameter    C_M_AXI_Q_RUSER_WIDTH = 1;
parameter    C_M_AXI_Q_BUSER_WIDTH = 1;
parameter    C_M_AXI_Q_USER_VALUE = 0;
parameter    C_M_AXI_Q_PROT_VALUE = 0;
parameter    C_M_AXI_Q_CACHE_VALUE = 3;
parameter    C_M_AXI_V_ID_WIDTH = 1;
parameter    C_M_AXI_V_ADDR_WIDTH = 64;
parameter    C_M_AXI_V_DATA_WIDTH = 32;
parameter    C_M_AXI_V_AWUSER_WIDTH = 1;
parameter    C_M_AXI_V_ARUSER_WIDTH = 1;
parameter    C_M_AXI_V_WUSER_WIDTH = 1;
parameter    C_M_AXI_V_RUSER_WIDTH = 1;
parameter    C_M_AXI_V_BUSER_WIDTH = 1;
parameter    C_M_AXI_V_USER_VALUE = 0;
parameter    C_M_AXI_V_PROT_VALUE = 0;
parameter    C_M_AXI_V_CACHE_VALUE = 3;
parameter    C_M_AXI_GMEM0_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM0_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_USER_VALUE = 0;
parameter    C_M_AXI_GMEM0_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM0_CACHE_VALUE = 3;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_K_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_OUT_M_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_Q_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_V_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM0_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
output   m_axi_K_AWVALID;
input   m_axi_K_AWREADY;
output  [C_M_AXI_K_ADDR_WIDTH - 1:0] m_axi_K_AWADDR;
output  [C_M_AXI_K_ID_WIDTH - 1:0] m_axi_K_AWID;
output  [7:0] m_axi_K_AWLEN;
output  [2:0] m_axi_K_AWSIZE;
output  [1:0] m_axi_K_AWBURST;
output  [1:0] m_axi_K_AWLOCK;
output  [3:0] m_axi_K_AWCACHE;
output  [2:0] m_axi_K_AWPROT;
output  [3:0] m_axi_K_AWQOS;
output  [3:0] m_axi_K_AWREGION;
output  [C_M_AXI_K_AWUSER_WIDTH - 1:0] m_axi_K_AWUSER;
output   m_axi_K_WVALID;
input   m_axi_K_WREADY;
output  [C_M_AXI_K_DATA_WIDTH - 1:0] m_axi_K_WDATA;
output  [C_M_AXI_K_WSTRB_WIDTH - 1:0] m_axi_K_WSTRB;
output   m_axi_K_WLAST;
output  [C_M_AXI_K_ID_WIDTH - 1:0] m_axi_K_WID;
output  [C_M_AXI_K_WUSER_WIDTH - 1:0] m_axi_K_WUSER;
output   m_axi_K_ARVALID;
input   m_axi_K_ARREADY;
output  [C_M_AXI_K_ADDR_WIDTH - 1:0] m_axi_K_ARADDR;
output  [C_M_AXI_K_ID_WIDTH - 1:0] m_axi_K_ARID;
output  [7:0] m_axi_K_ARLEN;
output  [2:0] m_axi_K_ARSIZE;
output  [1:0] m_axi_K_ARBURST;
output  [1:0] m_axi_K_ARLOCK;
output  [3:0] m_axi_K_ARCACHE;
output  [2:0] m_axi_K_ARPROT;
output  [3:0] m_axi_K_ARQOS;
output  [3:0] m_axi_K_ARREGION;
output  [C_M_AXI_K_ARUSER_WIDTH - 1:0] m_axi_K_ARUSER;
input   m_axi_K_RVALID;
output   m_axi_K_RREADY;
input  [C_M_AXI_K_DATA_WIDTH - 1:0] m_axi_K_RDATA;
input   m_axi_K_RLAST;
input  [C_M_AXI_K_ID_WIDTH - 1:0] m_axi_K_RID;
input  [C_M_AXI_K_RUSER_WIDTH - 1:0] m_axi_K_RUSER;
input  [1:0] m_axi_K_RRESP;
input   m_axi_K_BVALID;
output   m_axi_K_BREADY;
input  [1:0] m_axi_K_BRESP;
input  [C_M_AXI_K_ID_WIDTH - 1:0] m_axi_K_BID;
input  [C_M_AXI_K_BUSER_WIDTH - 1:0] m_axi_K_BUSER;
output   m_axi_OUT_M_AWVALID;
input   m_axi_OUT_M_AWREADY;
output  [C_M_AXI_OUT_M_ADDR_WIDTH - 1:0] m_axi_OUT_M_AWADDR;
output  [C_M_AXI_OUT_M_ID_WIDTH - 1:0] m_axi_OUT_M_AWID;
output  [7:0] m_axi_OUT_M_AWLEN;
output  [2:0] m_axi_OUT_M_AWSIZE;
output  [1:0] m_axi_OUT_M_AWBURST;
output  [1:0] m_axi_OUT_M_AWLOCK;
output  [3:0] m_axi_OUT_M_AWCACHE;
output  [2:0] m_axi_OUT_M_AWPROT;
output  [3:0] m_axi_OUT_M_AWQOS;
output  [3:0] m_axi_OUT_M_AWREGION;
output  [C_M_AXI_OUT_M_AWUSER_WIDTH - 1:0] m_axi_OUT_M_AWUSER;
output   m_axi_OUT_M_WVALID;
input   m_axi_OUT_M_WREADY;
output  [C_M_AXI_OUT_M_DATA_WIDTH - 1:0] m_axi_OUT_M_WDATA;
output  [C_M_AXI_OUT_M_WSTRB_WIDTH - 1:0] m_axi_OUT_M_WSTRB;
output   m_axi_OUT_M_WLAST;
output  [C_M_AXI_OUT_M_ID_WIDTH - 1:0] m_axi_OUT_M_WID;
output  [C_M_AXI_OUT_M_WUSER_WIDTH - 1:0] m_axi_OUT_M_WUSER;
output   m_axi_OUT_M_ARVALID;
input   m_axi_OUT_M_ARREADY;
output  [C_M_AXI_OUT_M_ADDR_WIDTH - 1:0] m_axi_OUT_M_ARADDR;
output  [C_M_AXI_OUT_M_ID_WIDTH - 1:0] m_axi_OUT_M_ARID;
output  [7:0] m_axi_OUT_M_ARLEN;
output  [2:0] m_axi_OUT_M_ARSIZE;
output  [1:0] m_axi_OUT_M_ARBURST;
output  [1:0] m_axi_OUT_M_ARLOCK;
output  [3:0] m_axi_OUT_M_ARCACHE;
output  [2:0] m_axi_OUT_M_ARPROT;
output  [3:0] m_axi_OUT_M_ARQOS;
output  [3:0] m_axi_OUT_M_ARREGION;
output  [C_M_AXI_OUT_M_ARUSER_WIDTH - 1:0] m_axi_OUT_M_ARUSER;
input   m_axi_OUT_M_RVALID;
output   m_axi_OUT_M_RREADY;
input  [C_M_AXI_OUT_M_DATA_WIDTH - 1:0] m_axi_OUT_M_RDATA;
input   m_axi_OUT_M_RLAST;
input  [C_M_AXI_OUT_M_ID_WIDTH - 1:0] m_axi_OUT_M_RID;
input  [C_M_AXI_OUT_M_RUSER_WIDTH - 1:0] m_axi_OUT_M_RUSER;
input  [1:0] m_axi_OUT_M_RRESP;
input   m_axi_OUT_M_BVALID;
output   m_axi_OUT_M_BREADY;
input  [1:0] m_axi_OUT_M_BRESP;
input  [C_M_AXI_OUT_M_ID_WIDTH - 1:0] m_axi_OUT_M_BID;
input  [C_M_AXI_OUT_M_BUSER_WIDTH - 1:0] m_axi_OUT_M_BUSER;
output   m_axi_Q_AWVALID;
input   m_axi_Q_AWREADY;
output  [C_M_AXI_Q_ADDR_WIDTH - 1:0] m_axi_Q_AWADDR;
output  [C_M_AXI_Q_ID_WIDTH - 1:0] m_axi_Q_AWID;
output  [7:0] m_axi_Q_AWLEN;
output  [2:0] m_axi_Q_AWSIZE;
output  [1:0] m_axi_Q_AWBURST;
output  [1:0] m_axi_Q_AWLOCK;
output  [3:0] m_axi_Q_AWCACHE;
output  [2:0] m_axi_Q_AWPROT;
output  [3:0] m_axi_Q_AWQOS;
output  [3:0] m_axi_Q_AWREGION;
output  [C_M_AXI_Q_AWUSER_WIDTH - 1:0] m_axi_Q_AWUSER;
output   m_axi_Q_WVALID;
input   m_axi_Q_WREADY;
output  [C_M_AXI_Q_DATA_WIDTH - 1:0] m_axi_Q_WDATA;
output  [C_M_AXI_Q_WSTRB_WIDTH - 1:0] m_axi_Q_WSTRB;
output   m_axi_Q_WLAST;
output  [C_M_AXI_Q_ID_WIDTH - 1:0] m_axi_Q_WID;
output  [C_M_AXI_Q_WUSER_WIDTH - 1:0] m_axi_Q_WUSER;
output   m_axi_Q_ARVALID;
input   m_axi_Q_ARREADY;
output  [C_M_AXI_Q_ADDR_WIDTH - 1:0] m_axi_Q_ARADDR;
output  [C_M_AXI_Q_ID_WIDTH - 1:0] m_axi_Q_ARID;
output  [7:0] m_axi_Q_ARLEN;
output  [2:0] m_axi_Q_ARSIZE;
output  [1:0] m_axi_Q_ARBURST;
output  [1:0] m_axi_Q_ARLOCK;
output  [3:0] m_axi_Q_ARCACHE;
output  [2:0] m_axi_Q_ARPROT;
output  [3:0] m_axi_Q_ARQOS;
output  [3:0] m_axi_Q_ARREGION;
output  [C_M_AXI_Q_ARUSER_WIDTH - 1:0] m_axi_Q_ARUSER;
input   m_axi_Q_RVALID;
output   m_axi_Q_RREADY;
input  [C_M_AXI_Q_DATA_WIDTH - 1:0] m_axi_Q_RDATA;
input   m_axi_Q_RLAST;
input  [C_M_AXI_Q_ID_WIDTH - 1:0] m_axi_Q_RID;
input  [C_M_AXI_Q_RUSER_WIDTH - 1:0] m_axi_Q_RUSER;
input  [1:0] m_axi_Q_RRESP;
input   m_axi_Q_BVALID;
output   m_axi_Q_BREADY;
input  [1:0] m_axi_Q_BRESP;
input  [C_M_AXI_Q_ID_WIDTH - 1:0] m_axi_Q_BID;
input  [C_M_AXI_Q_BUSER_WIDTH - 1:0] m_axi_Q_BUSER;
output   m_axi_V_AWVALID;
input   m_axi_V_AWREADY;
output  [C_M_AXI_V_ADDR_WIDTH - 1:0] m_axi_V_AWADDR;
output  [C_M_AXI_V_ID_WIDTH - 1:0] m_axi_V_AWID;
output  [7:0] m_axi_V_AWLEN;
output  [2:0] m_axi_V_AWSIZE;
output  [1:0] m_axi_V_AWBURST;
output  [1:0] m_axi_V_AWLOCK;
output  [3:0] m_axi_V_AWCACHE;
output  [2:0] m_axi_V_AWPROT;
output  [3:0] m_axi_V_AWQOS;
output  [3:0] m_axi_V_AWREGION;
output  [C_M_AXI_V_AWUSER_WIDTH - 1:0] m_axi_V_AWUSER;
output   m_axi_V_WVALID;
input   m_axi_V_WREADY;
output  [C_M_AXI_V_DATA_WIDTH - 1:0] m_axi_V_WDATA;
output  [C_M_AXI_V_WSTRB_WIDTH - 1:0] m_axi_V_WSTRB;
output   m_axi_V_WLAST;
output  [C_M_AXI_V_ID_WIDTH - 1:0] m_axi_V_WID;
output  [C_M_AXI_V_WUSER_WIDTH - 1:0] m_axi_V_WUSER;
output   m_axi_V_ARVALID;
input   m_axi_V_ARREADY;
output  [C_M_AXI_V_ADDR_WIDTH - 1:0] m_axi_V_ARADDR;
output  [C_M_AXI_V_ID_WIDTH - 1:0] m_axi_V_ARID;
output  [7:0] m_axi_V_ARLEN;
output  [2:0] m_axi_V_ARSIZE;
output  [1:0] m_axi_V_ARBURST;
output  [1:0] m_axi_V_ARLOCK;
output  [3:0] m_axi_V_ARCACHE;
output  [2:0] m_axi_V_ARPROT;
output  [3:0] m_axi_V_ARQOS;
output  [3:0] m_axi_V_ARREGION;
output  [C_M_AXI_V_ARUSER_WIDTH - 1:0] m_axi_V_ARUSER;
input   m_axi_V_RVALID;
output   m_axi_V_RREADY;
input  [C_M_AXI_V_DATA_WIDTH - 1:0] m_axi_V_RDATA;
input   m_axi_V_RLAST;
input  [C_M_AXI_V_ID_WIDTH - 1:0] m_axi_V_RID;
input  [C_M_AXI_V_RUSER_WIDTH - 1:0] m_axi_V_RUSER;
input  [1:0] m_axi_V_RRESP;
input   m_axi_V_BVALID;
output   m_axi_V_BREADY;
input  [1:0] m_axi_V_BRESP;
input  [C_M_AXI_V_ID_WIDTH - 1:0] m_axi_V_BID;
input  [C_M_AXI_V_BUSER_WIDTH - 1:0] m_axi_V_BUSER;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_AWADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_AWID;
output  [7:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [C_M_AXI_GMEM0_AWUSER_WIDTH - 1:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_WDATA;
output  [C_M_AXI_GMEM0_WSTRB_WIDTH - 1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_WID;
output  [C_M_AXI_GMEM0_WUSER_WIDTH - 1:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_ARADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_ARID;
output  [7:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [C_M_AXI_GMEM0_ARUSER_WIDTH - 1:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_RID;
input  [C_M_AXI_GMEM0_RUSER_WIDTH - 1:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_BID;
input  [C_M_AXI_GMEM0_BUSER_WIDTH - 1:0] m_axi_gmem0_BUSER;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;
input  [7:0] in_r_TDATA;
input  [0:0] in_r_TKEEP;
input  [0:0] in_r_TSTRB;
input  [0:0] in_r_TLAST;
output  [7:0] out_r_TDATA;
output  [0:0] out_r_TKEEP;
output  [0:0] out_r_TSTRB;
output  [0:0] out_r_TLAST;
input   in_r_TVALID;
output   in_r_TREADY;
output   out_r_TVALID;
input   out_r_TREADY;

 reg    ap_rst_n_inv;
wire   [63:0] in_q;
wire   [63:0] in_k;
wire   [63:0] in_v;
wire   [63:0] in_o;
wire   [63:0] in_w_up;
wire   [63:0] in_w_down;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire    K_AWREADY;
wire    K_WREADY;
wire    K_ARREADY;
wire    K_RVALID;
wire   [7:0] K_RDATA;
wire    K_RLAST;
wire   [0:0] K_RID;
wire   [12:0] K_RFIFONUM;
wire   [0:0] K_RUSER;
wire   [1:0] K_RRESP;
wire    K_BVALID;
wire    OUT_M_AWREADY;
wire    OUT_M_WREADY;
wire    OUT_M_ARREADY;
wire    OUT_M_RVALID;
wire   [7:0] OUT_M_RDATA;
wire    OUT_M_RLAST;
wire   [0:0] OUT_M_RID;
wire   [12:0] OUT_M_RFIFONUM;
wire   [0:0] OUT_M_RUSER;
wire   [1:0] OUT_M_RRESP;
wire    OUT_M_BVALID;
wire    Q_AWREADY;
wire    Q_WREADY;
wire    Q_ARREADY;
wire    Q_RVALID;
wire   [7:0] Q_RDATA;
wire    Q_RLAST;
wire   [0:0] Q_RID;
wire   [12:0] Q_RFIFONUM;
wire   [0:0] Q_RUSER;
wire   [1:0] Q_RRESP;
wire    Q_BVALID;
wire    V_AWREADY;
wire    V_WREADY;
wire    V_ARREADY;
wire    V_RVALID;
wire   [7:0] V_RDATA;
wire    V_RLAST;
wire   [0:0] V_RID;
wire   [12:0] V_RFIFONUM;
wire   [0:0] V_RUSER;
wire   [1:0] V_RRESP;
wire    V_BVALID;
wire    gmem0_AWREADY;
wire    gmem0_WREADY;
wire    gmem0_ARREADY;
wire    gmem0_RVALID;
wire   [7:0] gmem0_RDATA;
wire    gmem0_RLAST;
wire   [0:0] gmem0_RID;
wire   [12:0] gmem0_RFIFONUM;
wire   [0:0] gmem0_RUSER;
wire   [1:0] gmem0_RRESP;
wire    gmem0_BVALID;
wire    gmem1_AWREADY;
wire    gmem1_WREADY;
wire    gmem1_ARREADY;
wire    gmem1_RVALID;
wire   [7:0] gmem1_RDATA;
wire    gmem1_RLAST;
wire   [0:0] gmem1_RID;
wire   [12:0] gmem1_RFIFONUM;
wire   [0:0] gmem1_RUSER;
wire   [1:0] gmem1_RRESP;
wire    gmem1_BVALID;
wire    axis_to_apuint_U0_ap_start;
wire    axis_to_apuint_U0_ap_done;
wire    axis_to_apuint_U0_ap_continue;
wire    axis_to_apuint_U0_ap_idle;
wire    axis_to_apuint_U0_ap_ready;
wire   [7:0] axis_to_apuint_U0_input_stream1_din;
wire    axis_to_apuint_U0_input_stream1_write;
wire    axis_to_apuint_U0_in_r_TREADY;
wire    ViT_Block_Core_U0_ap_start;
wire    ViT_Block_Core_U0_start_out;
wire    ViT_Block_Core_U0_start_write;
wire    ViT_Block_Core_U0_input_stream1_read;
wire   [7:0] ViT_Block_Core_U0_output_stream2_din;
wire    ViT_Block_Core_U0_output_stream2_write;
wire    ViT_Block_Core_U0_m_axi_Q_AWVALID;
wire   [63:0] ViT_Block_Core_U0_m_axi_Q_AWADDR;
wire   [0:0] ViT_Block_Core_U0_m_axi_Q_AWID;
wire   [31:0] ViT_Block_Core_U0_m_axi_Q_AWLEN;
wire   [2:0] ViT_Block_Core_U0_m_axi_Q_AWSIZE;
wire   [1:0] ViT_Block_Core_U0_m_axi_Q_AWBURST;
wire   [1:0] ViT_Block_Core_U0_m_axi_Q_AWLOCK;
wire   [3:0] ViT_Block_Core_U0_m_axi_Q_AWCACHE;
wire   [2:0] ViT_Block_Core_U0_m_axi_Q_AWPROT;
wire   [3:0] ViT_Block_Core_U0_m_axi_Q_AWQOS;
wire   [3:0] ViT_Block_Core_U0_m_axi_Q_AWREGION;
wire   [0:0] ViT_Block_Core_U0_m_axi_Q_AWUSER;
wire    ViT_Block_Core_U0_m_axi_Q_WVALID;
wire   [7:0] ViT_Block_Core_U0_m_axi_Q_WDATA;
wire   [0:0] ViT_Block_Core_U0_m_axi_Q_WSTRB;
wire    ViT_Block_Core_U0_m_axi_Q_WLAST;
wire   [0:0] ViT_Block_Core_U0_m_axi_Q_WID;
wire   [0:0] ViT_Block_Core_U0_m_axi_Q_WUSER;
wire    ViT_Block_Core_U0_m_axi_Q_ARVALID;
wire   [63:0] ViT_Block_Core_U0_m_axi_Q_ARADDR;
wire   [0:0] ViT_Block_Core_U0_m_axi_Q_ARID;
wire   [31:0] ViT_Block_Core_U0_m_axi_Q_ARLEN;
wire   [2:0] ViT_Block_Core_U0_m_axi_Q_ARSIZE;
wire   [1:0] ViT_Block_Core_U0_m_axi_Q_ARBURST;
wire   [1:0] ViT_Block_Core_U0_m_axi_Q_ARLOCK;
wire   [3:0] ViT_Block_Core_U0_m_axi_Q_ARCACHE;
wire   [2:0] ViT_Block_Core_U0_m_axi_Q_ARPROT;
wire   [3:0] ViT_Block_Core_U0_m_axi_Q_ARQOS;
wire   [3:0] ViT_Block_Core_U0_m_axi_Q_ARREGION;
wire   [0:0] ViT_Block_Core_U0_m_axi_Q_ARUSER;
wire    ViT_Block_Core_U0_m_axi_Q_RREADY;
wire    ViT_Block_Core_U0_m_axi_Q_BREADY;
wire    ViT_Block_Core_U0_m_axi_K_AWVALID;
wire   [63:0] ViT_Block_Core_U0_m_axi_K_AWADDR;
wire   [0:0] ViT_Block_Core_U0_m_axi_K_AWID;
wire   [31:0] ViT_Block_Core_U0_m_axi_K_AWLEN;
wire   [2:0] ViT_Block_Core_U0_m_axi_K_AWSIZE;
wire   [1:0] ViT_Block_Core_U0_m_axi_K_AWBURST;
wire   [1:0] ViT_Block_Core_U0_m_axi_K_AWLOCK;
wire   [3:0] ViT_Block_Core_U0_m_axi_K_AWCACHE;
wire   [2:0] ViT_Block_Core_U0_m_axi_K_AWPROT;
wire   [3:0] ViT_Block_Core_U0_m_axi_K_AWQOS;
wire   [3:0] ViT_Block_Core_U0_m_axi_K_AWREGION;
wire   [0:0] ViT_Block_Core_U0_m_axi_K_AWUSER;
wire    ViT_Block_Core_U0_m_axi_K_WVALID;
wire   [7:0] ViT_Block_Core_U0_m_axi_K_WDATA;
wire   [0:0] ViT_Block_Core_U0_m_axi_K_WSTRB;
wire    ViT_Block_Core_U0_m_axi_K_WLAST;
wire   [0:0] ViT_Block_Core_U0_m_axi_K_WID;
wire   [0:0] ViT_Block_Core_U0_m_axi_K_WUSER;
wire    ViT_Block_Core_U0_m_axi_K_ARVALID;
wire   [63:0] ViT_Block_Core_U0_m_axi_K_ARADDR;
wire   [0:0] ViT_Block_Core_U0_m_axi_K_ARID;
wire   [31:0] ViT_Block_Core_U0_m_axi_K_ARLEN;
wire   [2:0] ViT_Block_Core_U0_m_axi_K_ARSIZE;
wire   [1:0] ViT_Block_Core_U0_m_axi_K_ARBURST;
wire   [1:0] ViT_Block_Core_U0_m_axi_K_ARLOCK;
wire   [3:0] ViT_Block_Core_U0_m_axi_K_ARCACHE;
wire   [2:0] ViT_Block_Core_U0_m_axi_K_ARPROT;
wire   [3:0] ViT_Block_Core_U0_m_axi_K_ARQOS;
wire   [3:0] ViT_Block_Core_U0_m_axi_K_ARREGION;
wire   [0:0] ViT_Block_Core_U0_m_axi_K_ARUSER;
wire    ViT_Block_Core_U0_m_axi_K_RREADY;
wire    ViT_Block_Core_U0_m_axi_K_BREADY;
wire    ViT_Block_Core_U0_m_axi_V_AWVALID;
wire   [63:0] ViT_Block_Core_U0_m_axi_V_AWADDR;
wire   [0:0] ViT_Block_Core_U0_m_axi_V_AWID;
wire   [31:0] ViT_Block_Core_U0_m_axi_V_AWLEN;
wire   [2:0] ViT_Block_Core_U0_m_axi_V_AWSIZE;
wire   [1:0] ViT_Block_Core_U0_m_axi_V_AWBURST;
wire   [1:0] ViT_Block_Core_U0_m_axi_V_AWLOCK;
wire   [3:0] ViT_Block_Core_U0_m_axi_V_AWCACHE;
wire   [2:0] ViT_Block_Core_U0_m_axi_V_AWPROT;
wire   [3:0] ViT_Block_Core_U0_m_axi_V_AWQOS;
wire   [3:0] ViT_Block_Core_U0_m_axi_V_AWREGION;
wire   [0:0] ViT_Block_Core_U0_m_axi_V_AWUSER;
wire    ViT_Block_Core_U0_m_axi_V_WVALID;
wire   [7:0] ViT_Block_Core_U0_m_axi_V_WDATA;
wire   [0:0] ViT_Block_Core_U0_m_axi_V_WSTRB;
wire    ViT_Block_Core_U0_m_axi_V_WLAST;
wire   [0:0] ViT_Block_Core_U0_m_axi_V_WID;
wire   [0:0] ViT_Block_Core_U0_m_axi_V_WUSER;
wire    ViT_Block_Core_U0_m_axi_V_ARVALID;
wire   [63:0] ViT_Block_Core_U0_m_axi_V_ARADDR;
wire   [0:0] ViT_Block_Core_U0_m_axi_V_ARID;
wire   [31:0] ViT_Block_Core_U0_m_axi_V_ARLEN;
wire   [2:0] ViT_Block_Core_U0_m_axi_V_ARSIZE;
wire   [1:0] ViT_Block_Core_U0_m_axi_V_ARBURST;
wire   [1:0] ViT_Block_Core_U0_m_axi_V_ARLOCK;
wire   [3:0] ViT_Block_Core_U0_m_axi_V_ARCACHE;
wire   [2:0] ViT_Block_Core_U0_m_axi_V_ARPROT;
wire   [3:0] ViT_Block_Core_U0_m_axi_V_ARQOS;
wire   [3:0] ViT_Block_Core_U0_m_axi_V_ARREGION;
wire   [0:0] ViT_Block_Core_U0_m_axi_V_ARUSER;
wire    ViT_Block_Core_U0_m_axi_V_RREADY;
wire    ViT_Block_Core_U0_m_axi_V_BREADY;
wire    ViT_Block_Core_U0_m_axi_OUT_M_AWVALID;
wire   [63:0] ViT_Block_Core_U0_m_axi_OUT_M_AWADDR;
wire   [0:0] ViT_Block_Core_U0_m_axi_OUT_M_AWID;
wire   [31:0] ViT_Block_Core_U0_m_axi_OUT_M_AWLEN;
wire   [2:0] ViT_Block_Core_U0_m_axi_OUT_M_AWSIZE;
wire   [1:0] ViT_Block_Core_U0_m_axi_OUT_M_AWBURST;
wire   [1:0] ViT_Block_Core_U0_m_axi_OUT_M_AWLOCK;
wire   [3:0] ViT_Block_Core_U0_m_axi_OUT_M_AWCACHE;
wire   [2:0] ViT_Block_Core_U0_m_axi_OUT_M_AWPROT;
wire   [3:0] ViT_Block_Core_U0_m_axi_OUT_M_AWQOS;
wire   [3:0] ViT_Block_Core_U0_m_axi_OUT_M_AWREGION;
wire   [0:0] ViT_Block_Core_U0_m_axi_OUT_M_AWUSER;
wire    ViT_Block_Core_U0_m_axi_OUT_M_WVALID;
wire   [7:0] ViT_Block_Core_U0_m_axi_OUT_M_WDATA;
wire   [0:0] ViT_Block_Core_U0_m_axi_OUT_M_WSTRB;
wire    ViT_Block_Core_U0_m_axi_OUT_M_WLAST;
wire   [0:0] ViT_Block_Core_U0_m_axi_OUT_M_WID;
wire   [0:0] ViT_Block_Core_U0_m_axi_OUT_M_WUSER;
wire    ViT_Block_Core_U0_m_axi_OUT_M_ARVALID;
wire   [63:0] ViT_Block_Core_U0_m_axi_OUT_M_ARADDR;
wire   [0:0] ViT_Block_Core_U0_m_axi_OUT_M_ARID;
wire   [31:0] ViT_Block_Core_U0_m_axi_OUT_M_ARLEN;
wire   [2:0] ViT_Block_Core_U0_m_axi_OUT_M_ARSIZE;
wire   [1:0] ViT_Block_Core_U0_m_axi_OUT_M_ARBURST;
wire   [1:0] ViT_Block_Core_U0_m_axi_OUT_M_ARLOCK;
wire   [3:0] ViT_Block_Core_U0_m_axi_OUT_M_ARCACHE;
wire   [2:0] ViT_Block_Core_U0_m_axi_OUT_M_ARPROT;
wire   [3:0] ViT_Block_Core_U0_m_axi_OUT_M_ARQOS;
wire   [3:0] ViT_Block_Core_U0_m_axi_OUT_M_ARREGION;
wire   [0:0] ViT_Block_Core_U0_m_axi_OUT_M_ARUSER;
wire    ViT_Block_Core_U0_m_axi_OUT_M_RREADY;
wire    ViT_Block_Core_U0_m_axi_OUT_M_BREADY;
wire    ViT_Block_Core_U0_m_axi_gmem0_AWVALID;
wire   [63:0] ViT_Block_Core_U0_m_axi_gmem0_AWADDR;
wire   [0:0] ViT_Block_Core_U0_m_axi_gmem0_AWID;
wire   [31:0] ViT_Block_Core_U0_m_axi_gmem0_AWLEN;
wire   [2:0] ViT_Block_Core_U0_m_axi_gmem0_AWSIZE;
wire   [1:0] ViT_Block_Core_U0_m_axi_gmem0_AWBURST;
wire   [1:0] ViT_Block_Core_U0_m_axi_gmem0_AWLOCK;
wire   [3:0] ViT_Block_Core_U0_m_axi_gmem0_AWCACHE;
wire   [2:0] ViT_Block_Core_U0_m_axi_gmem0_AWPROT;
wire   [3:0] ViT_Block_Core_U0_m_axi_gmem0_AWQOS;
wire   [3:0] ViT_Block_Core_U0_m_axi_gmem0_AWREGION;
wire   [0:0] ViT_Block_Core_U0_m_axi_gmem0_AWUSER;
wire    ViT_Block_Core_U0_m_axi_gmem0_WVALID;
wire   [7:0] ViT_Block_Core_U0_m_axi_gmem0_WDATA;
wire   [0:0] ViT_Block_Core_U0_m_axi_gmem0_WSTRB;
wire    ViT_Block_Core_U0_m_axi_gmem0_WLAST;
wire   [0:0] ViT_Block_Core_U0_m_axi_gmem0_WID;
wire   [0:0] ViT_Block_Core_U0_m_axi_gmem0_WUSER;
wire    ViT_Block_Core_U0_m_axi_gmem0_ARVALID;
wire   [63:0] ViT_Block_Core_U0_m_axi_gmem0_ARADDR;
wire   [0:0] ViT_Block_Core_U0_m_axi_gmem0_ARID;
wire   [31:0] ViT_Block_Core_U0_m_axi_gmem0_ARLEN;
wire   [2:0] ViT_Block_Core_U0_m_axi_gmem0_ARSIZE;
wire   [1:0] ViT_Block_Core_U0_m_axi_gmem0_ARBURST;
wire   [1:0] ViT_Block_Core_U0_m_axi_gmem0_ARLOCK;
wire   [3:0] ViT_Block_Core_U0_m_axi_gmem0_ARCACHE;
wire   [2:0] ViT_Block_Core_U0_m_axi_gmem0_ARPROT;
wire   [3:0] ViT_Block_Core_U0_m_axi_gmem0_ARQOS;
wire   [3:0] ViT_Block_Core_U0_m_axi_gmem0_ARREGION;
wire   [0:0] ViT_Block_Core_U0_m_axi_gmem0_ARUSER;
wire    ViT_Block_Core_U0_m_axi_gmem0_RREADY;
wire    ViT_Block_Core_U0_m_axi_gmem0_BREADY;
wire    ViT_Block_Core_U0_m_axi_gmem1_AWVALID;
wire   [63:0] ViT_Block_Core_U0_m_axi_gmem1_AWADDR;
wire   [0:0] ViT_Block_Core_U0_m_axi_gmem1_AWID;
wire   [31:0] ViT_Block_Core_U0_m_axi_gmem1_AWLEN;
wire   [2:0] ViT_Block_Core_U0_m_axi_gmem1_AWSIZE;
wire   [1:0] ViT_Block_Core_U0_m_axi_gmem1_AWBURST;
wire   [1:0] ViT_Block_Core_U0_m_axi_gmem1_AWLOCK;
wire   [3:0] ViT_Block_Core_U0_m_axi_gmem1_AWCACHE;
wire   [2:0] ViT_Block_Core_U0_m_axi_gmem1_AWPROT;
wire   [3:0] ViT_Block_Core_U0_m_axi_gmem1_AWQOS;
wire   [3:0] ViT_Block_Core_U0_m_axi_gmem1_AWREGION;
wire   [0:0] ViT_Block_Core_U0_m_axi_gmem1_AWUSER;
wire    ViT_Block_Core_U0_m_axi_gmem1_WVALID;
wire   [7:0] ViT_Block_Core_U0_m_axi_gmem1_WDATA;
wire   [0:0] ViT_Block_Core_U0_m_axi_gmem1_WSTRB;
wire    ViT_Block_Core_U0_m_axi_gmem1_WLAST;
wire   [0:0] ViT_Block_Core_U0_m_axi_gmem1_WID;
wire   [0:0] ViT_Block_Core_U0_m_axi_gmem1_WUSER;
wire    ViT_Block_Core_U0_m_axi_gmem1_ARVALID;
wire   [63:0] ViT_Block_Core_U0_m_axi_gmem1_ARADDR;
wire   [0:0] ViT_Block_Core_U0_m_axi_gmem1_ARID;
wire   [31:0] ViT_Block_Core_U0_m_axi_gmem1_ARLEN;
wire   [2:0] ViT_Block_Core_U0_m_axi_gmem1_ARSIZE;
wire   [1:0] ViT_Block_Core_U0_m_axi_gmem1_ARBURST;
wire   [1:0] ViT_Block_Core_U0_m_axi_gmem1_ARLOCK;
wire   [3:0] ViT_Block_Core_U0_m_axi_gmem1_ARCACHE;
wire   [2:0] ViT_Block_Core_U0_m_axi_gmem1_ARPROT;
wire   [3:0] ViT_Block_Core_U0_m_axi_gmem1_ARQOS;
wire   [3:0] ViT_Block_Core_U0_m_axi_gmem1_ARREGION;
wire   [0:0] ViT_Block_Core_U0_m_axi_gmem1_ARUSER;
wire    ViT_Block_Core_U0_m_axi_gmem1_RREADY;
wire    ViT_Block_Core_U0_m_axi_gmem1_BREADY;
wire    ViT_Block_Core_U0_ap_done;
wire    ViT_Block_Core_U0_ap_ready;
wire    ViT_Block_Core_U0_ap_idle;
wire    ViT_Block_Core_U0_ap_continue;
wire    apuint_to_axis_U0_ap_start;
wire    apuint_to_axis_U0_ap_done;
wire    apuint_to_axis_U0_ap_continue;
wire    apuint_to_axis_U0_ap_idle;
wire    apuint_to_axis_U0_ap_ready;
wire    apuint_to_axis_U0_output_stream2_read;
wire   [7:0] apuint_to_axis_U0_out_r_TDATA;
wire    apuint_to_axis_U0_out_r_TVALID;
wire   [0:0] apuint_to_axis_U0_out_r_TKEEP;
wire   [0:0] apuint_to_axis_U0_out_r_TSTRB;
wire   [0:0] apuint_to_axis_U0_out_r_TLAST;
wire    input_stream_full_n;
wire   [7:0] input_stream_dout;
wire   [1:0] input_stream_num_data_valid;
wire   [1:0] input_stream_fifo_cap;
wire    input_stream_empty_n;
wire    output_stream_full_n;
wire   [7:0] output_stream_dout;
wire   [1:0] output_stream_num_data_valid;
wire   [1:0] output_stream_fifo_cap;
wire    output_stream_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_axis_to_apuint_U0_ap_ready;
wire    ap_sync_axis_to_apuint_U0_ap_ready;
reg    ap_sync_reg_ViT_Block_Core_U0_ap_ready;
wire    ap_sync_ViT_Block_Core_U0_ap_ready;
wire   [0:0] start_for_apuint_to_axis_U0_din;
wire    start_for_apuint_to_axis_U0_full_n;
wire   [0:0] start_for_apuint_to_axis_U0_dout;
wire    start_for_apuint_to_axis_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_axis_to_apuint_U0_ap_ready = 1'b0;
#0 ap_sync_reg_ViT_Block_Core_U0_ap_ready = 1'b0;
end

ViT_Block_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .in_q(in_q),
    .in_k(in_k),
    .in_v(in_v),
    .in_o(in_o),
    .in_w_up(in_w_up),
    .in_w_down(in_w_down),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

ViT_Block_K_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 64 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_K_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_K_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_K_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_K_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_K_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_K_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_K_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_K_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_K_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_K_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_K_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 13 ),
    .USER_DW( 8 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
K_m_axi_U(
    .AWVALID(m_axi_K_AWVALID),
    .AWREADY(m_axi_K_AWREADY),
    .AWADDR(m_axi_K_AWADDR),
    .AWID(m_axi_K_AWID),
    .AWLEN(m_axi_K_AWLEN),
    .AWSIZE(m_axi_K_AWSIZE),
    .AWBURST(m_axi_K_AWBURST),
    .AWLOCK(m_axi_K_AWLOCK),
    .AWCACHE(m_axi_K_AWCACHE),
    .AWPROT(m_axi_K_AWPROT),
    .AWQOS(m_axi_K_AWQOS),
    .AWREGION(m_axi_K_AWREGION),
    .AWUSER(m_axi_K_AWUSER),
    .WVALID(m_axi_K_WVALID),
    .WREADY(m_axi_K_WREADY),
    .WDATA(m_axi_K_WDATA),
    .WSTRB(m_axi_K_WSTRB),
    .WLAST(m_axi_K_WLAST),
    .WID(m_axi_K_WID),
    .WUSER(m_axi_K_WUSER),
    .ARVALID(m_axi_K_ARVALID),
    .ARREADY(m_axi_K_ARREADY),
    .ARADDR(m_axi_K_ARADDR),
    .ARID(m_axi_K_ARID),
    .ARLEN(m_axi_K_ARLEN),
    .ARSIZE(m_axi_K_ARSIZE),
    .ARBURST(m_axi_K_ARBURST),
    .ARLOCK(m_axi_K_ARLOCK),
    .ARCACHE(m_axi_K_ARCACHE),
    .ARPROT(m_axi_K_ARPROT),
    .ARQOS(m_axi_K_ARQOS),
    .ARREGION(m_axi_K_ARREGION),
    .ARUSER(m_axi_K_ARUSER),
    .RVALID(m_axi_K_RVALID),
    .RREADY(m_axi_K_RREADY),
    .RDATA(m_axi_K_RDATA),
    .RLAST(m_axi_K_RLAST),
    .RID(m_axi_K_RID),
    .RUSER(m_axi_K_RUSER),
    .RRESP(m_axi_K_RRESP),
    .BVALID(m_axi_K_BVALID),
    .BREADY(m_axi_K_BREADY),
    .BRESP(m_axi_K_BRESP),
    .BID(m_axi_K_BID),
    .BUSER(m_axi_K_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(ViT_Block_Core_U0_m_axi_K_ARVALID),
    .I_ARREADY(K_ARREADY),
    .I_ARADDR(ViT_Block_Core_U0_m_axi_K_ARADDR),
    .I_ARLEN(ViT_Block_Core_U0_m_axi_K_ARLEN),
    .I_RVALID(K_RVALID),
    .I_RREADY(ViT_Block_Core_U0_m_axi_K_RREADY),
    .I_RDATA(K_RDATA),
    .I_RFIFONUM(K_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(K_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(K_WREADY),
    .I_WDATA(8'd0),
    .I_WSTRB(1'd0),
    .I_BVALID(K_BVALID),
    .I_BREADY(1'b0)
);

ViT_Block_OUT_M_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 64 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_OUT_M_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_OUT_M_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_OUT_M_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_OUT_M_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_OUT_M_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_OUT_M_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_OUT_M_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_OUT_M_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_OUT_M_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_OUT_M_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_OUT_M_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 13 ),
    .USER_DW( 8 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
OUT_M_m_axi_U(
    .AWVALID(m_axi_OUT_M_AWVALID),
    .AWREADY(m_axi_OUT_M_AWREADY),
    .AWADDR(m_axi_OUT_M_AWADDR),
    .AWID(m_axi_OUT_M_AWID),
    .AWLEN(m_axi_OUT_M_AWLEN),
    .AWSIZE(m_axi_OUT_M_AWSIZE),
    .AWBURST(m_axi_OUT_M_AWBURST),
    .AWLOCK(m_axi_OUT_M_AWLOCK),
    .AWCACHE(m_axi_OUT_M_AWCACHE),
    .AWPROT(m_axi_OUT_M_AWPROT),
    .AWQOS(m_axi_OUT_M_AWQOS),
    .AWREGION(m_axi_OUT_M_AWREGION),
    .AWUSER(m_axi_OUT_M_AWUSER),
    .WVALID(m_axi_OUT_M_WVALID),
    .WREADY(m_axi_OUT_M_WREADY),
    .WDATA(m_axi_OUT_M_WDATA),
    .WSTRB(m_axi_OUT_M_WSTRB),
    .WLAST(m_axi_OUT_M_WLAST),
    .WID(m_axi_OUT_M_WID),
    .WUSER(m_axi_OUT_M_WUSER),
    .ARVALID(m_axi_OUT_M_ARVALID),
    .ARREADY(m_axi_OUT_M_ARREADY),
    .ARADDR(m_axi_OUT_M_ARADDR),
    .ARID(m_axi_OUT_M_ARID),
    .ARLEN(m_axi_OUT_M_ARLEN),
    .ARSIZE(m_axi_OUT_M_ARSIZE),
    .ARBURST(m_axi_OUT_M_ARBURST),
    .ARLOCK(m_axi_OUT_M_ARLOCK),
    .ARCACHE(m_axi_OUT_M_ARCACHE),
    .ARPROT(m_axi_OUT_M_ARPROT),
    .ARQOS(m_axi_OUT_M_ARQOS),
    .ARREGION(m_axi_OUT_M_ARREGION),
    .ARUSER(m_axi_OUT_M_ARUSER),
    .RVALID(m_axi_OUT_M_RVALID),
    .RREADY(m_axi_OUT_M_RREADY),
    .RDATA(m_axi_OUT_M_RDATA),
    .RLAST(m_axi_OUT_M_RLAST),
    .RID(m_axi_OUT_M_RID),
    .RUSER(m_axi_OUT_M_RUSER),
    .RRESP(m_axi_OUT_M_RRESP),
    .BVALID(m_axi_OUT_M_BVALID),
    .BREADY(m_axi_OUT_M_BREADY),
    .BRESP(m_axi_OUT_M_BRESP),
    .BID(m_axi_OUT_M_BID),
    .BUSER(m_axi_OUT_M_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(ViT_Block_Core_U0_m_axi_OUT_M_ARVALID),
    .I_ARREADY(OUT_M_ARREADY),
    .I_ARADDR(ViT_Block_Core_U0_m_axi_OUT_M_ARADDR),
    .I_ARLEN(ViT_Block_Core_U0_m_axi_OUT_M_ARLEN),
    .I_RVALID(OUT_M_RVALID),
    .I_RREADY(ViT_Block_Core_U0_m_axi_OUT_M_RREADY),
    .I_RDATA(OUT_M_RDATA),
    .I_RFIFONUM(OUT_M_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(OUT_M_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(OUT_M_WREADY),
    .I_WDATA(8'd0),
    .I_WSTRB(1'd0),
    .I_BVALID(OUT_M_BVALID),
    .I_BREADY(1'b0)
);

ViT_Block_Q_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 64 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_Q_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_Q_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_Q_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_Q_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_Q_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_Q_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_Q_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_Q_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_Q_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_Q_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_Q_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 13 ),
    .USER_DW( 8 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
Q_m_axi_U(
    .AWVALID(m_axi_Q_AWVALID),
    .AWREADY(m_axi_Q_AWREADY),
    .AWADDR(m_axi_Q_AWADDR),
    .AWID(m_axi_Q_AWID),
    .AWLEN(m_axi_Q_AWLEN),
    .AWSIZE(m_axi_Q_AWSIZE),
    .AWBURST(m_axi_Q_AWBURST),
    .AWLOCK(m_axi_Q_AWLOCK),
    .AWCACHE(m_axi_Q_AWCACHE),
    .AWPROT(m_axi_Q_AWPROT),
    .AWQOS(m_axi_Q_AWQOS),
    .AWREGION(m_axi_Q_AWREGION),
    .AWUSER(m_axi_Q_AWUSER),
    .WVALID(m_axi_Q_WVALID),
    .WREADY(m_axi_Q_WREADY),
    .WDATA(m_axi_Q_WDATA),
    .WSTRB(m_axi_Q_WSTRB),
    .WLAST(m_axi_Q_WLAST),
    .WID(m_axi_Q_WID),
    .WUSER(m_axi_Q_WUSER),
    .ARVALID(m_axi_Q_ARVALID),
    .ARREADY(m_axi_Q_ARREADY),
    .ARADDR(m_axi_Q_ARADDR),
    .ARID(m_axi_Q_ARID),
    .ARLEN(m_axi_Q_ARLEN),
    .ARSIZE(m_axi_Q_ARSIZE),
    .ARBURST(m_axi_Q_ARBURST),
    .ARLOCK(m_axi_Q_ARLOCK),
    .ARCACHE(m_axi_Q_ARCACHE),
    .ARPROT(m_axi_Q_ARPROT),
    .ARQOS(m_axi_Q_ARQOS),
    .ARREGION(m_axi_Q_ARREGION),
    .ARUSER(m_axi_Q_ARUSER),
    .RVALID(m_axi_Q_RVALID),
    .RREADY(m_axi_Q_RREADY),
    .RDATA(m_axi_Q_RDATA),
    .RLAST(m_axi_Q_RLAST),
    .RID(m_axi_Q_RID),
    .RUSER(m_axi_Q_RUSER),
    .RRESP(m_axi_Q_RRESP),
    .BVALID(m_axi_Q_BVALID),
    .BREADY(m_axi_Q_BREADY),
    .BRESP(m_axi_Q_BRESP),
    .BID(m_axi_Q_BID),
    .BUSER(m_axi_Q_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(ViT_Block_Core_U0_m_axi_Q_ARVALID),
    .I_ARREADY(Q_ARREADY),
    .I_ARADDR(ViT_Block_Core_U0_m_axi_Q_ARADDR),
    .I_ARLEN(ViT_Block_Core_U0_m_axi_Q_ARLEN),
    .I_RVALID(Q_RVALID),
    .I_RREADY(ViT_Block_Core_U0_m_axi_Q_RREADY),
    .I_RDATA(Q_RDATA),
    .I_RFIFONUM(Q_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(Q_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(Q_WREADY),
    .I_WDATA(8'd0),
    .I_WSTRB(1'd0),
    .I_BVALID(Q_BVALID),
    .I_BREADY(1'b0)
);

ViT_Block_V_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 64 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_V_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_V_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_V_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_V_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_V_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_V_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_V_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_V_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_V_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_V_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_V_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 13 ),
    .USER_DW( 8 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
V_m_axi_U(
    .AWVALID(m_axi_V_AWVALID),
    .AWREADY(m_axi_V_AWREADY),
    .AWADDR(m_axi_V_AWADDR),
    .AWID(m_axi_V_AWID),
    .AWLEN(m_axi_V_AWLEN),
    .AWSIZE(m_axi_V_AWSIZE),
    .AWBURST(m_axi_V_AWBURST),
    .AWLOCK(m_axi_V_AWLOCK),
    .AWCACHE(m_axi_V_AWCACHE),
    .AWPROT(m_axi_V_AWPROT),
    .AWQOS(m_axi_V_AWQOS),
    .AWREGION(m_axi_V_AWREGION),
    .AWUSER(m_axi_V_AWUSER),
    .WVALID(m_axi_V_WVALID),
    .WREADY(m_axi_V_WREADY),
    .WDATA(m_axi_V_WDATA),
    .WSTRB(m_axi_V_WSTRB),
    .WLAST(m_axi_V_WLAST),
    .WID(m_axi_V_WID),
    .WUSER(m_axi_V_WUSER),
    .ARVALID(m_axi_V_ARVALID),
    .ARREADY(m_axi_V_ARREADY),
    .ARADDR(m_axi_V_ARADDR),
    .ARID(m_axi_V_ARID),
    .ARLEN(m_axi_V_ARLEN),
    .ARSIZE(m_axi_V_ARSIZE),
    .ARBURST(m_axi_V_ARBURST),
    .ARLOCK(m_axi_V_ARLOCK),
    .ARCACHE(m_axi_V_ARCACHE),
    .ARPROT(m_axi_V_ARPROT),
    .ARQOS(m_axi_V_ARQOS),
    .ARREGION(m_axi_V_ARREGION),
    .ARUSER(m_axi_V_ARUSER),
    .RVALID(m_axi_V_RVALID),
    .RREADY(m_axi_V_RREADY),
    .RDATA(m_axi_V_RDATA),
    .RLAST(m_axi_V_RLAST),
    .RID(m_axi_V_RID),
    .RUSER(m_axi_V_RUSER),
    .RRESP(m_axi_V_RRESP),
    .BVALID(m_axi_V_BVALID),
    .BREADY(m_axi_V_BREADY),
    .BRESP(m_axi_V_BRESP),
    .BID(m_axi_V_BID),
    .BUSER(m_axi_V_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(ViT_Block_Core_U0_m_axi_V_ARVALID),
    .I_ARREADY(V_ARREADY),
    .I_ARADDR(ViT_Block_Core_U0_m_axi_V_ARADDR),
    .I_ARLEN(ViT_Block_Core_U0_m_axi_V_ARLEN),
    .I_RVALID(V_RVALID),
    .I_RREADY(ViT_Block_Core_U0_m_axi_V_RREADY),
    .I_RDATA(V_RDATA),
    .I_RFIFONUM(V_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(V_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(V_WREADY),
    .I_WDATA(8'd0),
    .I_WSTRB(1'd0),
    .I_BVALID(V_BVALID),
    .I_BREADY(1'b0)
);

ViT_Block_gmem0_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 64 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM0_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 13 ),
    .USER_DW( 8 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem0_m_axi_U(
    .AWVALID(m_axi_gmem0_AWVALID),
    .AWREADY(m_axi_gmem0_AWREADY),
    .AWADDR(m_axi_gmem0_AWADDR),
    .AWID(m_axi_gmem0_AWID),
    .AWLEN(m_axi_gmem0_AWLEN),
    .AWSIZE(m_axi_gmem0_AWSIZE),
    .AWBURST(m_axi_gmem0_AWBURST),
    .AWLOCK(m_axi_gmem0_AWLOCK),
    .AWCACHE(m_axi_gmem0_AWCACHE),
    .AWPROT(m_axi_gmem0_AWPROT),
    .AWQOS(m_axi_gmem0_AWQOS),
    .AWREGION(m_axi_gmem0_AWREGION),
    .AWUSER(m_axi_gmem0_AWUSER),
    .WVALID(m_axi_gmem0_WVALID),
    .WREADY(m_axi_gmem0_WREADY),
    .WDATA(m_axi_gmem0_WDATA),
    .WSTRB(m_axi_gmem0_WSTRB),
    .WLAST(m_axi_gmem0_WLAST),
    .WID(m_axi_gmem0_WID),
    .WUSER(m_axi_gmem0_WUSER),
    .ARVALID(m_axi_gmem0_ARVALID),
    .ARREADY(m_axi_gmem0_ARREADY),
    .ARADDR(m_axi_gmem0_ARADDR),
    .ARID(m_axi_gmem0_ARID),
    .ARLEN(m_axi_gmem0_ARLEN),
    .ARSIZE(m_axi_gmem0_ARSIZE),
    .ARBURST(m_axi_gmem0_ARBURST),
    .ARLOCK(m_axi_gmem0_ARLOCK),
    .ARCACHE(m_axi_gmem0_ARCACHE),
    .ARPROT(m_axi_gmem0_ARPROT),
    .ARQOS(m_axi_gmem0_ARQOS),
    .ARREGION(m_axi_gmem0_ARREGION),
    .ARUSER(m_axi_gmem0_ARUSER),
    .RVALID(m_axi_gmem0_RVALID),
    .RREADY(m_axi_gmem0_RREADY),
    .RDATA(m_axi_gmem0_RDATA),
    .RLAST(m_axi_gmem0_RLAST),
    .RID(m_axi_gmem0_RID),
    .RUSER(m_axi_gmem0_RUSER),
    .RRESP(m_axi_gmem0_RRESP),
    .BVALID(m_axi_gmem0_BVALID),
    .BREADY(m_axi_gmem0_BREADY),
    .BRESP(m_axi_gmem0_BRESP),
    .BID(m_axi_gmem0_BID),
    .BUSER(m_axi_gmem0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(ViT_Block_Core_U0_m_axi_gmem0_ARVALID),
    .I_ARREADY(gmem0_ARREADY),
    .I_ARADDR(ViT_Block_Core_U0_m_axi_gmem0_ARADDR),
    .I_ARLEN(ViT_Block_Core_U0_m_axi_gmem0_ARLEN),
    .I_RVALID(gmem0_RVALID),
    .I_RREADY(ViT_Block_Core_U0_m_axi_gmem0_RREADY),
    .I_RDATA(gmem0_RDATA),
    .I_RFIFONUM(gmem0_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem0_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem0_WREADY),
    .I_WDATA(8'd0),
    .I_WSTRB(1'd0),
    .I_BVALID(gmem0_BVALID),
    .I_BREADY(1'b0)
);

ViT_Block_gmem1_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 64 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 13 ),
    .USER_DW( 8 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(ViT_Block_Core_U0_m_axi_gmem1_ARVALID),
    .I_ARREADY(gmem1_ARREADY),
    .I_ARADDR(ViT_Block_Core_U0_m_axi_gmem1_ARADDR),
    .I_ARLEN(ViT_Block_Core_U0_m_axi_gmem1_ARLEN),
    .I_RVALID(gmem1_RVALID),
    .I_RREADY(ViT_Block_Core_U0_m_axi_gmem1_RREADY),
    .I_RDATA(gmem1_RDATA),
    .I_RFIFONUM(gmem1_RFIFONUM),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem1_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWLEN(32'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem1_WREADY),
    .I_WDATA(8'd0),
    .I_WSTRB(1'd0),
    .I_BVALID(gmem1_BVALID),
    .I_BREADY(1'b0)
);

ViT_Block_axis_to_apuint axis_to_apuint_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(axis_to_apuint_U0_ap_start),
    .ap_done(axis_to_apuint_U0_ap_done),
    .ap_continue(axis_to_apuint_U0_ap_continue),
    .ap_idle(axis_to_apuint_U0_ap_idle),
    .ap_ready(axis_to_apuint_U0_ap_ready),
    .in_r_TVALID(in_r_TVALID),
    .input_stream1_din(axis_to_apuint_U0_input_stream1_din),
    .input_stream1_num_data_valid(input_stream_num_data_valid),
    .input_stream1_fifo_cap(input_stream_fifo_cap),
    .input_stream1_full_n(input_stream_full_n),
    .input_stream1_write(axis_to_apuint_U0_input_stream1_write),
    .in_r_TDATA(in_r_TDATA),
    .in_r_TREADY(axis_to_apuint_U0_in_r_TREADY),
    .in_r_TKEEP(in_r_TKEEP),
    .in_r_TSTRB(in_r_TSTRB),
    .in_r_TLAST(in_r_TLAST)
);

ViT_Block_ViT_Block_Core ViT_Block_Core_U0(
    .ap_start(ViT_Block_Core_U0_ap_start),
    .start_full_n(start_for_apuint_to_axis_U0_full_n),
    .start_out(ViT_Block_Core_U0_start_out),
    .start_write(ViT_Block_Core_U0_start_write),
    .input_stream1_dout(input_stream_dout),
    .input_stream1_empty_n(input_stream_empty_n),
    .input_stream1_read(ViT_Block_Core_U0_input_stream1_read),
    .output_stream2_din(ViT_Block_Core_U0_output_stream2_din),
    .output_stream2_full_n(output_stream_full_n),
    .output_stream2_write(ViT_Block_Core_U0_output_stream2_write),
    .m_axi_Q_AWVALID(ViT_Block_Core_U0_m_axi_Q_AWVALID),
    .m_axi_Q_AWREADY(1'b0),
    .m_axi_Q_AWADDR(ViT_Block_Core_U0_m_axi_Q_AWADDR),
    .m_axi_Q_AWID(ViT_Block_Core_U0_m_axi_Q_AWID),
    .m_axi_Q_AWLEN(ViT_Block_Core_U0_m_axi_Q_AWLEN),
    .m_axi_Q_AWSIZE(ViT_Block_Core_U0_m_axi_Q_AWSIZE),
    .m_axi_Q_AWBURST(ViT_Block_Core_U0_m_axi_Q_AWBURST),
    .m_axi_Q_AWLOCK(ViT_Block_Core_U0_m_axi_Q_AWLOCK),
    .m_axi_Q_AWCACHE(ViT_Block_Core_U0_m_axi_Q_AWCACHE),
    .m_axi_Q_AWPROT(ViT_Block_Core_U0_m_axi_Q_AWPROT),
    .m_axi_Q_AWQOS(ViT_Block_Core_U0_m_axi_Q_AWQOS),
    .m_axi_Q_AWREGION(ViT_Block_Core_U0_m_axi_Q_AWREGION),
    .m_axi_Q_AWUSER(ViT_Block_Core_U0_m_axi_Q_AWUSER),
    .m_axi_Q_WVALID(ViT_Block_Core_U0_m_axi_Q_WVALID),
    .m_axi_Q_WREADY(1'b0),
    .m_axi_Q_WDATA(ViT_Block_Core_U0_m_axi_Q_WDATA),
    .m_axi_Q_WSTRB(ViT_Block_Core_U0_m_axi_Q_WSTRB),
    .m_axi_Q_WLAST(ViT_Block_Core_U0_m_axi_Q_WLAST),
    .m_axi_Q_WID(ViT_Block_Core_U0_m_axi_Q_WID),
    .m_axi_Q_WUSER(ViT_Block_Core_U0_m_axi_Q_WUSER),
    .m_axi_Q_ARVALID(ViT_Block_Core_U0_m_axi_Q_ARVALID),
    .m_axi_Q_ARREADY(Q_ARREADY),
    .m_axi_Q_ARADDR(ViT_Block_Core_U0_m_axi_Q_ARADDR),
    .m_axi_Q_ARID(ViT_Block_Core_U0_m_axi_Q_ARID),
    .m_axi_Q_ARLEN(ViT_Block_Core_U0_m_axi_Q_ARLEN),
    .m_axi_Q_ARSIZE(ViT_Block_Core_U0_m_axi_Q_ARSIZE),
    .m_axi_Q_ARBURST(ViT_Block_Core_U0_m_axi_Q_ARBURST),
    .m_axi_Q_ARLOCK(ViT_Block_Core_U0_m_axi_Q_ARLOCK),
    .m_axi_Q_ARCACHE(ViT_Block_Core_U0_m_axi_Q_ARCACHE),
    .m_axi_Q_ARPROT(ViT_Block_Core_U0_m_axi_Q_ARPROT),
    .m_axi_Q_ARQOS(ViT_Block_Core_U0_m_axi_Q_ARQOS),
    .m_axi_Q_ARREGION(ViT_Block_Core_U0_m_axi_Q_ARREGION),
    .m_axi_Q_ARUSER(ViT_Block_Core_U0_m_axi_Q_ARUSER),
    .m_axi_Q_RVALID(Q_RVALID),
    .m_axi_Q_RREADY(ViT_Block_Core_U0_m_axi_Q_RREADY),
    .m_axi_Q_RDATA(Q_RDATA),
    .m_axi_Q_RLAST(Q_RLAST),
    .m_axi_Q_RID(Q_RID),
    .m_axi_Q_RFIFONUM(Q_RFIFONUM),
    .m_axi_Q_RUSER(Q_RUSER),
    .m_axi_Q_RRESP(Q_RRESP),
    .m_axi_Q_BVALID(1'b0),
    .m_axi_Q_BREADY(ViT_Block_Core_U0_m_axi_Q_BREADY),
    .m_axi_Q_BRESP(2'd0),
    .m_axi_Q_BID(1'd0),
    .m_axi_Q_BUSER(1'd0),
    .in_q(in_q),
    .m_axi_K_AWVALID(ViT_Block_Core_U0_m_axi_K_AWVALID),
    .m_axi_K_AWREADY(1'b0),
    .m_axi_K_AWADDR(ViT_Block_Core_U0_m_axi_K_AWADDR),
    .m_axi_K_AWID(ViT_Block_Core_U0_m_axi_K_AWID),
    .m_axi_K_AWLEN(ViT_Block_Core_U0_m_axi_K_AWLEN),
    .m_axi_K_AWSIZE(ViT_Block_Core_U0_m_axi_K_AWSIZE),
    .m_axi_K_AWBURST(ViT_Block_Core_U0_m_axi_K_AWBURST),
    .m_axi_K_AWLOCK(ViT_Block_Core_U0_m_axi_K_AWLOCK),
    .m_axi_K_AWCACHE(ViT_Block_Core_U0_m_axi_K_AWCACHE),
    .m_axi_K_AWPROT(ViT_Block_Core_U0_m_axi_K_AWPROT),
    .m_axi_K_AWQOS(ViT_Block_Core_U0_m_axi_K_AWQOS),
    .m_axi_K_AWREGION(ViT_Block_Core_U0_m_axi_K_AWREGION),
    .m_axi_K_AWUSER(ViT_Block_Core_U0_m_axi_K_AWUSER),
    .m_axi_K_WVALID(ViT_Block_Core_U0_m_axi_K_WVALID),
    .m_axi_K_WREADY(1'b0),
    .m_axi_K_WDATA(ViT_Block_Core_U0_m_axi_K_WDATA),
    .m_axi_K_WSTRB(ViT_Block_Core_U0_m_axi_K_WSTRB),
    .m_axi_K_WLAST(ViT_Block_Core_U0_m_axi_K_WLAST),
    .m_axi_K_WID(ViT_Block_Core_U0_m_axi_K_WID),
    .m_axi_K_WUSER(ViT_Block_Core_U0_m_axi_K_WUSER),
    .m_axi_K_ARVALID(ViT_Block_Core_U0_m_axi_K_ARVALID),
    .m_axi_K_ARREADY(K_ARREADY),
    .m_axi_K_ARADDR(ViT_Block_Core_U0_m_axi_K_ARADDR),
    .m_axi_K_ARID(ViT_Block_Core_U0_m_axi_K_ARID),
    .m_axi_K_ARLEN(ViT_Block_Core_U0_m_axi_K_ARLEN),
    .m_axi_K_ARSIZE(ViT_Block_Core_U0_m_axi_K_ARSIZE),
    .m_axi_K_ARBURST(ViT_Block_Core_U0_m_axi_K_ARBURST),
    .m_axi_K_ARLOCK(ViT_Block_Core_U0_m_axi_K_ARLOCK),
    .m_axi_K_ARCACHE(ViT_Block_Core_U0_m_axi_K_ARCACHE),
    .m_axi_K_ARPROT(ViT_Block_Core_U0_m_axi_K_ARPROT),
    .m_axi_K_ARQOS(ViT_Block_Core_U0_m_axi_K_ARQOS),
    .m_axi_K_ARREGION(ViT_Block_Core_U0_m_axi_K_ARREGION),
    .m_axi_K_ARUSER(ViT_Block_Core_U0_m_axi_K_ARUSER),
    .m_axi_K_RVALID(K_RVALID),
    .m_axi_K_RREADY(ViT_Block_Core_U0_m_axi_K_RREADY),
    .m_axi_K_RDATA(K_RDATA),
    .m_axi_K_RLAST(K_RLAST),
    .m_axi_K_RID(K_RID),
    .m_axi_K_RFIFONUM(K_RFIFONUM),
    .m_axi_K_RUSER(K_RUSER),
    .m_axi_K_RRESP(K_RRESP),
    .m_axi_K_BVALID(1'b0),
    .m_axi_K_BREADY(ViT_Block_Core_U0_m_axi_K_BREADY),
    .m_axi_K_BRESP(2'd0),
    .m_axi_K_BID(1'd0),
    .m_axi_K_BUSER(1'd0),
    .in_k(in_k),
    .m_axi_V_AWVALID(ViT_Block_Core_U0_m_axi_V_AWVALID),
    .m_axi_V_AWREADY(1'b0),
    .m_axi_V_AWADDR(ViT_Block_Core_U0_m_axi_V_AWADDR),
    .m_axi_V_AWID(ViT_Block_Core_U0_m_axi_V_AWID),
    .m_axi_V_AWLEN(ViT_Block_Core_U0_m_axi_V_AWLEN),
    .m_axi_V_AWSIZE(ViT_Block_Core_U0_m_axi_V_AWSIZE),
    .m_axi_V_AWBURST(ViT_Block_Core_U0_m_axi_V_AWBURST),
    .m_axi_V_AWLOCK(ViT_Block_Core_U0_m_axi_V_AWLOCK),
    .m_axi_V_AWCACHE(ViT_Block_Core_U0_m_axi_V_AWCACHE),
    .m_axi_V_AWPROT(ViT_Block_Core_U0_m_axi_V_AWPROT),
    .m_axi_V_AWQOS(ViT_Block_Core_U0_m_axi_V_AWQOS),
    .m_axi_V_AWREGION(ViT_Block_Core_U0_m_axi_V_AWREGION),
    .m_axi_V_AWUSER(ViT_Block_Core_U0_m_axi_V_AWUSER),
    .m_axi_V_WVALID(ViT_Block_Core_U0_m_axi_V_WVALID),
    .m_axi_V_WREADY(1'b0),
    .m_axi_V_WDATA(ViT_Block_Core_U0_m_axi_V_WDATA),
    .m_axi_V_WSTRB(ViT_Block_Core_U0_m_axi_V_WSTRB),
    .m_axi_V_WLAST(ViT_Block_Core_U0_m_axi_V_WLAST),
    .m_axi_V_WID(ViT_Block_Core_U0_m_axi_V_WID),
    .m_axi_V_WUSER(ViT_Block_Core_U0_m_axi_V_WUSER),
    .m_axi_V_ARVALID(ViT_Block_Core_U0_m_axi_V_ARVALID),
    .m_axi_V_ARREADY(V_ARREADY),
    .m_axi_V_ARADDR(ViT_Block_Core_U0_m_axi_V_ARADDR),
    .m_axi_V_ARID(ViT_Block_Core_U0_m_axi_V_ARID),
    .m_axi_V_ARLEN(ViT_Block_Core_U0_m_axi_V_ARLEN),
    .m_axi_V_ARSIZE(ViT_Block_Core_U0_m_axi_V_ARSIZE),
    .m_axi_V_ARBURST(ViT_Block_Core_U0_m_axi_V_ARBURST),
    .m_axi_V_ARLOCK(ViT_Block_Core_U0_m_axi_V_ARLOCK),
    .m_axi_V_ARCACHE(ViT_Block_Core_U0_m_axi_V_ARCACHE),
    .m_axi_V_ARPROT(ViT_Block_Core_U0_m_axi_V_ARPROT),
    .m_axi_V_ARQOS(ViT_Block_Core_U0_m_axi_V_ARQOS),
    .m_axi_V_ARREGION(ViT_Block_Core_U0_m_axi_V_ARREGION),
    .m_axi_V_ARUSER(ViT_Block_Core_U0_m_axi_V_ARUSER),
    .m_axi_V_RVALID(V_RVALID),
    .m_axi_V_RREADY(ViT_Block_Core_U0_m_axi_V_RREADY),
    .m_axi_V_RDATA(V_RDATA),
    .m_axi_V_RLAST(V_RLAST),
    .m_axi_V_RID(V_RID),
    .m_axi_V_RFIFONUM(V_RFIFONUM),
    .m_axi_V_RUSER(V_RUSER),
    .m_axi_V_RRESP(V_RRESP),
    .m_axi_V_BVALID(1'b0),
    .m_axi_V_BREADY(ViT_Block_Core_U0_m_axi_V_BREADY),
    .m_axi_V_BRESP(2'd0),
    .m_axi_V_BID(1'd0),
    .m_axi_V_BUSER(1'd0),
    .in_v(in_v),
    .m_axi_OUT_M_AWVALID(ViT_Block_Core_U0_m_axi_OUT_M_AWVALID),
    .m_axi_OUT_M_AWREADY(1'b0),
    .m_axi_OUT_M_AWADDR(ViT_Block_Core_U0_m_axi_OUT_M_AWADDR),
    .m_axi_OUT_M_AWID(ViT_Block_Core_U0_m_axi_OUT_M_AWID),
    .m_axi_OUT_M_AWLEN(ViT_Block_Core_U0_m_axi_OUT_M_AWLEN),
    .m_axi_OUT_M_AWSIZE(ViT_Block_Core_U0_m_axi_OUT_M_AWSIZE),
    .m_axi_OUT_M_AWBURST(ViT_Block_Core_U0_m_axi_OUT_M_AWBURST),
    .m_axi_OUT_M_AWLOCK(ViT_Block_Core_U0_m_axi_OUT_M_AWLOCK),
    .m_axi_OUT_M_AWCACHE(ViT_Block_Core_U0_m_axi_OUT_M_AWCACHE),
    .m_axi_OUT_M_AWPROT(ViT_Block_Core_U0_m_axi_OUT_M_AWPROT),
    .m_axi_OUT_M_AWQOS(ViT_Block_Core_U0_m_axi_OUT_M_AWQOS),
    .m_axi_OUT_M_AWREGION(ViT_Block_Core_U0_m_axi_OUT_M_AWREGION),
    .m_axi_OUT_M_AWUSER(ViT_Block_Core_U0_m_axi_OUT_M_AWUSER),
    .m_axi_OUT_M_WVALID(ViT_Block_Core_U0_m_axi_OUT_M_WVALID),
    .m_axi_OUT_M_WREADY(1'b0),
    .m_axi_OUT_M_WDATA(ViT_Block_Core_U0_m_axi_OUT_M_WDATA),
    .m_axi_OUT_M_WSTRB(ViT_Block_Core_U0_m_axi_OUT_M_WSTRB),
    .m_axi_OUT_M_WLAST(ViT_Block_Core_U0_m_axi_OUT_M_WLAST),
    .m_axi_OUT_M_WID(ViT_Block_Core_U0_m_axi_OUT_M_WID),
    .m_axi_OUT_M_WUSER(ViT_Block_Core_U0_m_axi_OUT_M_WUSER),
    .m_axi_OUT_M_ARVALID(ViT_Block_Core_U0_m_axi_OUT_M_ARVALID),
    .m_axi_OUT_M_ARREADY(OUT_M_ARREADY),
    .m_axi_OUT_M_ARADDR(ViT_Block_Core_U0_m_axi_OUT_M_ARADDR),
    .m_axi_OUT_M_ARID(ViT_Block_Core_U0_m_axi_OUT_M_ARID),
    .m_axi_OUT_M_ARLEN(ViT_Block_Core_U0_m_axi_OUT_M_ARLEN),
    .m_axi_OUT_M_ARSIZE(ViT_Block_Core_U0_m_axi_OUT_M_ARSIZE),
    .m_axi_OUT_M_ARBURST(ViT_Block_Core_U0_m_axi_OUT_M_ARBURST),
    .m_axi_OUT_M_ARLOCK(ViT_Block_Core_U0_m_axi_OUT_M_ARLOCK),
    .m_axi_OUT_M_ARCACHE(ViT_Block_Core_U0_m_axi_OUT_M_ARCACHE),
    .m_axi_OUT_M_ARPROT(ViT_Block_Core_U0_m_axi_OUT_M_ARPROT),
    .m_axi_OUT_M_ARQOS(ViT_Block_Core_U0_m_axi_OUT_M_ARQOS),
    .m_axi_OUT_M_ARREGION(ViT_Block_Core_U0_m_axi_OUT_M_ARREGION),
    .m_axi_OUT_M_ARUSER(ViT_Block_Core_U0_m_axi_OUT_M_ARUSER),
    .m_axi_OUT_M_RVALID(OUT_M_RVALID),
    .m_axi_OUT_M_RREADY(ViT_Block_Core_U0_m_axi_OUT_M_RREADY),
    .m_axi_OUT_M_RDATA(OUT_M_RDATA),
    .m_axi_OUT_M_RLAST(OUT_M_RLAST),
    .m_axi_OUT_M_RID(OUT_M_RID),
    .m_axi_OUT_M_RFIFONUM(OUT_M_RFIFONUM),
    .m_axi_OUT_M_RUSER(OUT_M_RUSER),
    .m_axi_OUT_M_RRESP(OUT_M_RRESP),
    .m_axi_OUT_M_BVALID(1'b0),
    .m_axi_OUT_M_BREADY(ViT_Block_Core_U0_m_axi_OUT_M_BREADY),
    .m_axi_OUT_M_BRESP(2'd0),
    .m_axi_OUT_M_BID(1'd0),
    .m_axi_OUT_M_BUSER(1'd0),
    .in_o(in_o),
    .m_axi_gmem0_AWVALID(ViT_Block_Core_U0_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(1'b0),
    .m_axi_gmem0_AWADDR(ViT_Block_Core_U0_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(ViT_Block_Core_U0_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(ViT_Block_Core_U0_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(ViT_Block_Core_U0_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(ViT_Block_Core_U0_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(ViT_Block_Core_U0_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(ViT_Block_Core_U0_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(ViT_Block_Core_U0_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(ViT_Block_Core_U0_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(ViT_Block_Core_U0_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(ViT_Block_Core_U0_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(ViT_Block_Core_U0_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(1'b0),
    .m_axi_gmem0_WDATA(ViT_Block_Core_U0_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(ViT_Block_Core_U0_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(ViT_Block_Core_U0_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(ViT_Block_Core_U0_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(ViT_Block_Core_U0_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(ViT_Block_Core_U0_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(gmem0_ARREADY),
    .m_axi_gmem0_ARADDR(ViT_Block_Core_U0_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(ViT_Block_Core_U0_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(ViT_Block_Core_U0_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(ViT_Block_Core_U0_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(ViT_Block_Core_U0_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(ViT_Block_Core_U0_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(ViT_Block_Core_U0_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(ViT_Block_Core_U0_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(ViT_Block_Core_U0_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(ViT_Block_Core_U0_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(ViT_Block_Core_U0_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(gmem0_RVALID),
    .m_axi_gmem0_RREADY(ViT_Block_Core_U0_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(gmem0_RDATA),
    .m_axi_gmem0_RLAST(gmem0_RLAST),
    .m_axi_gmem0_RID(gmem0_RID),
    .m_axi_gmem0_RFIFONUM(gmem0_RFIFONUM),
    .m_axi_gmem0_RUSER(gmem0_RUSER),
    .m_axi_gmem0_RRESP(gmem0_RRESP),
    .m_axi_gmem0_BVALID(1'b0),
    .m_axi_gmem0_BREADY(ViT_Block_Core_U0_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(2'd0),
    .m_axi_gmem0_BID(1'd0),
    .m_axi_gmem0_BUSER(1'd0),
    .in_w_up(in_w_up),
    .m_axi_gmem1_AWVALID(ViT_Block_Core_U0_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(1'b0),
    .m_axi_gmem1_AWADDR(ViT_Block_Core_U0_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(ViT_Block_Core_U0_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(ViT_Block_Core_U0_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(ViT_Block_Core_U0_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(ViT_Block_Core_U0_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(ViT_Block_Core_U0_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(ViT_Block_Core_U0_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(ViT_Block_Core_U0_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(ViT_Block_Core_U0_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(ViT_Block_Core_U0_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(ViT_Block_Core_U0_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(ViT_Block_Core_U0_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(1'b0),
    .m_axi_gmem1_WDATA(ViT_Block_Core_U0_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(ViT_Block_Core_U0_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(ViT_Block_Core_U0_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(ViT_Block_Core_U0_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(ViT_Block_Core_U0_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(ViT_Block_Core_U0_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(gmem1_ARREADY),
    .m_axi_gmem1_ARADDR(ViT_Block_Core_U0_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(ViT_Block_Core_U0_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(ViT_Block_Core_U0_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(ViT_Block_Core_U0_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(ViT_Block_Core_U0_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(ViT_Block_Core_U0_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(ViT_Block_Core_U0_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(ViT_Block_Core_U0_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(ViT_Block_Core_U0_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(ViT_Block_Core_U0_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(ViT_Block_Core_U0_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(gmem1_RVALID),
    .m_axi_gmem1_RREADY(ViT_Block_Core_U0_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(gmem1_RDATA),
    .m_axi_gmem1_RLAST(gmem1_RLAST),
    .m_axi_gmem1_RID(gmem1_RID),
    .m_axi_gmem1_RFIFONUM(gmem1_RFIFONUM),
    .m_axi_gmem1_RUSER(gmem1_RUSER),
    .m_axi_gmem1_RRESP(gmem1_RRESP),
    .m_axi_gmem1_BVALID(1'b0),
    .m_axi_gmem1_BREADY(ViT_Block_Core_U0_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(2'd0),
    .m_axi_gmem1_BID(1'd0),
    .m_axi_gmem1_BUSER(1'd0),
    .in_w_down(in_w_down),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .in_q_ap_vld(1'b1),
    .in_k_ap_vld(1'b1),
    .in_v_ap_vld(1'b1),
    .in_o_ap_vld(1'b1),
    .in_w_up_ap_vld(1'b1),
    .in_w_down_ap_vld(1'b1),
    .ap_done(ViT_Block_Core_U0_ap_done),
    .ap_ready(ViT_Block_Core_U0_ap_ready),
    .ap_idle(ViT_Block_Core_U0_ap_idle),
    .ap_continue(ViT_Block_Core_U0_ap_continue)
);

ViT_Block_apuint_to_axis apuint_to_axis_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(apuint_to_axis_U0_ap_start),
    .ap_done(apuint_to_axis_U0_ap_done),
    .ap_continue(apuint_to_axis_U0_ap_continue),
    .ap_idle(apuint_to_axis_U0_ap_idle),
    .ap_ready(apuint_to_axis_U0_ap_ready),
    .output_stream2_dout(output_stream_dout),
    .output_stream2_num_data_valid(output_stream_num_data_valid),
    .output_stream2_fifo_cap(output_stream_fifo_cap),
    .output_stream2_empty_n(output_stream_empty_n),
    .output_stream2_read(apuint_to_axis_U0_output_stream2_read),
    .out_r_TREADY(out_r_TREADY),
    .out_r_TDATA(apuint_to_axis_U0_out_r_TDATA),
    .out_r_TVALID(apuint_to_axis_U0_out_r_TVALID),
    .out_r_TKEEP(apuint_to_axis_U0_out_r_TKEEP),
    .out_r_TSTRB(apuint_to_axis_U0_out_r_TSTRB),
    .out_r_TLAST(apuint_to_axis_U0_out_r_TLAST)
);

ViT_Block_fifo_w8_d2_S_x0 input_stream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(axis_to_apuint_U0_input_stream1_din),
    .if_full_n(input_stream_full_n),
    .if_write(axis_to_apuint_U0_input_stream1_write),
    .if_dout(input_stream_dout),
    .if_num_data_valid(input_stream_num_data_valid),
    .if_fifo_cap(input_stream_fifo_cap),
    .if_empty_n(input_stream_empty_n),
    .if_read(ViT_Block_Core_U0_input_stream1_read)
);

ViT_Block_fifo_w8_d2_S_x0 output_stream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(ViT_Block_Core_U0_output_stream2_din),
    .if_full_n(output_stream_full_n),
    .if_write(ViT_Block_Core_U0_output_stream2_write),
    .if_dout(output_stream_dout),
    .if_num_data_valid(output_stream_num_data_valid),
    .if_fifo_cap(output_stream_fifo_cap),
    .if_empty_n(output_stream_empty_n),
    .if_read(apuint_to_axis_U0_output_stream2_read)
);

ViT_Block_start_for_apuint_to_axis_U0 start_for_apuint_to_axis_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_apuint_to_axis_U0_din),
    .if_full_n(start_for_apuint_to_axis_U0_full_n),
    .if_write(ViT_Block_Core_U0_start_write),
    .if_dout(start_for_apuint_to_axis_U0_dout),
    .if_empty_n(start_for_apuint_to_axis_U0_empty_n),
    .if_read(apuint_to_axis_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_ViT_Block_Core_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_ViT_Block_Core_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_ViT_Block_Core_U0_ap_ready <= ap_sync_ViT_Block_Core_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_axis_to_apuint_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_axis_to_apuint_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_axis_to_apuint_U0_ap_ready <= ap_sync_axis_to_apuint_U0_ap_ready;
        end
    end
end

assign K_RID = 1'd0;

assign K_RLAST = 1'b0;

assign K_RRESP = 2'd0;

assign K_RUSER = 1'd0;

assign OUT_M_RID = 1'd0;

assign OUT_M_RLAST = 1'b0;

assign OUT_M_RRESP = 2'd0;

assign OUT_M_RUSER = 1'd0;

assign Q_RID = 1'd0;

assign Q_RLAST = 1'b0;

assign Q_RRESP = 2'd0;

assign Q_RUSER = 1'd0;

assign V_RID = 1'd0;

assign V_RLAST = 1'b0;

assign V_RRESP = 2'd0;

assign V_RUSER = 1'd0;

assign ViT_Block_Core_U0_ap_continue = 1'b1;

assign ViT_Block_Core_U0_ap_start = ((ap_sync_reg_ViT_Block_Core_U0_ap_ready ^ 1'b1) & ap_start);

assign ap_done = apuint_to_axis_U0_ap_done;

assign ap_idle = (axis_to_apuint_U0_ap_idle & apuint_to_axis_U0_ap_idle & ViT_Block_Core_U0_ap_idle);

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_ViT_Block_Core_U0_ap_ready = (ap_sync_reg_ViT_Block_Core_U0_ap_ready | ViT_Block_Core_U0_ap_ready);

assign ap_sync_axis_to_apuint_U0_ap_ready = (axis_to_apuint_U0_ap_ready | ap_sync_reg_axis_to_apuint_U0_ap_ready);

assign ap_sync_ready = (ap_sync_axis_to_apuint_U0_ap_ready & ap_sync_ViT_Block_Core_U0_ap_ready);

assign apuint_to_axis_U0_ap_continue = 1'b1;

assign apuint_to_axis_U0_ap_start = start_for_apuint_to_axis_U0_empty_n;

assign axis_to_apuint_U0_ap_continue = 1'b1;

assign axis_to_apuint_U0_ap_start = ((ap_sync_reg_axis_to_apuint_U0_ap_ready ^ 1'b1) & ap_start);

assign gmem0_RID = 1'd0;

assign gmem0_RLAST = 1'b0;

assign gmem0_RRESP = 2'd0;

assign gmem0_RUSER = 1'd0;

assign gmem1_RID = 1'd0;

assign gmem1_RLAST = 1'b0;

assign gmem1_RRESP = 2'd0;

assign gmem1_RUSER = 1'd0;

assign in_r_TREADY = axis_to_apuint_U0_in_r_TREADY;

assign out_r_TDATA = apuint_to_axis_U0_out_r_TDATA;

assign out_r_TKEEP = apuint_to_axis_U0_out_r_TKEEP;

assign out_r_TLAST = apuint_to_axis_U0_out_r_TLAST;

assign out_r_TSTRB = apuint_to_axis_U0_out_r_TSTRB;

assign out_r_TVALID = apuint_to_axis_U0_out_r_TVALID;

assign start_for_apuint_to_axis_U0_din = 1'b1;

endmodule //ViT_Block
