// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ViT_Block_MM1_tiled_7 (
        A_sx_1_dout,
        A_sx_1_empty_n,
        A_sx_1_read,
        V_1_1_dout,
        V_1_1_empty_n,
        V_1_1_read,
        head_out_1_din,
        head_out_1_full_n,
        head_out_1_write,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [7:0] A_sx_1_dout;
input   A_sx_1_empty_n;
output   A_sx_1_read;
input  [7:0] V_1_1_dout;
input   V_1_1_empty_n;
output   V_1_1_read;
output  [7:0] head_out_1_din;
input   head_out_1_full_n;
output   head_out_1_write;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    MatMul_KV_tiled_17_17_48_1_1_1_1_1_382_16_0_ap_int_8_ap_int_32_19_U0_ap_start;
wire    MatMul_KV_tiled_17_17_48_1_1_1_1_1_382_16_0_ap_int_8_ap_int_32_19_U0_ap_done;
wire    MatMul_KV_tiled_17_17_48_1_1_1_1_1_382_16_0_ap_int_8_ap_int_32_19_U0_ap_continue;
wire    MatMul_KV_tiled_17_17_48_1_1_1_1_1_382_16_0_ap_int_8_ap_int_32_19_U0_ap_idle;
wire    MatMul_KV_tiled_17_17_48_1_1_1_1_1_382_16_0_ap_int_8_ap_int_32_19_U0_ap_ready;
wire    MatMul_KV_tiled_17_17_48_1_1_1_1_1_382_16_0_ap_int_8_ap_int_32_19_U0_A_sx_1_read;
wire    MatMul_KV_tiled_17_17_48_1_1_1_1_1_382_16_0_ap_int_8_ap_int_32_19_U0_V_1_1_read;
wire   [7:0] MatMul_KV_tiled_17_17_48_1_1_1_1_1_382_16_0_ap_int_8_ap_int_32_19_U0_head_out_1_din;
wire    MatMul_KV_tiled_17_17_48_1_1_1_1_1_382_16_0_ap_int_8_ap_int_32_19_U0_head_out_1_write;

ViT_Block_MatMul_KV_tiled_17_17_48_1_1_1_1_1_382_16_0_ap_int_8_ap_int_32_19 MatMul_KV_tiled_17_17_48_1_1_1_1_1_382_16_0_ap_int_8_ap_int_32_19_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(MatMul_KV_tiled_17_17_48_1_1_1_1_1_382_16_0_ap_int_8_ap_int_32_19_U0_ap_start),
    .ap_done(MatMul_KV_tiled_17_17_48_1_1_1_1_1_382_16_0_ap_int_8_ap_int_32_19_U0_ap_done),
    .ap_continue(MatMul_KV_tiled_17_17_48_1_1_1_1_1_382_16_0_ap_int_8_ap_int_32_19_U0_ap_continue),
    .ap_idle(MatMul_KV_tiled_17_17_48_1_1_1_1_1_382_16_0_ap_int_8_ap_int_32_19_U0_ap_idle),
    .ap_ready(MatMul_KV_tiled_17_17_48_1_1_1_1_1_382_16_0_ap_int_8_ap_int_32_19_U0_ap_ready),
    .A_sx_1_dout(A_sx_1_dout),
    .A_sx_1_num_data_valid(2'd0),
    .A_sx_1_fifo_cap(2'd0),
    .A_sx_1_empty_n(A_sx_1_empty_n),
    .A_sx_1_read(MatMul_KV_tiled_17_17_48_1_1_1_1_1_382_16_0_ap_int_8_ap_int_32_19_U0_A_sx_1_read),
    .V_1_1_dout(V_1_1_dout),
    .V_1_1_num_data_valid(2'd0),
    .V_1_1_fifo_cap(2'd0),
    .V_1_1_empty_n(V_1_1_empty_n),
    .V_1_1_read(MatMul_KV_tiled_17_17_48_1_1_1_1_1_382_16_0_ap_int_8_ap_int_32_19_U0_V_1_1_read),
    .head_out_1_din(MatMul_KV_tiled_17_17_48_1_1_1_1_1_382_16_0_ap_int_8_ap_int_32_19_U0_head_out_1_din),
    .head_out_1_num_data_valid(2'd0),
    .head_out_1_fifo_cap(2'd0),
    .head_out_1_full_n(head_out_1_full_n),
    .head_out_1_write(MatMul_KV_tiled_17_17_48_1_1_1_1_1_382_16_0_ap_int_8_ap_int_32_19_U0_head_out_1_write)
);

assign A_sx_1_read = MatMul_KV_tiled_17_17_48_1_1_1_1_1_382_16_0_ap_int_8_ap_int_32_19_U0_A_sx_1_read;

assign MatMul_KV_tiled_17_17_48_1_1_1_1_1_382_16_0_ap_int_8_ap_int_32_19_U0_ap_continue = ap_continue;

assign MatMul_KV_tiled_17_17_48_1_1_1_1_1_382_16_0_ap_int_8_ap_int_32_19_U0_ap_start = ap_start;

assign V_1_1_read = MatMul_KV_tiled_17_17_48_1_1_1_1_1_382_16_0_ap_int_8_ap_int_32_19_U0_V_1_1_read;

assign ap_done = MatMul_KV_tiled_17_17_48_1_1_1_1_1_382_16_0_ap_int_8_ap_int_32_19_U0_ap_done;

assign ap_idle = MatMul_KV_tiled_17_17_48_1_1_1_1_1_382_16_0_ap_int_8_ap_int_32_19_U0_ap_idle;

assign ap_ready = MatMul_KV_tiled_17_17_48_1_1_1_1_1_382_16_0_ap_int_8_ap_int_32_19_U0_ap_ready;

assign head_out_1_din = MatMul_KV_tiled_17_17_48_1_1_1_1_1_382_16_0_ap_int_8_ap_int_32_19_U0_head_out_1_din;

assign head_out_1_write = MatMul_KV_tiled_17_17_48_1_1_1_1_1_382_16_0_ap_int_8_ap_int_32_19_U0_head_out_1_write;

endmodule //ViT_Block_MM1_tiled_7
