-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ViT_Block_Out_linear_tiled is
port (
    m_axi_Out_r_AWVALID : OUT STD_LOGIC;
    m_axi_Out_r_AWREADY : IN STD_LOGIC;
    m_axi_Out_r_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_Out_r_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_Out_r_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_Out_r_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_Out_r_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_Out_r_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_Out_r_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_Out_r_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_Out_r_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_Out_r_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_Out_r_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_Out_r_WVALID : OUT STD_LOGIC;
    m_axi_Out_r_WREADY : IN STD_LOGIC;
    m_axi_Out_r_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_Out_r_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_Out_r_WLAST : OUT STD_LOGIC;
    m_axi_Out_r_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_Out_r_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_Out_r_ARVALID : OUT STD_LOGIC;
    m_axi_Out_r_ARREADY : IN STD_LOGIC;
    m_axi_Out_r_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_Out_r_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_Out_r_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_Out_r_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_Out_r_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_Out_r_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_Out_r_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_Out_r_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_Out_r_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_Out_r_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_Out_r_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_Out_r_RVALID : IN STD_LOGIC;
    m_axi_Out_r_RREADY : OUT STD_LOGIC;
    m_axi_Out_r_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_Out_r_RLAST : IN STD_LOGIC;
    m_axi_Out_r_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_Out_r_RFIFONUM : IN STD_LOGIC_VECTOR (12 downto 0);
    m_axi_Out_r_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_Out_r_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_Out_r_BVALID : IN STD_LOGIC;
    m_axi_Out_r_BREADY : OUT STD_LOGIC;
    m_axi_Out_r_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_Out_r_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_Out_r_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_w : IN STD_LOGIC_VECTOR (63 downto 0);
    out_linear4_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    out_linear4_empty_n : IN STD_LOGIC;
    out_linear4_read : OUT STD_LOGIC;
    out_mha8_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    out_mha8_full_n : IN STD_LOGIC;
    out_mha8_write : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    in_w_ap_vld : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of ViT_Block_Out_linear_tiled is 
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";

attribute shreg_extract : string;
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_ap_start : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_ap_done : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_ap_continue : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_ap_idle : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_ap_ready : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_start_out : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_start_write : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_AWVALID : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_WVALID : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_WDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_WSTRB : STD_LOGIC_VECTOR (0 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_WLAST : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARVALID : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_RREADY : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_BREADY : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_out_w1_din : STD_LOGIC_VECTOR (7 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_out_w1_write : STD_LOGIC;
    signal Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_ap_start : STD_LOGIC;
    signal Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_ap_done : STD_LOGIC;
    signal Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_ap_continue : STD_LOGIC;
    signal Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_ap_idle : STD_LOGIC;
    signal Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_ap_ready : STD_LOGIC;
    signal Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_out_linear4_read : STD_LOGIC;
    signal Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_out_mha8_din : STD_LOGIC_VECTOR (7 downto 0);
    signal Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_out_mha8_write : STD_LOGIC;
    signal Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_out_w1_read : STD_LOGIC;
    signal out_w_full_n : STD_LOGIC;
    signal out_w_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal out_w_num_data_valid : STD_LOGIC_VECTOR (6 downto 0);
    signal out_w_fifo_cap : STD_LOGIC_VECTOR (6 downto 0);
    signal out_w_empty_n : STD_LOGIC;
    signal start_for_Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_full_n : STD_LOGIC;
    signal start_for_Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_empty_n : STD_LOGIC;

    component ViT_Block_WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        m_axi_Out_r_AWVALID : OUT STD_LOGIC;
        m_axi_Out_r_AWREADY : IN STD_LOGIC;
        m_axi_Out_r_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_Out_r_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_Out_r_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_Out_r_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_Out_r_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_Out_r_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_Out_r_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_Out_r_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_Out_r_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_Out_r_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_Out_r_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_Out_r_WVALID : OUT STD_LOGIC;
        m_axi_Out_r_WREADY : IN STD_LOGIC;
        m_axi_Out_r_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_Out_r_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_Out_r_WLAST : OUT STD_LOGIC;
        m_axi_Out_r_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_Out_r_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_Out_r_ARVALID : OUT STD_LOGIC;
        m_axi_Out_r_ARREADY : IN STD_LOGIC;
        m_axi_Out_r_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_Out_r_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_Out_r_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_Out_r_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_Out_r_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_Out_r_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_Out_r_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_Out_r_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_Out_r_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_Out_r_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_Out_r_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_Out_r_RVALID : IN STD_LOGIC;
        m_axi_Out_r_RREADY : OUT STD_LOGIC;
        m_axi_Out_r_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        m_axi_Out_r_RLAST : IN STD_LOGIC;
        m_axi_Out_r_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_Out_r_RFIFONUM : IN STD_LOGIC_VECTOR (12 downto 0);
        m_axi_Out_r_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_Out_r_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_Out_r_BVALID : IN STD_LOGIC;
        m_axi_Out_r_BREADY : OUT STD_LOGIC;
        m_axi_Out_r_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_Out_r_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_Out_r_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        W_ddr_tile : IN STD_LOGIC_VECTOR (63 downto 0);
        out_w1_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        out_w1_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        out_w1_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        out_w1_full_n : IN STD_LOGIC;
        out_w1_write : OUT STD_LOGIC );
    end component;


    component ViT_Block_Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        out_linear4_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        out_linear4_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        out_linear4_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        out_linear4_empty_n : IN STD_LOGIC;
        out_linear4_read : OUT STD_LOGIC;
        out_mha8_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        out_mha8_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        out_mha8_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        out_mha8_full_n : IN STD_LOGIC;
        out_mha8_write : OUT STD_LOGIC;
        out_w1_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        out_w1_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        out_w1_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        out_w1_empty_n : IN STD_LOGIC;
        out_w1_read : OUT STD_LOGIC );
    end component;


    component ViT_Block_fifo_w8_d64_S_x4 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (6 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (6 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component ViT_Block_start_for_Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0 : component ViT_Block_WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_ap_start,
        start_full_n => start_for_Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_full_n,
        ap_done => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_ap_done,
        ap_continue => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_ap_continue,
        ap_idle => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_ap_idle,
        ap_ready => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_ap_ready,
        start_out => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_start_out,
        start_write => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_start_write,
        m_axi_Out_r_AWVALID => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_AWVALID,
        m_axi_Out_r_AWREADY => ap_const_logic_0,
        m_axi_Out_r_AWADDR => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_AWADDR,
        m_axi_Out_r_AWID => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_AWID,
        m_axi_Out_r_AWLEN => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_AWLEN,
        m_axi_Out_r_AWSIZE => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_AWSIZE,
        m_axi_Out_r_AWBURST => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_AWBURST,
        m_axi_Out_r_AWLOCK => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_AWLOCK,
        m_axi_Out_r_AWCACHE => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_AWCACHE,
        m_axi_Out_r_AWPROT => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_AWPROT,
        m_axi_Out_r_AWQOS => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_AWQOS,
        m_axi_Out_r_AWREGION => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_AWREGION,
        m_axi_Out_r_AWUSER => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_AWUSER,
        m_axi_Out_r_WVALID => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_WVALID,
        m_axi_Out_r_WREADY => ap_const_logic_0,
        m_axi_Out_r_WDATA => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_WDATA,
        m_axi_Out_r_WSTRB => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_WSTRB,
        m_axi_Out_r_WLAST => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_WLAST,
        m_axi_Out_r_WID => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_WID,
        m_axi_Out_r_WUSER => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_WUSER,
        m_axi_Out_r_ARVALID => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARVALID,
        m_axi_Out_r_ARREADY => m_axi_Out_r_ARREADY,
        m_axi_Out_r_ARADDR => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARADDR,
        m_axi_Out_r_ARID => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARID,
        m_axi_Out_r_ARLEN => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARLEN,
        m_axi_Out_r_ARSIZE => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARSIZE,
        m_axi_Out_r_ARBURST => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARBURST,
        m_axi_Out_r_ARLOCK => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARLOCK,
        m_axi_Out_r_ARCACHE => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARCACHE,
        m_axi_Out_r_ARPROT => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARPROT,
        m_axi_Out_r_ARQOS => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARQOS,
        m_axi_Out_r_ARREGION => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARREGION,
        m_axi_Out_r_ARUSER => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARUSER,
        m_axi_Out_r_RVALID => m_axi_Out_r_RVALID,
        m_axi_Out_r_RREADY => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_RREADY,
        m_axi_Out_r_RDATA => m_axi_Out_r_RDATA,
        m_axi_Out_r_RLAST => m_axi_Out_r_RLAST,
        m_axi_Out_r_RID => m_axi_Out_r_RID,
        m_axi_Out_r_RFIFONUM => m_axi_Out_r_RFIFONUM,
        m_axi_Out_r_RUSER => m_axi_Out_r_RUSER,
        m_axi_Out_r_RRESP => m_axi_Out_r_RRESP,
        m_axi_Out_r_BVALID => ap_const_logic_0,
        m_axi_Out_r_BREADY => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_BREADY,
        m_axi_Out_r_BRESP => ap_const_lv2_0,
        m_axi_Out_r_BID => ap_const_lv1_0,
        m_axi_Out_r_BUSER => ap_const_lv1_0,
        W_ddr_tile => in_w,
        out_w1_din => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_out_w1_din,
        out_w1_num_data_valid => out_w_num_data_valid,
        out_w1_fifo_cap => out_w_fifo_cap,
        out_w1_full_n => out_w_full_n,
        out_w1_write => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_out_w1_write);

    Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0 : component ViT_Block_Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_ap_start,
        ap_done => Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_ap_done,
        ap_continue => Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_ap_continue,
        ap_idle => Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_ap_idle,
        ap_ready => Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_ap_ready,
        out_linear4_dout => out_linear4_dout,
        out_linear4_num_data_valid => ap_const_lv2_0,
        out_linear4_fifo_cap => ap_const_lv2_0,
        out_linear4_empty_n => out_linear4_empty_n,
        out_linear4_read => Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_out_linear4_read,
        out_mha8_din => Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_out_mha8_din,
        out_mha8_num_data_valid => ap_const_lv2_0,
        out_mha8_fifo_cap => ap_const_lv2_0,
        out_mha8_full_n => out_mha8_full_n,
        out_mha8_write => Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_out_mha8_write,
        out_w1_dout => out_w_dout,
        out_w1_num_data_valid => out_w_num_data_valid,
        out_w1_fifo_cap => out_w_fifo_cap,
        out_w1_empty_n => out_w_empty_n,
        out_w1_read => Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_out_w1_read);

    out_w_U : component ViT_Block_fifo_w8_d64_S_x4
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_out_w1_din,
        if_full_n => out_w_full_n,
        if_write => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_out_w1_write,
        if_dout => out_w_dout,
        if_num_data_valid => out_w_num_data_valid,
        if_fifo_cap => out_w_fifo_cap,
        if_empty_n => out_w_empty_n,
        if_read => Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_out_w1_read);

    start_for_Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_U : component ViT_Block_start_for_Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_din,
        if_full_n => start_for_Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_full_n,
        if_write => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_start_write,
        if_dout => start_for_Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_dout,
        if_empty_n => start_for_Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_empty_n,
        if_read => Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_ap_ready);




    Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_ap_continue <= ap_continue;
    Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_ap_start <= start_for_Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_empty_n;
    WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_ap_continue <= ap_const_logic_1;
    WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_ap_start <= ap_start;
    ap_done <= Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_ap_done;
    ap_idle <= (WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_ap_idle and Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_ap_idle);
    ap_ready <= WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_ap_ready;
    m_axi_Out_r_ARADDR <= WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARADDR;
    m_axi_Out_r_ARBURST <= WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARBURST;
    m_axi_Out_r_ARCACHE <= WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARCACHE;
    m_axi_Out_r_ARID <= WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARID;
    m_axi_Out_r_ARLEN <= WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARLEN;
    m_axi_Out_r_ARLOCK <= WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARLOCK;
    m_axi_Out_r_ARPROT <= WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARPROT;
    m_axi_Out_r_ARQOS <= WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARQOS;
    m_axi_Out_r_ARREGION <= WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARREGION;
    m_axi_Out_r_ARSIZE <= WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARSIZE;
    m_axi_Out_r_ARUSER <= WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARUSER;
    m_axi_Out_r_ARVALID <= WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_ARVALID;
    m_axi_Out_r_AWADDR <= ap_const_lv64_0;
    m_axi_Out_r_AWBURST <= ap_const_lv2_0;
    m_axi_Out_r_AWCACHE <= ap_const_lv4_0;
    m_axi_Out_r_AWID <= ap_const_lv1_0;
    m_axi_Out_r_AWLEN <= ap_const_lv32_0;
    m_axi_Out_r_AWLOCK <= ap_const_lv2_0;
    m_axi_Out_r_AWPROT <= ap_const_lv3_0;
    m_axi_Out_r_AWQOS <= ap_const_lv4_0;
    m_axi_Out_r_AWREGION <= ap_const_lv4_0;
    m_axi_Out_r_AWSIZE <= ap_const_lv3_0;
    m_axi_Out_r_AWUSER <= ap_const_lv1_0;
    m_axi_Out_r_AWVALID <= ap_const_logic_0;
    m_axi_Out_r_BREADY <= ap_const_logic_0;
    m_axi_Out_r_RREADY <= WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_12_U0_m_axi_Out_r_RREADY;
    m_axi_Out_r_WDATA <= ap_const_lv8_0;
    m_axi_Out_r_WID <= ap_const_lv1_0;
    m_axi_Out_r_WLAST <= ap_const_logic_0;
    m_axi_Out_r_WSTRB <= ap_const_lv1_0;
    m_axi_Out_r_WUSER <= ap_const_lv1_0;
    m_axi_Out_r_WVALID <= ap_const_logic_0;
    out_linear4_read <= Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_out_linear4_read;
    out_mha8_din <= Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_out_mha8_din;
    out_mha8_write <= Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_out_mha8_write;
    start_for_Linear_Layer_17_16_16_1_1_1_1_1_1_536_16_0_ap_int_ap_int_ap_int_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
