-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ViT_Block_V_linear_tiled is
port (
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    m_axi_V_AWVALID : OUT STD_LOGIC;
    m_axi_V_AWREADY : IN STD_LOGIC;
    m_axi_V_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_V_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_V_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_V_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_V_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_V_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_V_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_V_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_V_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_V_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_V_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_V_WVALID : OUT STD_LOGIC;
    m_axi_V_WREADY : IN STD_LOGIC;
    m_axi_V_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_V_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_V_WLAST : OUT STD_LOGIC;
    m_axi_V_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_V_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_V_ARVALID : OUT STD_LOGIC;
    m_axi_V_ARREADY : IN STD_LOGIC;
    m_axi_V_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_V_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_V_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_V_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_V_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_V_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_V_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_V_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_V_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_V_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_V_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_V_RVALID : IN STD_LOGIC;
    m_axi_V_RREADY : OUT STD_LOGIC;
    m_axi_V_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_V_RLAST : IN STD_LOGIC;
    m_axi_V_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_V_RFIFONUM : IN STD_LOGIC_VECTOR (12 downto 0);
    m_axi_V_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_V_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_V_BVALID : IN STD_LOGIC;
    m_axi_V_BREADY : OUT STD_LOGIC;
    m_axi_V_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_V_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_V_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_w : IN STD_LOGIC_VECTOR (63 downto 0);
    V_in7_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    V_in7_empty_n : IN STD_LOGIC;
    V_in7_read : OUT STD_LOGIC;
    v_lin3_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    v_lin3_full_n : IN STD_LOGIC;
    v_lin3_write : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    in_w_ap_vld : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of ViT_Block_V_linear_tiled is 
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal internal_ap_ready : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_ap_start : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_ap_done : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_ap_continue : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_ap_idle : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_ap_ready : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_start_out : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_start_write : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_AWVALID : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_WVALID : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_WDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_WSTRB : STD_LOGIC_VECTOR (0 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_WLAST : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARVALID : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_RREADY : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_BREADY : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_out_w1_din : STD_LOGIC_VECTOR (7 downto 0);
    signal WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_out_w1_write : STD_LOGIC;
    signal Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_ap_start : STD_LOGIC;
    signal Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_ap_done : STD_LOGIC;
    signal Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_ap_continue : STD_LOGIC;
    signal Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_ap_idle : STD_LOGIC;
    signal Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_ap_ready : STD_LOGIC;
    signal Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_V_in7_read : STD_LOGIC;
    signal Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_v_lin3_din : STD_LOGIC_VECTOR (7 downto 0);
    signal Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_v_lin3_write : STD_LOGIC;
    signal Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_out_w1_read : STD_LOGIC;
    signal out_w_full_n : STD_LOGIC;
    signal out_w_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal out_w_num_data_valid : STD_LOGIC_VECTOR (6 downto 0);
    signal out_w_fifo_cap : STD_LOGIC_VECTOR (6 downto 0);
    signal out_w_empty_n : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal start_for_Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_full_n : STD_LOGIC;
    signal start_for_Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_empty_n : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ViT_Block_WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        m_axi_V_AWVALID : OUT STD_LOGIC;
        m_axi_V_AWREADY : IN STD_LOGIC;
        m_axi_V_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_V_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_V_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_V_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_V_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_V_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_V_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_V_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_V_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_V_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_V_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_V_WVALID : OUT STD_LOGIC;
        m_axi_V_WREADY : IN STD_LOGIC;
        m_axi_V_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_V_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_V_WLAST : OUT STD_LOGIC;
        m_axi_V_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_V_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_V_ARVALID : OUT STD_LOGIC;
        m_axi_V_ARREADY : IN STD_LOGIC;
        m_axi_V_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_V_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_V_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_V_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_V_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_V_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_V_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_V_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_V_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_V_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_V_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_V_RVALID : IN STD_LOGIC;
        m_axi_V_RREADY : OUT STD_LOGIC;
        m_axi_V_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        m_axi_V_RLAST : IN STD_LOGIC;
        m_axi_V_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_V_RFIFONUM : IN STD_LOGIC_VECTOR (12 downto 0);
        m_axi_V_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_V_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_V_BVALID : IN STD_LOGIC;
        m_axi_V_BREADY : OUT STD_LOGIC;
        m_axi_V_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_V_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_V_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        W_ddr_tile : IN STD_LOGIC_VECTOR (63 downto 0);
        out_w1_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        out_w1_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        out_w1_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        out_w1_full_n : IN STD_LOGIC;
        out_w1_write : OUT STD_LOGIC );
    end component;


    component ViT_Block_Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        V_in7_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        V_in7_num_data_valid : IN STD_LOGIC_VECTOR (12 downto 0);
        V_in7_fifo_cap : IN STD_LOGIC_VECTOR (12 downto 0);
        V_in7_empty_n : IN STD_LOGIC;
        V_in7_read : OUT STD_LOGIC;
        v_lin3_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        v_lin3_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        v_lin3_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        v_lin3_full_n : IN STD_LOGIC;
        v_lin3_write : OUT STD_LOGIC;
        out_w1_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        out_w1_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        out_w1_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        out_w1_empty_n : IN STD_LOGIC;
        out_w1_read : OUT STD_LOGIC );
    end component;


    component ViT_Block_fifo_w8_d64_S_x2 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (6 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (6 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component ViT_Block_start_for_Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0 : component ViT_Block_WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_ap_start,
        start_full_n => start_for_Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_full_n,
        ap_done => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_ap_done,
        ap_continue => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_ap_continue,
        ap_idle => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_ap_idle,
        ap_ready => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_ap_ready,
        start_out => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_start_out,
        start_write => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_start_write,
        m_axi_V_AWVALID => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_AWVALID,
        m_axi_V_AWREADY => ap_const_logic_0,
        m_axi_V_AWADDR => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_AWADDR,
        m_axi_V_AWID => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_AWID,
        m_axi_V_AWLEN => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_AWLEN,
        m_axi_V_AWSIZE => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_AWSIZE,
        m_axi_V_AWBURST => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_AWBURST,
        m_axi_V_AWLOCK => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_AWLOCK,
        m_axi_V_AWCACHE => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_AWCACHE,
        m_axi_V_AWPROT => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_AWPROT,
        m_axi_V_AWQOS => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_AWQOS,
        m_axi_V_AWREGION => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_AWREGION,
        m_axi_V_AWUSER => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_AWUSER,
        m_axi_V_WVALID => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_WVALID,
        m_axi_V_WREADY => ap_const_logic_0,
        m_axi_V_WDATA => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_WDATA,
        m_axi_V_WSTRB => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_WSTRB,
        m_axi_V_WLAST => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_WLAST,
        m_axi_V_WID => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_WID,
        m_axi_V_WUSER => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_WUSER,
        m_axi_V_ARVALID => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARVALID,
        m_axi_V_ARREADY => m_axi_V_ARREADY,
        m_axi_V_ARADDR => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARADDR,
        m_axi_V_ARID => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARID,
        m_axi_V_ARLEN => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARLEN,
        m_axi_V_ARSIZE => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARSIZE,
        m_axi_V_ARBURST => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARBURST,
        m_axi_V_ARLOCK => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARLOCK,
        m_axi_V_ARCACHE => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARCACHE,
        m_axi_V_ARPROT => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARPROT,
        m_axi_V_ARQOS => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARQOS,
        m_axi_V_ARREGION => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARREGION,
        m_axi_V_ARUSER => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARUSER,
        m_axi_V_RVALID => m_axi_V_RVALID,
        m_axi_V_RREADY => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_RREADY,
        m_axi_V_RDATA => m_axi_V_RDATA,
        m_axi_V_RLAST => m_axi_V_RLAST,
        m_axi_V_RID => m_axi_V_RID,
        m_axi_V_RFIFONUM => m_axi_V_RFIFONUM,
        m_axi_V_RUSER => m_axi_V_RUSER,
        m_axi_V_RRESP => m_axi_V_RRESP,
        m_axi_V_BVALID => ap_const_logic_0,
        m_axi_V_BREADY => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_BREADY,
        m_axi_V_BRESP => ap_const_lv2_0,
        m_axi_V_BID => ap_const_lv1_0,
        m_axi_V_BUSER => ap_const_lv1_0,
        W_ddr_tile => in_w,
        out_w1_din => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_out_w1_din,
        out_w1_num_data_valid => out_w_num_data_valid,
        out_w1_fifo_cap => out_w_fifo_cap,
        out_w1_full_n => out_w_full_n,
        out_w1_write => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_out_w1_write);

    Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0 : component ViT_Block_Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_ap_start,
        ap_done => Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_ap_done,
        ap_continue => Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_ap_continue,
        ap_idle => Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_ap_idle,
        ap_ready => Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_ap_ready,
        V_in7_dout => V_in7_dout,
        V_in7_num_data_valid => ap_const_lv13_0,
        V_in7_fifo_cap => ap_const_lv13_0,
        V_in7_empty_n => V_in7_empty_n,
        V_in7_read => Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_V_in7_read,
        v_lin3_din => Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_v_lin3_din,
        v_lin3_num_data_valid => ap_const_lv2_0,
        v_lin3_fifo_cap => ap_const_lv2_0,
        v_lin3_full_n => v_lin3_full_n,
        v_lin3_write => Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_v_lin3_write,
        out_w1_dout => out_w_dout,
        out_w1_num_data_valid => out_w_num_data_valid,
        out_w1_fifo_cap => out_w_fifo_cap,
        out_w1_empty_n => out_w_empty_n,
        out_w1_read => Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_out_w1_read);

    out_w_U : component ViT_Block_fifo_w8_d64_S_x2
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_out_w1_din,
        if_full_n => out_w_full_n,
        if_write => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_out_w1_write,
        if_dout => out_w_dout,
        if_num_data_valid => out_w_num_data_valid,
        if_fifo_cap => out_w_fifo_cap,
        if_empty_n => out_w_empty_n,
        if_read => Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_out_w1_read);

    start_for_Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_U : component ViT_Block_start_for_Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_din,
        if_full_n => start_for_Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_full_n,
        if_write => WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_start_write,
        if_dout => start_for_Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_dout,
        if_empty_n => start_for_Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_empty_n,
        if_read => Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_ap_ready);





    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_ap_continue <= ap_continue;
    Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_ap_start <= start_for_Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_empty_n;
    V_in7_read <= Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_V_in7_read;
    WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_ap_continue <= ap_const_logic_1;
    WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_ap_start <= real_start;
    ap_done <= Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_ap_done;
    ap_idle <= (WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_ap_idle and Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_ap_idle);
    ap_ready <= WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_ap_ready;
    ap_sync_ready <= WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_ap_ready;
    internal_ap_ready <= ap_sync_ready;
    m_axi_V_ARADDR <= WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARADDR;
    m_axi_V_ARBURST <= WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARBURST;
    m_axi_V_ARCACHE <= WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARCACHE;
    m_axi_V_ARID <= WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARID;
    m_axi_V_ARLEN <= WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARLEN;
    m_axi_V_ARLOCK <= WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARLOCK;
    m_axi_V_ARPROT <= WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARPROT;
    m_axi_V_ARQOS <= WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARQOS;
    m_axi_V_ARREGION <= WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARREGION;
    m_axi_V_ARSIZE <= WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARSIZE;
    m_axi_V_ARUSER <= WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARUSER;
    m_axi_V_ARVALID <= WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_ARVALID;
    m_axi_V_AWADDR <= ap_const_lv64_0;
    m_axi_V_AWBURST <= ap_const_lv2_0;
    m_axi_V_AWCACHE <= ap_const_lv4_0;
    m_axi_V_AWID <= ap_const_lv1_0;
    m_axi_V_AWLEN <= ap_const_lv32_0;
    m_axi_V_AWLOCK <= ap_const_lv2_0;
    m_axi_V_AWPROT <= ap_const_lv3_0;
    m_axi_V_AWQOS <= ap_const_lv4_0;
    m_axi_V_AWREGION <= ap_const_lv4_0;
    m_axi_V_AWSIZE <= ap_const_lv3_0;
    m_axi_V_AWUSER <= ap_const_lv1_0;
    m_axi_V_AWVALID <= ap_const_logic_0;
    m_axi_V_BREADY <= ap_const_logic_0;
    m_axi_V_RREADY <= WeightTiledStreaming_3_17_16_16_1_1_1_1_1_1_ap_int_8_9_U0_m_axi_V_RREADY;
    m_axi_V_WDATA <= ap_const_lv8_0;
    m_axi_V_WID <= ap_const_lv1_0;
    m_axi_V_WLAST <= ap_const_logic_0;
    m_axi_V_WSTRB <= ap_const_lv1_0;
    m_axi_V_WUSER <= ap_const_lv1_0;
    m_axi_V_WVALID <= ap_const_logic_0;

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_for_Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    v_lin3_din <= Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_v_lin3_din;
    v_lin3_write <= Linear_Layer_17_16_16_1_1_1_1_1_1_409_16_0_ap_int_ap_int_ap_int_U0_v_lin3_write;
end behav;
