-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ViT_Block_FC1_tiled_oc_2 is
port (
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    m_axi_gmem0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RFIFONUM : IN STD_LOGIC_VECTOR (12 downto 0);
    m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_w : IN STD_LOGIC_VECTOR (63 downto 0);
    norm_out_113_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    norm_out_113_empty_n : IN STD_LOGIC;
    norm_out_113_read : OUT STD_LOGIC;
    fc11_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    fc11_full_n : IN STD_LOGIC;
    fc11_write : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    in_w_ap_vld : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of ViT_Block_FC1_tiled_oc_2 is 
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal internal_ap_ready : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_ap_start : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_ap_done : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_ap_continue : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_ap_idle : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_ap_ready : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_start_out : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_start_write : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWVALID : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_WVALID : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_WDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_WSTRB : STD_LOGIC_VECTOR (0 downto 0);
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_WLAST : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARVALID : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_RREADY : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_BREADY : STD_LOGIC;
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_out_w1_din : STD_LOGIC_VECTOR (7 downto 0);
    signal WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_out_w1_write : STD_LOGIC;
    signal Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_ap_start : STD_LOGIC;
    signal Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_ap_done : STD_LOGIC;
    signal Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_ap_continue : STD_LOGIC;
    signal Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_ap_idle : STD_LOGIC;
    signal Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_ap_ready : STD_LOGIC;
    signal Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_norm_out_113_read : STD_LOGIC;
    signal Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_fc11_din : STD_LOGIC_VECTOR (7 downto 0);
    signal Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_fc11_write : STD_LOGIC;
    signal Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_out_w1_read : STD_LOGIC;
    signal out_w_full_n : STD_LOGIC;
    signal out_w_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal out_w_num_data_valid : STD_LOGIC_VECTOR (6 downto 0);
    signal out_w_fifo_cap : STD_LOGIC_VECTOR (6 downto 0);
    signal out_w_empty_n : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal start_for_Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_full_n : STD_LOGIC;
    signal start_for_Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_empty_n : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ViT_Block_WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        m_axi_gmem0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem0_AWREADY : IN STD_LOGIC;
        m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_WVALID : OUT STD_LOGIC;
        m_axi_gmem0_WREADY : IN STD_LOGIC;
        m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_WLAST : OUT STD_LOGIC;
        m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem0_ARREADY : IN STD_LOGIC;
        m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_RVALID : IN STD_LOGIC;
        m_axi_gmem0_RREADY : OUT STD_LOGIC;
        m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem0_RLAST : IN STD_LOGIC;
        m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_RFIFONUM : IN STD_LOGIC_VECTOR (12 downto 0);
        m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_BVALID : IN STD_LOGIC;
        m_axi_gmem0_BREADY : OUT STD_LOGIC;
        m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        W_ddr_tile : IN STD_LOGIC_VECTOR (63 downto 0);
        out_w1_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        out_w1_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        out_w1_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        out_w1_full_n : IN STD_LOGIC;
        out_w1_write : OUT STD_LOGIC );
    end component;


    component ViT_Block_Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        norm_out_113_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        norm_out_113_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        norm_out_113_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        norm_out_113_empty_n : IN STD_LOGIC;
        norm_out_113_read : OUT STD_LOGIC;
        fc11_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        fc11_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        fc11_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        fc11_full_n : IN STD_LOGIC;
        fc11_write : OUT STD_LOGIC;
        out_w1_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        out_w1_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        out_w1_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        out_w1_empty_n : IN STD_LOGIC;
        out_w1_read : OUT STD_LOGIC );
    end component;


    component ViT_Block_fifo_w8_d64_S_x6 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_num_data_valid : OUT STD_LOGIC_VECTOR (6 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (6 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component ViT_Block_start_for_Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0 : component ViT_Block_WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_ap_start,
        start_full_n => start_for_Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_full_n,
        ap_done => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_ap_done,
        ap_continue => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_ap_continue,
        ap_idle => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_ap_idle,
        ap_ready => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_ap_ready,
        start_out => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_start_out,
        start_write => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_start_write,
        m_axi_gmem0_AWVALID => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY => ap_const_logic_0,
        m_axi_gmem0_AWADDR => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY => ap_const_logic_0,
        m_axi_gmem0_WDATA => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_WLAST,
        m_axi_gmem0_WID => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_WID,
        m_axi_gmem0_WUSER => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY => m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID => m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA => m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST => m_axi_gmem0_RLAST,
        m_axi_gmem0_RID => m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM => m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER => m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP => m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID => ap_const_logic_0,
        m_axi_gmem0_BREADY => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP => ap_const_lv2_0,
        m_axi_gmem0_BID => ap_const_lv1_0,
        m_axi_gmem0_BUSER => ap_const_lv1_0,
        W_ddr_tile => in_w,
        out_w1_din => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_out_w1_din,
        out_w1_num_data_valid => out_w_num_data_valid,
        out_w1_fifo_cap => out_w_fifo_cap,
        out_w1_full_n => out_w_full_n,
        out_w1_write => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_out_w1_write);

    Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0 : component ViT_Block_Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_ap_start,
        ap_done => Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_ap_done,
        ap_continue => Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_ap_continue,
        ap_idle => Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_ap_idle,
        ap_ready => Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_ap_ready,
        norm_out_113_dout => norm_out_113_dout,
        norm_out_113_num_data_valid => ap_const_lv2_0,
        norm_out_113_fifo_cap => ap_const_lv2_0,
        norm_out_113_empty_n => norm_out_113_empty_n,
        norm_out_113_read => Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_norm_out_113_read,
        fc11_din => Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_fc11_din,
        fc11_num_data_valid => ap_const_lv7_0,
        fc11_fifo_cap => ap_const_lv7_0,
        fc11_full_n => fc11_full_n,
        fc11_write => Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_fc11_write,
        out_w1_dout => out_w_dout,
        out_w1_num_data_valid => out_w_num_data_valid,
        out_w1_fifo_cap => out_w_fifo_cap,
        out_w1_empty_n => out_w_empty_n,
        out_w1_read => Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_out_w1_read);

    out_w_U : component ViT_Block_fifo_w8_d64_S_x6
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_out_w1_din,
        if_full_n => out_w_full_n,
        if_write => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_out_w1_write,
        if_dout => out_w_dout,
        if_num_data_valid => out_w_num_data_valid,
        if_fifo_cap => out_w_fifo_cap,
        if_empty_n => out_w_empty_n,
        if_read => Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_out_w1_read);

    start_for_Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_U : component ViT_Block_start_for_Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_din,
        if_full_n => start_for_Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_full_n,
        if_write => WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_start_write,
        if_dout => start_for_Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_dout,
        if_empty_n => start_for_Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_empty_n,
        if_read => Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_ap_ready);





    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_ap_continue <= ap_continue;
    Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_ap_start <= start_for_Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_empty_n;
    WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_ap_continue <= ap_const_logic_1;
    WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_ap_start <= real_start;
    ap_done <= Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_ap_done;
    ap_idle <= (WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_ap_idle and Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_ap_idle);
    ap_ready <= WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_ap_ready;
    ap_sync_ready <= WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_ap_ready;
    fc11_din <= Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_fc11_din;
    fc11_write <= Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_fc11_write;
    internal_ap_ready <= ap_sync_ready;
    m_axi_gmem0_ARADDR <= WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARADDR;
    m_axi_gmem0_ARBURST <= WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARBURST;
    m_axi_gmem0_ARCACHE <= WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARCACHE;
    m_axi_gmem0_ARID <= WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARID;
    m_axi_gmem0_ARLEN <= WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARLEN;
    m_axi_gmem0_ARLOCK <= WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARLOCK;
    m_axi_gmem0_ARPROT <= WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARPROT;
    m_axi_gmem0_ARQOS <= WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARQOS;
    m_axi_gmem0_ARREGION <= WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARREGION;
    m_axi_gmem0_ARSIZE <= WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARSIZE;
    m_axi_gmem0_ARUSER <= WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARUSER;
    m_axi_gmem0_ARVALID <= WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARVALID;
    m_axi_gmem0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem0_AWID <= ap_const_lv1_0;
    m_axi_gmem0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem0_AWVALID <= ap_const_logic_0;
    m_axi_gmem0_BREADY <= ap_const_logic_0;
    m_axi_gmem0_RREADY <= WeightTiledStreaming_3_17_16_64_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_RREADY;
    m_axi_gmem0_WDATA <= ap_const_lv8_0;
    m_axi_gmem0_WID <= ap_const_lv1_0;
    m_axi_gmem0_WLAST <= ap_const_logic_0;
    m_axi_gmem0_WSTRB <= ap_const_lv1_0;
    m_axi_gmem0_WUSER <= ap_const_lv1_0;
    m_axi_gmem0_WVALID <= ap_const_logic_0;
    norm_out_113_read <= Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_norm_out_113_read;

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_for_Linear_Layer_17_16_64_1_1_1_1_1_1_291_16_0_ap_int_ap_int_ap_int_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
