-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ViT_Block_MatMul_QK_tiled_Pipeline_VITIS_LOOP_1701_8 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    A_0_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    A_0_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    A_0_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    A_0_full_n : IN STD_LOGIC;
    A_0_write : OUT STD_LOGIC;
    tile_Q_V_0_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    tile_Q_V_0_ce0 : OUT STD_LOGIC;
    tile_Q_V_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    tile_Q_V_0_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    tile_Q_V_0_ce1 : OUT STD_LOGIC;
    tile_Q_V_0_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    tile_Q_V_0_address2 : OUT STD_LOGIC_VECTOR (2 downto 0);
    tile_Q_V_0_ce2 : OUT STD_LOGIC;
    tile_Q_V_0_q2 : IN STD_LOGIC_VECTOR (7 downto 0);
    tile_Q_V_0_address3 : OUT STD_LOGIC_VECTOR (2 downto 0);
    tile_Q_V_0_ce3 : OUT STD_LOGIC;
    tile_Q_V_0_q3 : IN STD_LOGIC_VECTOR (7 downto 0);
    tile_Q_V_0_address4 : OUT STD_LOGIC_VECTOR (2 downto 0);
    tile_Q_V_0_ce4 : OUT STD_LOGIC;
    tile_Q_V_0_q4 : IN STD_LOGIC_VECTOR (7 downto 0);
    tile_Q_V_0_address5 : OUT STD_LOGIC_VECTOR (2 downto 0);
    tile_Q_V_0_ce5 : OUT STD_LOGIC;
    tile_Q_V_0_q5 : IN STD_LOGIC_VECTOR (7 downto 0);
    tile_Q_V_0_address6 : OUT STD_LOGIC_VECTOR (2 downto 0);
    tile_Q_V_0_ce6 : OUT STD_LOGIC;
    tile_Q_V_0_q6 : IN STD_LOGIC_VECTOR (7 downto 0);
    tile_Q_V_0_address7 : OUT STD_LOGIC_VECTOR (2 downto 0);
    tile_Q_V_0_ce7 : OUT STD_LOGIC;
    tile_Q_V_0_q7 : IN STD_LOGIC_VECTOR (7 downto 0);
    buff_K_V_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    buff_K_V_ce0 : OUT STD_LOGIC;
    buff_K_V_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    buff_K_V_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    buff_K_V_ce1 : OUT STD_LOGIC;
    buff_K_V_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    buff_K_V_address2 : OUT STD_LOGIC_VECTOR (7 downto 0);
    buff_K_V_ce2 : OUT STD_LOGIC;
    buff_K_V_q2 : IN STD_LOGIC_VECTOR (7 downto 0);
    buff_K_V_address3 : OUT STD_LOGIC_VECTOR (7 downto 0);
    buff_K_V_ce3 : OUT STD_LOGIC;
    buff_K_V_q3 : IN STD_LOGIC_VECTOR (7 downto 0);
    buff_K_V_address4 : OUT STD_LOGIC_VECTOR (7 downto 0);
    buff_K_V_ce4 : OUT STD_LOGIC;
    buff_K_V_q4 : IN STD_LOGIC_VECTOR (7 downto 0);
    buff_K_V_address5 : OUT STD_LOGIC_VECTOR (7 downto 0);
    buff_K_V_ce5 : OUT STD_LOGIC;
    buff_K_V_q5 : IN STD_LOGIC_VECTOR (7 downto 0);
    buff_K_V_address6 : OUT STD_LOGIC_VECTOR (7 downto 0);
    buff_K_V_ce6 : OUT STD_LOGIC;
    buff_K_V_q6 : IN STD_LOGIC_VECTOR (7 downto 0);
    buff_K_V_address7 : OUT STD_LOGIC_VECTOR (7 downto 0);
    buff_K_V_ce7 : OUT STD_LOGIC;
    buff_K_V_q7 : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of ViT_Block_MatMul_QK_tiled_Pipeline_VITIS_LOOP_1701_8 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv64_7 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000111";
    constant ap_const_lv64_6 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000110";
    constant ap_const_lv64_5 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000101";
    constant ap_const_lv64_4 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv64_3 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_11 : STD_LOGIC_VECTOR (4 downto 0) := "10001";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_const_lv8_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000011";
    constant ap_const_lv8_4 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_const_lv8_5 : STD_LOGIC_VECTOR (7 downto 0) := "00000101";
    constant ap_const_lv8_6 : STD_LOGIC_VECTOR (7 downto 0) := "00000110";
    constant ap_const_lv8_7 : STD_LOGIC_VECTOR (7 downto 0) := "00000111";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv27_8000 : STD_LOGIC_VECTOR (26 downto 0) := "000000000001000000000000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv12_F80 : STD_LOGIC_VECTOR (11 downto 0) := "111110000000";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv30_25F : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000001001011111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln1701_fu_321_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal A_0_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal buff_K_V_load_reg_781 : STD_LOGIC_VECTOR (7 downto 0);
    signal buff_K_V_load_reg_781_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tile_Q_V_0_load_reg_786 : STD_LOGIC_VECTOR (7 downto 0);
    signal tile_Q_V_0_load_reg_786_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal buff_K_V_load_1_reg_791 : STD_LOGIC_VECTOR (7 downto 0);
    signal tile_Q_V_0_load_1_reg_796 : STD_LOGIC_VECTOR (7 downto 0);
    signal buff_K_V_load_3_reg_811 : STD_LOGIC_VECTOR (7 downto 0);
    signal buff_K_V_load_3_reg_811_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tile_Q_V_0_load_3_reg_816 : STD_LOGIC_VECTOR (7 downto 0);
    signal tile_Q_V_0_load_3_reg_816_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal buff_K_V_load_4_reg_821 : STD_LOGIC_VECTOR (7 downto 0);
    signal tile_Q_V_0_load_4_reg_826 : STD_LOGIC_VECTOR (7 downto 0);
    signal buff_K_V_load_5_reg_831 : STD_LOGIC_VECTOR (7 downto 0);
    signal buff_K_V_load_5_reg_831_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tile_Q_V_0_load_5_reg_836 : STD_LOGIC_VECTOR (7 downto 0);
    signal tile_Q_V_0_load_5_reg_836_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal buff_K_V_load_7_reg_851 : STD_LOGIC_VECTOR (7 downto 0);
    signal buff_K_V_load_7_reg_851_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal buff_K_V_load_7_reg_851_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal buff_K_V_load_7_reg_851_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal buff_K_V_load_7_reg_851_pp0_iter5_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tile_Q_V_0_load_7_reg_856 : STD_LOGIC_VECTOR (7 downto 0);
    signal tile_Q_V_0_load_7_reg_856_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tile_Q_V_0_load_7_reg_856_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tile_Q_V_0_load_7_reg_856_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tile_Q_V_0_load_7_reg_856_pp0_iter5_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_638_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_646_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_663_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln840_19_reg_916 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_32_cast_fu_341_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_33_cast_fu_352_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_34_cast_fu_363_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_35_cast_fu_374_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_36_cast_fu_385_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_37_cast_fu_396_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_38_cast_fu_407_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_39_cast_fu_418_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal token_j_fu_100 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln1701_fu_327_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_n : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_s_fu_333_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_33_fu_346_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_34_fu_357_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_35_fu_368_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_36_fu_379_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_37_fu_390_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_38_fu_401_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_39_fu_412_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1494_fu_462_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln1494_5_fu_484_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_654_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln840_4_fu_497_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_671_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln840_20_fu_500_p2 : STD_LOGIC_VECTOR (17 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of add_ln840_20_fu_500_p2 : signal is "no";
    signal mul_ln1494_7_fu_515_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_680_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal trunc_ln1417_fu_532_p1 : STD_LOGIC_VECTOR (26 downto 0);
    signal ret_V_fu_535_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal trunc_ln_fu_541_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal ret_V_7_fu_555_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal trunc_ln3_fu_561_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln1420_fu_571_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_fu_525_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal rq_V_fu_575_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln1409_fu_551_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal rq_V_6_fu_581_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_7_fu_589_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln1035_fu_599_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1027_fu_605_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1444_fu_623_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1444_fu_615_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln1444_fu_611_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_680_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_638_ce : STD_LOGIC;
    signal grp_fu_646_ce : STD_LOGIC;
    signal grp_fu_654_ce : STD_LOGIC;
    signal grp_fu_663_ce : STD_LOGIC;
    signal grp_fu_671_ce : STD_LOGIC;
    signal grp_fu_680_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ViT_Block_mul_8s_8s_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component ViT_Block_mac_muladd_8s_8s_16s_17_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component ViT_Block_mac_muladd_8s_8s_17s_17_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (16 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component ViT_Block_mac_muladd_8s_8s_17s_18_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (16 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;


    component ViT_Block_am_addmul_18s_16s_10ns_30_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;


    component ViT_Block_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_8s_8s_16_1_1_U158 : component ViT_Block_mul_8s_8s_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => tile_Q_V_0_load_reg_786_pp0_iter2_reg,
        din1 => buff_K_V_load_reg_781_pp0_iter2_reg,
        dout => mul_ln1494_fu_462_p2);

    mul_8s_8s_16_1_1_U159 : component ViT_Block_mul_8s_8s_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => tile_Q_V_0_load_5_reg_836_pp0_iter2_reg,
        din1 => buff_K_V_load_5_reg_831_pp0_iter2_reg,
        dout => mul_ln1494_5_fu_484_p2);

    mul_8s_8s_16_1_1_U160 : component ViT_Block_mul_8s_8s_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => tile_Q_V_0_load_7_reg_856_pp0_iter5_reg,
        din1 => buff_K_V_load_7_reg_851_pp0_iter5_reg,
        dout => mul_ln1494_7_fu_515_p2);

    mac_muladd_8s_8s_16s_17_4_1_U161 : component ViT_Block_mac_muladd_8s_8s_16s_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tile_Q_V_0_q5,
        din1 => buff_K_V_q5,
        din2 => mul_ln1494_fu_462_p2,
        ce => grp_fu_638_ce,
        dout => grp_fu_638_p3);

    mac_muladd_8s_8s_16s_17_4_1_U162 : component ViT_Block_mac_muladd_8s_8s_16s_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tile_Q_V_0_q1,
        din1 => buff_K_V_q1,
        din2 => mul_ln1494_5_fu_484_p2,
        ce => grp_fu_646_ce,
        dout => grp_fu_646_p3);

    mac_muladd_8s_8s_17s_17_4_1_U163 : component ViT_Block_mac_muladd_8s_8s_17s_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 17,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tile_Q_V_0_load_1_reg_796,
        din1 => buff_K_V_load_1_reg_791,
        din2 => grp_fu_638_p3,
        ce => grp_fu_654_ce,
        dout => grp_fu_654_p3);

    mac_muladd_8s_8s_17s_17_4_1_U164 : component ViT_Block_mac_muladd_8s_8s_17s_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 17,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tile_Q_V_0_load_4_reg_826,
        din1 => buff_K_V_load_4_reg_821,
        din2 => grp_fu_646_p3,
        ce => grp_fu_663_ce,
        dout => grp_fu_663_p3);

    mac_muladd_8s_8s_17s_18_4_1_U165 : component ViT_Block_mac_muladd_8s_8s_17s_18_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 17,
        dout_WIDTH => 18)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tile_Q_V_0_load_3_reg_816_pp0_iter2_reg,
        din1 => buff_K_V_load_3_reg_811_pp0_iter2_reg,
        din2 => grp_fu_654_p3,
        ce => grp_fu_671_ce,
        dout => grp_fu_671_p3);

    am_addmul_18s_16s_10ns_30_4_1_U166 : component ViT_Block_am_addmul_18s_16s_10ns_30_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 18,
        din1_WIDTH => 16,
        din2_WIDTH => 10,
        dout_WIDTH => 30)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => add_ln840_20_fu_500_p2,
        din1 => mul_ln1494_7_fu_515_p2,
        din2 => grp_fu_680_p2,
        ce => grp_fu_680_ce,
        dout => grp_fu_680_p3);

    flow_control_loop_pipe_sequential_init_U : component ViT_Block_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    token_j_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln1701_fu_321_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    token_j_fu_100 <= add_ln1701_fu_327_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    token_j_fu_100 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then
                add_ln840_19_reg_916 <= grp_fu_663_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                buff_K_V_load_3_reg_811_pp0_iter2_reg <= buff_K_V_load_3_reg_811;
                buff_K_V_load_5_reg_831_pp0_iter2_reg <= buff_K_V_load_5_reg_831;
                buff_K_V_load_7_reg_851_pp0_iter2_reg <= buff_K_V_load_7_reg_851;
                buff_K_V_load_7_reg_851_pp0_iter3_reg <= buff_K_V_load_7_reg_851_pp0_iter2_reg;
                buff_K_V_load_7_reg_851_pp0_iter4_reg <= buff_K_V_load_7_reg_851_pp0_iter3_reg;
                buff_K_V_load_7_reg_851_pp0_iter5_reg <= buff_K_V_load_7_reg_851_pp0_iter4_reg;
                buff_K_V_load_reg_781_pp0_iter2_reg <= buff_K_V_load_reg_781;
                tile_Q_V_0_load_3_reg_816_pp0_iter2_reg <= tile_Q_V_0_load_3_reg_816;
                tile_Q_V_0_load_5_reg_836_pp0_iter2_reg <= tile_Q_V_0_load_5_reg_836;
                tile_Q_V_0_load_7_reg_856_pp0_iter2_reg <= tile_Q_V_0_load_7_reg_856;
                tile_Q_V_0_load_7_reg_856_pp0_iter3_reg <= tile_Q_V_0_load_7_reg_856_pp0_iter2_reg;
                tile_Q_V_0_load_7_reg_856_pp0_iter4_reg <= tile_Q_V_0_load_7_reg_856_pp0_iter3_reg;
                tile_Q_V_0_load_7_reg_856_pp0_iter5_reg <= tile_Q_V_0_load_7_reg_856_pp0_iter4_reg;
                tile_Q_V_0_load_reg_786_pp0_iter2_reg <= tile_Q_V_0_load_reg_786;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                buff_K_V_load_1_reg_791 <= buff_K_V_q6;
                buff_K_V_load_3_reg_811 <= buff_K_V_q4;
                buff_K_V_load_4_reg_821 <= buff_K_V_q3;
                buff_K_V_load_5_reg_831 <= buff_K_V_q2;
                buff_K_V_load_7_reg_851 <= buff_K_V_q0;
                buff_K_V_load_reg_781 <= buff_K_V_q7;
                tile_Q_V_0_load_1_reg_796 <= tile_Q_V_0_q6;
                tile_Q_V_0_load_3_reg_816 <= tile_Q_V_0_q4;
                tile_Q_V_0_load_4_reg_826 <= tile_Q_V_0_q3;
                tile_Q_V_0_load_5_reg_836 <= tile_Q_V_0_q2;
                tile_Q_V_0_load_7_reg_856 <= tile_Q_V_0_q0;
                tile_Q_V_0_load_reg_786 <= tile_Q_V_0_q7;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    A_0_blk_n_assign_proc : process(ap_enable_reg_pp0_iter9, A_0_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then 
            A_0_blk_n <= A_0_full_n;
        else 
            A_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    A_0_din <= 
        select_ln1444_fu_615_p3 when (or_ln1444_fu_623_p2(0) = '1') else 
        trunc_ln1444_fu_611_p1;

    A_0_write_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then 
            A_0_write <= ap_const_logic_1;
        else 
            A_0_write <= ap_const_logic_0;
        end if; 
    end process;

    add_ln1701_fu_327_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_n) + unsigned(ap_const_lv5_1));
    add_ln840_20_fu_500_p2 <= std_logic_vector(signed(sext_ln840_4_fu_497_p1) + signed(grp_fu_671_p3));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter9, A_0_full_n)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_logic_0 = A_0_full_n));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter9, A_0_full_n)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_logic_0 = A_0_full_n));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter9, A_0_full_n)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_logic_0 = A_0_full_n));
    end process;


    ap_block_state10_pp0_stage0_iter9_assign_proc : process(A_0_full_n)
    begin
                ap_block_state10_pp0_stage0_iter9 <= (ap_const_logic_0 = A_0_full_n);
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln1701_fu_321_p2)
    begin
        if (((icmp_ln1701_fu_321_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter8_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, token_j_fu_100, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_n <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_n <= token_j_fu_100;
        end if; 
    end process;

    buff_K_V_address0 <= tmp_39_cast_fu_418_p1(8 - 1 downto 0);
    buff_K_V_address1 <= tmp_38_cast_fu_407_p1(8 - 1 downto 0);
    buff_K_V_address2 <= tmp_37_cast_fu_396_p1(8 - 1 downto 0);
    buff_K_V_address3 <= tmp_36_cast_fu_385_p1(8 - 1 downto 0);
    buff_K_V_address4 <= tmp_35_cast_fu_374_p1(8 - 1 downto 0);
    buff_K_V_address5 <= tmp_34_cast_fu_363_p1(8 - 1 downto 0);
    buff_K_V_address6 <= tmp_33_cast_fu_352_p1(8 - 1 downto 0);
    buff_K_V_address7 <= tmp_32_cast_fu_341_p1(8 - 1 downto 0);

    buff_K_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buff_K_V_ce0 <= ap_const_logic_1;
        else 
            buff_K_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buff_K_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buff_K_V_ce1 <= ap_const_logic_1;
        else 
            buff_K_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buff_K_V_ce2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buff_K_V_ce2 <= ap_const_logic_1;
        else 
            buff_K_V_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    buff_K_V_ce3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buff_K_V_ce3 <= ap_const_logic_1;
        else 
            buff_K_V_ce3 <= ap_const_logic_0;
        end if; 
    end process;


    buff_K_V_ce4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buff_K_V_ce4 <= ap_const_logic_1;
        else 
            buff_K_V_ce4 <= ap_const_logic_0;
        end if; 
    end process;


    buff_K_V_ce5_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buff_K_V_ce5 <= ap_const_logic_1;
        else 
            buff_K_V_ce5 <= ap_const_logic_0;
        end if; 
    end process;


    buff_K_V_ce6_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buff_K_V_ce6 <= ap_const_logic_1;
        else 
            buff_K_V_ce6 <= ap_const_logic_0;
        end if; 
    end process;


    buff_K_V_ce7_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            buff_K_V_ce7 <= ap_const_logic_1;
        else 
            buff_K_V_ce7 <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_638_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_638_ce <= ap_const_logic_1;
        else 
            grp_fu_638_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_646_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_646_ce <= ap_const_logic_1;
        else 
            grp_fu_646_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_654_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_654_ce <= ap_const_logic_1;
        else 
            grp_fu_654_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_663_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_663_ce <= ap_const_logic_1;
        else 
            grp_fu_663_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_671_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_671_ce <= ap_const_logic_1;
        else 
            grp_fu_671_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_680_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_680_ce <= ap_const_logic_1;
        else 
            grp_fu_680_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_680_p2 <= ap_const_lv30_25F(10 - 1 downto 0);
    icmp_ln1027_fu_605_p2 <= "1" when (signed(rq_V_6_fu_581_p3) < signed(ap_const_lv12_F80)) else "0";
    icmp_ln1035_fu_599_p2 <= "1" when (signed(tmp_7_fu_589_p4) > signed(ap_const_lv5_0)) else "0";
    icmp_ln1701_fu_321_p2 <= "1" when (ap_sig_allocacmp_n = ap_const_lv5_11) else "0";
    or_ln1444_fu_623_p2 <= (icmp_ln1035_fu_599_p2 or icmp_ln1027_fu_605_p2);
    ret_V_7_fu_555_p2 <= std_logic_vector(unsigned(ap_const_lv27_8000) - unsigned(trunc_ln1417_fu_532_p1));
    ret_V_fu_535_p2 <= std_logic_vector(unsigned(trunc_ln1417_fu_532_p1) + unsigned(ap_const_lv27_8000));
    rq_V_6_fu_581_p3 <= 
        rq_V_fu_575_p2 when (tmp_fu_525_p3(0) = '1') else 
        zext_ln1409_fu_551_p1;
    rq_V_fu_575_p2 <= std_logic_vector(unsigned(ap_const_lv12_0) - unsigned(zext_ln1420_fu_571_p1));
    select_ln1444_fu_615_p3 <= 
        ap_const_lv8_7F when (icmp_ln1035_fu_599_p2(0) = '1') else 
        ap_const_lv8_80;
        sext_ln840_4_fu_497_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln840_19_reg_916),18));

    tile_Q_V_0_address0 <= ap_const_lv64_7(3 - 1 downto 0);
    tile_Q_V_0_address1 <= ap_const_lv64_6(3 - 1 downto 0);
    tile_Q_V_0_address2 <= ap_const_lv64_5(3 - 1 downto 0);
    tile_Q_V_0_address3 <= ap_const_lv64_4(3 - 1 downto 0);
    tile_Q_V_0_address4 <= ap_const_lv64_3(3 - 1 downto 0);
    tile_Q_V_0_address5 <= ap_const_lv64_2(3 - 1 downto 0);
    tile_Q_V_0_address6 <= ap_const_lv64_1(3 - 1 downto 0);
    tile_Q_V_0_address7 <= ap_const_lv64_0(3 - 1 downto 0);

    tile_Q_V_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tile_Q_V_0_ce0 <= ap_const_logic_1;
        else 
            tile_Q_V_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    tile_Q_V_0_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tile_Q_V_0_ce1 <= ap_const_logic_1;
        else 
            tile_Q_V_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    tile_Q_V_0_ce2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tile_Q_V_0_ce2 <= ap_const_logic_1;
        else 
            tile_Q_V_0_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    tile_Q_V_0_ce3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tile_Q_V_0_ce3 <= ap_const_logic_1;
        else 
            tile_Q_V_0_ce3 <= ap_const_logic_0;
        end if; 
    end process;


    tile_Q_V_0_ce4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tile_Q_V_0_ce4 <= ap_const_logic_1;
        else 
            tile_Q_V_0_ce4 <= ap_const_logic_0;
        end if; 
    end process;


    tile_Q_V_0_ce5_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tile_Q_V_0_ce5 <= ap_const_logic_1;
        else 
            tile_Q_V_0_ce5 <= ap_const_logic_0;
        end if; 
    end process;


    tile_Q_V_0_ce6_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tile_Q_V_0_ce6 <= ap_const_logic_1;
        else 
            tile_Q_V_0_ce6 <= ap_const_logic_0;
        end if; 
    end process;


    tile_Q_V_0_ce7_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            tile_Q_V_0_ce7 <= ap_const_logic_1;
        else 
            tile_Q_V_0_ce7 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_32_cast_fu_341_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_333_p3),64));
    tmp_33_cast_fu_352_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_33_fu_346_p2),64));
    tmp_33_fu_346_p2 <= (tmp_s_fu_333_p3 or ap_const_lv8_1);
    tmp_34_cast_fu_363_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_34_fu_357_p2),64));
    tmp_34_fu_357_p2 <= (tmp_s_fu_333_p3 or ap_const_lv8_2);
    tmp_35_cast_fu_374_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_35_fu_368_p2),64));
    tmp_35_fu_368_p2 <= (tmp_s_fu_333_p3 or ap_const_lv8_3);
    tmp_36_cast_fu_385_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_36_fu_379_p2),64));
    tmp_36_fu_379_p2 <= (tmp_s_fu_333_p3 or ap_const_lv8_4);
    tmp_37_cast_fu_396_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_37_fu_390_p2),64));
    tmp_37_fu_390_p2 <= (tmp_s_fu_333_p3 or ap_const_lv8_5);
    tmp_38_cast_fu_407_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_38_fu_401_p2),64));
    tmp_38_fu_401_p2 <= (tmp_s_fu_333_p3 or ap_const_lv8_6);
    tmp_39_cast_fu_418_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_39_fu_412_p2),64));
    tmp_39_fu_412_p2 <= (tmp_s_fu_333_p3 or ap_const_lv8_7);
    tmp_7_fu_589_p4 <= rq_V_6_fu_581_p3(11 downto 7);
    tmp_fu_525_p3 <= grp_fu_680_p3(29 downto 29);
    tmp_s_fu_333_p3 <= (ap_sig_allocacmp_n & ap_const_lv3_0);
    trunc_ln1417_fu_532_p1 <= grp_fu_680_p3(27 - 1 downto 0);
    trunc_ln1444_fu_611_p1 <= rq_V_6_fu_581_p3(8 - 1 downto 0);
    trunc_ln3_fu_561_p4 <= ret_V_7_fu_555_p2(26 downto 16);
    trunc_ln_fu_541_p4 <= ret_V_fu_535_p2(26 downto 16);
    zext_ln1409_fu_551_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln_fu_541_p4),12));
    zext_ln1420_fu_571_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln3_fu_561_p4),12));
end behav;
