-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ViT_Block_WeightTiledStreaming_3_17_192_192_1_1_1_1_1_1_ap_int_8_17 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    m_axi_V_AWVALID : OUT STD_LOGIC;
    m_axi_V_AWREADY : IN STD_LOGIC;
    m_axi_V_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_V_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_V_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_V_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_V_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_V_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_V_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_V_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_V_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_V_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_V_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_V_WVALID : OUT STD_LOGIC;
    m_axi_V_WREADY : IN STD_LOGIC;
    m_axi_V_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_V_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_V_WLAST : OUT STD_LOGIC;
    m_axi_V_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_V_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_V_ARVALID : OUT STD_LOGIC;
    m_axi_V_ARREADY : IN STD_LOGIC;
    m_axi_V_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_V_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_V_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_V_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_V_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_V_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_V_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_V_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_V_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_V_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_V_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_V_RVALID : IN STD_LOGIC;
    m_axi_V_RREADY : OUT STD_LOGIC;
    m_axi_V_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axi_V_RLAST : IN STD_LOGIC;
    m_axi_V_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_V_RFIFONUM : IN STD_LOGIC_VECTOR (12 downto 0);
    m_axi_V_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_V_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_V_BVALID : IN STD_LOGIC;
    m_axi_V_BREADY : OUT STD_LOGIC;
    m_axi_V_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_V_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_V_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    W_ddr_tile : IN STD_LOGIC_VECTOR (63 downto 0);
    out_w1_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    out_w1_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
    out_w1_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
    out_w1_full_n : IN STD_LOGIC;
    out_w1_write : OUT STD_LOGIC );
end;


architecture behav of ViT_Block_WeightTiledStreaming_3_17_192_192_1_1_1_1_1_1_ap_int_8_17 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_11 : STD_LOGIC_VECTOR (4 downto 0) := "10001";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv8_C0 : STD_LOGIC_VECTOR (7 downto 0) := "11000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal m_8_fu_141_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal m_8_reg_248 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln1238_fu_153_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln1238_reg_256 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal sext_ln1239_fu_189_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln1239_reg_261 : STD_LOGIC_VECTOR (17 downto 0);
    signal icmp_ln1238_fu_147_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln1239_fu_207_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln1239_reg_269 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal add_ln1243_fu_222_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln1243_reg_274 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln1239_fu_201_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_ap_start : STD_LOGIC;
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_ap_done : STD_LOGIC;
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_ap_idle : STD_LOGIC;
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_ap_ready : STD_LOGIC;
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_AWVALID : STD_LOGIC;
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_WVALID : STD_LOGIC;
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_WDATA : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_WSTRB : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_WLAST : STD_LOGIC;
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARVALID : STD_LOGIC;
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_RREADY : STD_LOGIC;
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_BREADY : STD_LOGIC;
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_burst_reads2_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_burst_reads2_write : STD_LOGIC;
    signal grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_ap_start : STD_LOGIC;
    signal grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_ap_done : STD_LOGIC;
    signal grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_ap_idle : STD_LOGIC;
    signal grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_ap_ready : STD_LOGIC;
    signal grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_out_w1_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_out_w1_write : STD_LOGIC;
    signal grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_burst_reads2_read : STD_LOGIC;
    signal k_reg_90 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln1237_fu_135_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal n_tile_reg_101 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_burst_read_beats_1_ap_int_8_s_fu_112_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal burst_reads_full_n : STD_LOGIC;
    signal burst_reads_write : STD_LOGIC;
    signal grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_ap_start_reg : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm_state7 : STD_LOGIC;
    signal burst_reads_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal burst_reads_empty_n : STD_LOGIC;
    signal burst_reads_read : STD_LOGIC;
    signal m_fu_76 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal p_shl_fu_159_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_shl1_fu_171_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_shl_cast_fu_167_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_shl1_cast_fu_179_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal empty_184_fu_183_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln1239_fu_197_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln1243_4_fu_213_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln1243_fu_218_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component ViT_Block_burst_read_beats_1_ap_int_8_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem1_AWVALID : OUT STD_LOGIC;
        m_axi_gmem1_AWREADY : IN STD_LOGIC;
        m_axi_gmem1_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_WVALID : OUT STD_LOGIC;
        m_axi_gmem1_WREADY : IN STD_LOGIC;
        m_axi_gmem1_WDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem1_WSTRB : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_WLAST : OUT STD_LOGIC;
        m_axi_gmem1_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_ARVALID : OUT STD_LOGIC;
        m_axi_gmem1_ARREADY : IN STD_LOGIC;
        m_axi_gmem1_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_RVALID : IN STD_LOGIC;
        m_axi_gmem1_RREADY : OUT STD_LOGIC;
        m_axi_gmem1_RDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        m_axi_gmem1_RLAST : IN STD_LOGIC;
        m_axi_gmem1_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_RFIFONUM : IN STD_LOGIC_VECTOR (12 downto 0);
        m_axi_gmem1_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_BVALID : IN STD_LOGIC;
        m_axi_gmem1_BREADY : OUT STD_LOGIC;
        m_axi_gmem1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        W_ddr : IN STD_LOGIC_VECTOR (63 downto 0);
        burst_reads2_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        burst_reads2_full_n : IN STD_LOGIC;
        burst_reads2_write : OUT STD_LOGIC );
    end component;


    component ViT_Block_packer_to_packs_1_1_1_ap_int_8_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        out_w1_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        out_w1_num_data_valid : IN STD_LOGIC_VECTOR (6 downto 0);
        out_w1_fifo_cap : IN STD_LOGIC_VECTOR (6 downto 0);
        out_w1_full_n : IN STD_LOGIC;
        out_w1_write : OUT STD_LOGIC;
        burst_reads2_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        burst_reads2_empty_n : IN STD_LOGIC;
        burst_reads2_read : OUT STD_LOGIC );
    end component;


    component ViT_Block_fifo_w8_d64_S_x1 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    grp_burst_read_beats_1_ap_int_8_s_fu_112 : component ViT_Block_burst_read_beats_1_ap_int_8_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_burst_read_beats_1_ap_int_8_s_fu_112_ap_start,
        ap_done => grp_burst_read_beats_1_ap_int_8_s_fu_112_ap_done,
        ap_idle => grp_burst_read_beats_1_ap_int_8_s_fu_112_ap_idle,
        ap_ready => grp_burst_read_beats_1_ap_int_8_s_fu_112_ap_ready,
        m_axi_gmem1_AWVALID => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY => ap_const_logic_0,
        m_axi_gmem1_AWADDR => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY => ap_const_logic_0,
        m_axi_gmem1_WDATA => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_WLAST,
        m_axi_gmem1_WID => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_WID,
        m_axi_gmem1_WUSER => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY => m_axi_V_ARREADY,
        m_axi_gmem1_ARADDR => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID => m_axi_V_RVALID,
        m_axi_gmem1_RREADY => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA => m_axi_V_RDATA,
        m_axi_gmem1_RLAST => m_axi_V_RLAST,
        m_axi_gmem1_RID => m_axi_V_RID,
        m_axi_gmem1_RFIFONUM => m_axi_V_RFIFONUM,
        m_axi_gmem1_RUSER => m_axi_V_RUSER,
        m_axi_gmem1_RRESP => m_axi_V_RRESP,
        m_axi_gmem1_BVALID => ap_const_logic_0,
        m_axi_gmem1_BREADY => grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP => ap_const_lv2_0,
        m_axi_gmem1_BID => ap_const_lv1_0,
        m_axi_gmem1_BUSER => ap_const_lv1_0,
        W_ddr => add_ln1243_reg_274,
        burst_reads2_din => grp_burst_read_beats_1_ap_int_8_s_fu_112_burst_reads2_din,
        burst_reads2_full_n => burst_reads_full_n,
        burst_reads2_write => grp_burst_read_beats_1_ap_int_8_s_fu_112_burst_reads2_write);

    grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120 : component ViT_Block_packer_to_packs_1_1_1_ap_int_8_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_ap_start,
        ap_done => grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_ap_done,
        ap_idle => grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_ap_idle,
        ap_ready => grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_ap_ready,
        out_w1_din => grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_out_w1_din,
        out_w1_num_data_valid => ap_const_lv7_0,
        out_w1_fifo_cap => ap_const_lv7_0,
        out_w1_full_n => out_w1_full_n,
        out_w1_write => grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_out_w1_write,
        burst_reads2_dout => burst_reads_dout,
        burst_reads2_empty_n => burst_reads_empty_n,
        burst_reads2_read => grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_burst_reads2_read);

    burst_reads_fifo_U : component ViT_Block_fifo_w8_d64_S_x1
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => grp_burst_read_beats_1_ap_int_8_s_fu_112_burst_reads2_din,
        if_full_n => burst_reads_full_n,
        if_write => burst_reads_write,
        if_dout => burst_reads_dout,
        if_empty_n => burst_reads_empty_n,
        if_read => burst_reads_read);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln1237_fu_135_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_burst_read_beats_1_ap_int_8_s_fu_112_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_burst_read_beats_1_ap_int_8_s_fu_112_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_burst_read_beats_1_ap_int_8_s_fu_112_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_burst_read_beats_1_ap_int_8_s_fu_112_ap_ready = ap_const_logic_1)) then 
                    grp_burst_read_beats_1_ap_int_8_s_fu_112_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_NS_fsm_state7) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                    grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_ap_ready = ap_const_logic_1)) then 
                    grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    k_reg_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln1237_fu_135_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                k_reg_90 <= ap_const_lv8_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln1239_fu_201_p2 = ap_const_lv1_1))) then 
                k_reg_90 <= add_ln1238_reg_256;
            end if; 
        end if;
    end process;

    m_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                m_fu_76 <= ap_const_lv5_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln1238_fu_147_p2 = ap_const_lv1_1))) then 
                m_fu_76 <= m_8_reg_248;
            end if; 
        end if;
    end process;

    n_tile_reg_101_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln1238_fu_147_p2 = ap_const_lv1_0))) then 
                n_tile_reg_101 <= ap_const_lv8_0;
            elsif (((grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
                n_tile_reg_101 <= add_ln1239_reg_269;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                add_ln1238_reg_256 <= add_ln1238_fu_153_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                add_ln1239_reg_269 <= add_ln1239_fu_207_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln1239_fu_201_p2 = ap_const_lv1_0))) then
                add_ln1243_reg_274 <= add_ln1243_fu_222_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                m_8_reg_248 <= m_8_fu_141_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln1238_fu_147_p2 = ap_const_lv1_0))) then
                    sext_ln1239_reg_261(17 downto 6) <= sext_ln1239_fu_189_p1(17 downto 6);
            end if;
        end if;
    end process;
    sext_ln1239_reg_261(5 downto 0) <= "000000";

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, icmp_ln1238_fu_147_p2, ap_CS_fsm_state4, icmp_ln1239_fu_201_p2, grp_burst_read_beats_1_ap_int_8_s_fu_112_ap_done, grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_ap_done, icmp_ln1237_fu_135_p2, ap_CS_fsm_state8, ap_CS_fsm_state6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln1237_fu_135_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln1238_fu_147_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln1239_fu_201_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_burst_read_beats_1_ap_int_8_s_fu_112_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    add_ln1238_fu_153_p2 <= std_logic_vector(unsigned(k_reg_90) + unsigned(ap_const_lv8_1));
    add_ln1239_fu_207_p2 <= std_logic_vector(unsigned(n_tile_reg_101) + unsigned(ap_const_lv8_1));
    add_ln1243_4_fu_213_p2 <= std_logic_vector(signed(sext_ln1239_reg_261) + signed(zext_ln1239_fu_197_p1));
    add_ln1243_fu_222_p2 <= std_logic_vector(signed(sext_ln1243_fu_218_p1) + signed(W_ddr_tile));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_NS_fsm_state7 <= ap_NS_fsm(6);

    ap_ST_fsm_state1_blk_assign_proc : process(real_start, ap_done_reg)
    begin
        if (((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_burst_read_beats_1_ap_int_8_s_fu_112_ap_done)
    begin
        if ((grp_burst_read_beats_1_ap_int_8_s_fu_112_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_ap_done)
    begin
        if ((grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln1237_fu_135_p2)
    begin
        if (((icmp_ln1237_fu_135_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    burst_reads_read_assign_proc : process(grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_burst_reads2_read, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            burst_reads_read <= grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_burst_reads2_read;
        else 
            burst_reads_read <= ap_const_logic_0;
        end if; 
    end process;


    burst_reads_write_assign_proc : process(grp_burst_read_beats_1_ap_int_8_s_fu_112_burst_reads2_write, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            burst_reads_write <= grp_burst_read_beats_1_ap_int_8_s_fu_112_burst_reads2_write;
        else 
            burst_reads_write <= ap_const_logic_0;
        end if; 
    end process;

    empty_184_fu_183_p2 <= std_logic_vector(unsigned(p_shl_cast_fu_167_p1) - unsigned(p_shl1_cast_fu_179_p1));
    grp_burst_read_beats_1_ap_int_8_s_fu_112_ap_start <= grp_burst_read_beats_1_ap_int_8_s_fu_112_ap_start_reg;
    grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_ap_start <= grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_ap_start_reg;
    icmp_ln1237_fu_135_p2 <= "1" when (m_fu_76 = ap_const_lv5_11) else "0";
    icmp_ln1238_fu_147_p2 <= "1" when (k_reg_90 = ap_const_lv8_C0) else "0";
    icmp_ln1239_fu_201_p2 <= "1" when (n_tile_reg_101 = ap_const_lv8_C0) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln1237_fu_135_p2)
    begin
        if (((icmp_ln1237_fu_135_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    m_8_fu_141_p2 <= std_logic_vector(unsigned(m_fu_76) + unsigned(ap_const_lv5_1));
    m_axi_V_ARADDR <= grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARADDR;
    m_axi_V_ARBURST <= grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARBURST;
    m_axi_V_ARCACHE <= grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARCACHE;
    m_axi_V_ARID <= grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARID;
    m_axi_V_ARLEN <= grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARLEN;
    m_axi_V_ARLOCK <= grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARLOCK;
    m_axi_V_ARPROT <= grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARPROT;
    m_axi_V_ARQOS <= grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARQOS;
    m_axi_V_ARREGION <= grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARREGION;
    m_axi_V_ARSIZE <= grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARSIZE;
    m_axi_V_ARUSER <= grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARUSER;

    m_axi_V_ARVALID_assign_proc : process(grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARVALID, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            m_axi_V_ARVALID <= grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_ARVALID;
        else 
            m_axi_V_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_V_AWADDR <= ap_const_lv64_0;
    m_axi_V_AWBURST <= ap_const_lv2_0;
    m_axi_V_AWCACHE <= ap_const_lv4_0;
    m_axi_V_AWID <= ap_const_lv1_0;
    m_axi_V_AWLEN <= ap_const_lv32_0;
    m_axi_V_AWLOCK <= ap_const_lv2_0;
    m_axi_V_AWPROT <= ap_const_lv3_0;
    m_axi_V_AWQOS <= ap_const_lv4_0;
    m_axi_V_AWREGION <= ap_const_lv4_0;
    m_axi_V_AWSIZE <= ap_const_lv3_0;
    m_axi_V_AWUSER <= ap_const_lv1_0;
    m_axi_V_AWVALID <= ap_const_logic_0;
    m_axi_V_BREADY <= ap_const_logic_0;

    m_axi_V_RREADY_assign_proc : process(grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_RREADY, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            m_axi_V_RREADY <= grp_burst_read_beats_1_ap_int_8_s_fu_112_m_axi_gmem1_RREADY;
        else 
            m_axi_V_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_V_WDATA <= ap_const_lv8_0;
    m_axi_V_WID <= ap_const_lv1_0;
    m_axi_V_WLAST <= ap_const_logic_0;
    m_axi_V_WSTRB <= ap_const_lv1_0;
    m_axi_V_WUSER <= ap_const_lv1_0;
    m_axi_V_WVALID <= ap_const_logic_0;
    out_w1_din <= grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_out_w1_din;

    out_w1_write_assign_proc : process(grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_out_w1_write, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            out_w1_write <= grp_packer_to_packs_1_1_1_ap_int_8_s_fu_120_out_w1_write;
        else 
            out_w1_write <= ap_const_logic_0;
        end if; 
    end process;

    p_shl1_cast_fu_179_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl1_fu_171_p3),17));
    p_shl1_fu_171_p3 <= (k_reg_90 & ap_const_lv6_0);
    p_shl_cast_fu_167_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl_fu_159_p3),17));
    p_shl_fu_159_p3 <= (k_reg_90 & ap_const_lv8_0);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

        sext_ln1239_fu_189_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(empty_184_fu_183_p2),18));

        sext_ln1243_fu_218_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln1243_4_fu_213_p2),64));

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln1239_fu_197_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(n_tile_reg_101),18));
end behav;
