// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ViT_Block_FC1_tiled_oc_2 (
        ap_start,
        start_full_n,
        start_out,
        start_write,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        in_w,
        norm_out_113_dout,
        norm_out_113_empty_n,
        norm_out_113_read,
        fc11_din,
        fc11_full_n,
        fc11_write,
        ap_clk,
        ap_rst,
        in_w_ap_vld,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input   ap_start;
input   start_full_n;
output   start_out;
output   start_write;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [63:0] m_axi_gmem0_AWADDR;
output  [0:0] m_axi_gmem0_AWID;
output  [31:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [0:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [7:0] m_axi_gmem0_WDATA;
output  [0:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [0:0] m_axi_gmem0_WID;
output  [0:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [63:0] m_axi_gmem0_ARADDR;
output  [0:0] m_axi_gmem0_ARID;
output  [31:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [0:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [7:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [0:0] m_axi_gmem0_RID;
input  [12:0] m_axi_gmem0_RFIFONUM;
input  [0:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [0:0] m_axi_gmem0_BID;
input  [0:0] m_axi_gmem0_BUSER;
input  [63:0] in_w;
input  [7:0] norm_out_113_dout;
input   norm_out_113_empty_n;
output   norm_out_113_read;
output  [7:0] fc11_din;
input   fc11_full_n;
output   fc11_write;
input   ap_clk;
input   ap_rst;
input   in_w_ap_vld;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

reg start_write;

reg    real_start;
reg    start_once_reg;
wire    internal_ap_ready;
wire    WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_ap_start;
wire    WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_ap_done;
wire    WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_ap_continue;
wire    WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_ap_idle;
wire    WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_ap_ready;
wire    WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_start_out;
wire    WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_start_write;
wire    WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWVALID;
wire   [63:0] WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWADDR;
wire   [0:0] WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWID;
wire   [31:0] WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWLEN;
wire   [2:0] WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWSIZE;
wire   [1:0] WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWBURST;
wire   [1:0] WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWLOCK;
wire   [3:0] WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWCACHE;
wire   [2:0] WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWPROT;
wire   [3:0] WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWQOS;
wire   [3:0] WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWREGION;
wire   [0:0] WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWUSER;
wire    WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_WVALID;
wire   [7:0] WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_WDATA;
wire   [0:0] WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_WSTRB;
wire    WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_WLAST;
wire   [0:0] WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_WID;
wire   [0:0] WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_WUSER;
wire    WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARVALID;
wire   [63:0] WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARADDR;
wire   [0:0] WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARID;
wire   [31:0] WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARLEN;
wire   [2:0] WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARSIZE;
wire   [1:0] WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARBURST;
wire   [1:0] WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARLOCK;
wire   [3:0] WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARCACHE;
wire   [2:0] WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARPROT;
wire   [3:0] WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARQOS;
wire   [3:0] WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARREGION;
wire   [0:0] WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARUSER;
wire    WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_RREADY;
wire    WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_BREADY;
wire   [7:0] WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_out_w1_din;
wire    WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_out_w1_write;
wire    Linear_Layer_1_U0_ap_start;
wire    Linear_Layer_1_U0_ap_done;
wire    Linear_Layer_1_U0_ap_continue;
wire    Linear_Layer_1_U0_ap_idle;
wire    Linear_Layer_1_U0_ap_ready;
wire    Linear_Layer_1_U0_norm_out_113_read;
wire   [7:0] Linear_Layer_1_U0_fc11_din;
wire    Linear_Layer_1_U0_fc11_write;
wire    Linear_Layer_1_U0_out_w1_read;
wire    out_w_full_n;
wire   [7:0] out_w_dout;
wire   [6:0] out_w_num_data_valid;
wire   [6:0] out_w_fifo_cap;
wire    out_w_empty_n;
wire    ap_sync_ready;
wire   [0:0] start_for_Linear_Layer_1_U0_din;
wire    start_for_Linear_Layer_1_U0_full_n;
wire   [0:0] start_for_Linear_Layer_1_U0_dout;
wire    start_for_Linear_Layer_1_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
end

ViT_Block_WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_s WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_ap_start),
    .start_full_n(start_for_Linear_Layer_1_U0_full_n),
    .ap_done(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_ap_done),
    .ap_continue(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_ap_continue),
    .ap_idle(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_ap_idle),
    .ap_ready(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_ap_ready),
    .start_out(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_start_out),
    .start_write(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_start_write),
    .m_axi_gmem0_AWVALID(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(1'b0),
    .m_axi_gmem0_AWADDR(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(1'b0),
    .m_axi_gmem0_WDATA(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(m_axi_gmem0_ARREADY),
    .m_axi_gmem0_ARADDR(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(m_axi_gmem0_RVALID),
    .m_axi_gmem0_RREADY(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(m_axi_gmem0_RDATA),
    .m_axi_gmem0_RLAST(m_axi_gmem0_RLAST),
    .m_axi_gmem0_RID(m_axi_gmem0_RID),
    .m_axi_gmem0_RFIFONUM(m_axi_gmem0_RFIFONUM),
    .m_axi_gmem0_RUSER(m_axi_gmem0_RUSER),
    .m_axi_gmem0_RRESP(m_axi_gmem0_RRESP),
    .m_axi_gmem0_BVALID(1'b0),
    .m_axi_gmem0_BREADY(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(2'd0),
    .m_axi_gmem0_BID(1'd0),
    .m_axi_gmem0_BUSER(1'd0),
    .W_ddr_tile(in_w),
    .out_w1_din(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_out_w1_din),
    .out_w1_num_data_valid(out_w_num_data_valid),
    .out_w1_fifo_cap(out_w_fifo_cap),
    .out_w1_full_n(out_w_full_n),
    .out_w1_write(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_out_w1_write)
);

ViT_Block_Linear_Layer_1 Linear_Layer_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Linear_Layer_1_U0_ap_start),
    .ap_done(Linear_Layer_1_U0_ap_done),
    .ap_continue(Linear_Layer_1_U0_ap_continue),
    .ap_idle(Linear_Layer_1_U0_ap_idle),
    .ap_ready(Linear_Layer_1_U0_ap_ready),
    .norm_out_113_dout(norm_out_113_dout),
    .norm_out_113_num_data_valid(2'd0),
    .norm_out_113_fifo_cap(2'd0),
    .norm_out_113_empty_n(norm_out_113_empty_n),
    .norm_out_113_read(Linear_Layer_1_U0_norm_out_113_read),
    .fc11_din(Linear_Layer_1_U0_fc11_din),
    .fc11_num_data_valid(7'd0),
    .fc11_fifo_cap(7'd0),
    .fc11_full_n(fc11_full_n),
    .fc11_write(Linear_Layer_1_U0_fc11_write),
    .out_w1_dout(out_w_dout),
    .out_w1_num_data_valid(out_w_num_data_valid),
    .out_w1_fifo_cap(out_w_fifo_cap),
    .out_w1_empty_n(out_w_empty_n),
    .out_w1_read(Linear_Layer_1_U0_out_w1_read)
);

ViT_Block_fifo_w8_d64_S_x6 out_w_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_out_w1_din),
    .if_full_n(out_w_full_n),
    .if_write(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_out_w1_write),
    .if_dout(out_w_dout),
    .if_num_data_valid(out_w_num_data_valid),
    .if_fifo_cap(out_w_fifo_cap),
    .if_empty_n(out_w_empty_n),
    .if_read(Linear_Layer_1_U0_out_w1_read)
);

ViT_Block_start_for_Linear_Layer_1_U0 start_for_Linear_Layer_1_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Linear_Layer_1_U0_din),
    .if_full_n(start_for_Linear_Layer_1_U0_full_n),
    .if_write(WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_start_write),
    .if_dout(start_for_Linear_Layer_1_U0_dout),
    .if_empty_n(start_for_Linear_Layer_1_U0_empty_n),
    .if_read(Linear_Layer_1_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

assign Linear_Layer_1_U0_ap_continue = ap_continue;

assign Linear_Layer_1_U0_ap_start = start_for_Linear_Layer_1_U0_empty_n;

assign WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_ap_continue = 1'b1;

assign WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_ap_start = real_start;

assign ap_done = Linear_Layer_1_U0_ap_done;

assign ap_idle = (WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_ap_idle & Linear_Layer_1_U0_ap_idle);

assign ap_ready = WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_ap_ready;

assign ap_sync_ready = WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_ap_ready;

assign fc11_din = Linear_Layer_1_U0_fc11_din;

assign fc11_write = Linear_Layer_1_U0_fc11_write;

assign internal_ap_ready = ap_sync_ready;

assign m_axi_gmem0_ARADDR = WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARADDR;

assign m_axi_gmem0_ARBURST = WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARBURST;

assign m_axi_gmem0_ARCACHE = WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARCACHE;

assign m_axi_gmem0_ARID = WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARID;

assign m_axi_gmem0_ARLEN = WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARLEN;

assign m_axi_gmem0_ARLOCK = WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARLOCK;

assign m_axi_gmem0_ARPROT = WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARPROT;

assign m_axi_gmem0_ARQOS = WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARQOS;

assign m_axi_gmem0_ARREGION = WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARREGION;

assign m_axi_gmem0_ARSIZE = WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARSIZE;

assign m_axi_gmem0_ARUSER = WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARUSER;

assign m_axi_gmem0_ARVALID = WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_ARVALID;

assign m_axi_gmem0_AWADDR = 64'd0;

assign m_axi_gmem0_AWBURST = 2'd0;

assign m_axi_gmem0_AWCACHE = 4'd0;

assign m_axi_gmem0_AWID = 1'd0;

assign m_axi_gmem0_AWLEN = 32'd0;

assign m_axi_gmem0_AWLOCK = 2'd0;

assign m_axi_gmem0_AWPROT = 3'd0;

assign m_axi_gmem0_AWQOS = 4'd0;

assign m_axi_gmem0_AWREGION = 4'd0;

assign m_axi_gmem0_AWSIZE = 3'd0;

assign m_axi_gmem0_AWUSER = 1'd0;

assign m_axi_gmem0_AWVALID = 1'b0;

assign m_axi_gmem0_BREADY = 1'b0;

assign m_axi_gmem0_RREADY = WeightTiledStreaming_3_17_192_768_1_1_1_1_1_1_ap_int_8_U0_m_axi_gmem0_RREADY;

assign m_axi_gmem0_WDATA = 8'd0;

assign m_axi_gmem0_WID = 1'd0;

assign m_axi_gmem0_WLAST = 1'b0;

assign m_axi_gmem0_WSTRB = 1'd0;

assign m_axi_gmem0_WUSER = 1'd0;

assign m_axi_gmem0_WVALID = 1'b0;

assign norm_out_113_read = Linear_Layer_1_U0_norm_out_113_read;

assign start_for_Linear_Layer_1_U0_din = 1'b1;

assign start_out = real_start;

endmodule //ViT_Block_FC1_tiled_oc_2
